# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

FFI::DynamicLibrary::SEARCH_PATH ||= ["c:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin"]

module Index
  extend FFI::Library

  def self.library_names
    ["clang"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  CINDEX_VERSION_MAJOR = 0
  CINDEX_VERSION_MINOR = 64
  typedef :pointer, :cx_index
  typedef :pointer, :cx_target_info
  typedef :pointer, :cx_translation_unit
  typedef :pointer, :cx_client_data

  class CXUnsavedFile < FFI::Struct
    layout :filename, :string,
           :contents, :string,
           :length, :ulong
  end

  CXAvailabilityKind = enum(
    :CXAvailability_Available, 0,
    :CXAvailability_Deprecated, 1,
    :CXAvailability_NotAvailable, 2,
    :CXAvailability_NotAccessible, 3
  )

  class CXVersion < FFI::Struct
    layout :major, :int,
           :minor, :int,
           :subminor, :int
  end

  CXCursorExceptionSpecificationKind = enum(
    :CXCursor_ExceptionSpecificationKind_None, 0,
    :CXCursor_ExceptionSpecificationKind_DynamicNone, 1,
    :CXCursor_ExceptionSpecificationKind_Dynamic, 2,
    :CXCursor_ExceptionSpecificationKind_MSAny, 3,
    :CXCursor_ExceptionSpecificationKind_BasicNoexcept, 4,
    :CXCursor_ExceptionSpecificationKind_ComputedNoexcept, 5,
    :CXCursor_ExceptionSpecificationKind_Unevaluated, 6,
    :CXCursor_ExceptionSpecificationKind_Uninstantiated, 7,
    :CXCursor_ExceptionSpecificationKind_Unparsed, 8,
    :CXCursor_ExceptionSpecificationKind_NoThrow, 9
  )

  attach_function :clang_create_index, :clang_createIndex, [:int, :int], :pointer
  attach_function :clang_dispose_index, :clang_disposeIndex, [:pointer], :void

  CXChoice = enum(
    :CXChoice_Default, 0,
    :CXChoice_Enabled, 1,
    :CXChoice_Disabled, 2
  )

  CXGlobalOptFlags = enum(
    :CXGlobalOpt_None, 0,
    :CXGlobalOpt_ThreadBackgroundPriorityForIndexing, 1,
    :CXGlobalOpt_ThreadBackgroundPriorityForEditing, 2,
    :CXGlobalOpt_ThreadBackgroundPriorityForAll, 3
  )

  class CXIndexOptions < FFI::Struct
    layout :size, :uint,
           :thread_background_priority_for_indexing, :uchar,
           :thread_background_priority_for_editing, :uchar,
           :exclude_declarations_from_pch, :uint,
           :display_diagnostics, :uint,
           :store_preambles_in_memory, :uint,
           :unnamed_9, :uint,
           :preamble_storage_path, :string,
           :invocation_emission_path, :string
  end

  attach_function :clang_create_index_with_options, :clang_createIndexWithOptions, [CXIndexOptions.by_ref], :pointer
  attach_function :clang_cx_index_set_global_options, :clang_CXIndex_setGlobalOptions, [:pointer, :uint], :void
  attach_function :clang_cx_index_get_global_options, :clang_CXIndex_getGlobalOptions, [:pointer], :uint
  attach_function :clang_cx_index_set_invocation_emission_path_option, :clang_CXIndex_setInvocationEmissionPathOption, [:pointer, :string], :void
  attach_function :clang_is_file_multiple_include_guarded, :clang_isFileMultipleIncludeGuarded, [:pointer, :pointer], :uint
  attach_function :clang_get_file, :clang_getFile, [:pointer, :string], :pointer
  attach_function :clang_get_file_contents, :clang_getFileContents, [:pointer, :pointer, :pointer], :string
  attach_function :clang_get_location, :clang_getLocation, [:pointer, :pointer, :uint, :uint], CXSourceLocation.by_value
  attach_function :clang_get_location_for_offset, :clang_getLocationForOffset, [:pointer, :pointer, :uint], CXSourceLocation.by_value
  attach_function :clang_get_skipped_ranges, :clang_getSkippedRanges, [:pointer, :pointer], CXSourceRangeList.by_ref
  attach_function :clang_get_all_skipped_ranges, :clang_getAllSkippedRanges, [:pointer], CXSourceRangeList.by_ref
  attach_function :clang_get_num_diagnostics, :clang_getNumDiagnostics, [:pointer], :uint
  attach_function :clang_get_diagnostic, :clang_getDiagnostic, [:pointer, :uint], :pointer
  attach_function :clang_get_diagnostic_set_from_tu, :clang_getDiagnosticSetFromTU, [:pointer], :pointer
  attach_function :clang_get_translation_unit_spelling, :clang_getTranslationUnitSpelling, [:pointer], CXString.by_value
  attach_function :clang_create_translation_unit_from_source_file, :clang_createTranslationUnitFromSourceFile, [:pointer, :string, :int, :pointer, :uint, CXUnsavedFile.by_ref], :pointer
  attach_function :clang_create_translation_unit, :clang_createTranslationUnit, [:pointer, :string], :pointer
  attach_function :clang_create_translation_unit2, :clang_createTranslationUnit2, [:pointer, :string, :pointer], CXErrorCode

  CXTranslationUnitFlags = enum(
    :CXTranslationUnit_None, 0,
    :CXTranslationUnit_DetailedPreprocessingRecord, 1,
    :CXTranslationUnit_Incomplete, 2,
    :CXTranslationUnit_PrecompiledPreamble, 4,
    :CXTranslationUnit_CacheCompletionResults, 8,
    :CXTranslationUnit_ForSerialization, 16,
    :CXTranslationUnit_CXXChainedPCH, 32,
    :CXTranslationUnit_SkipFunctionBodies, 64,
    :CXTranslationUnit_IncludeBriefCommentsInCodeCompletion, 128,
    :CXTranslationUnit_CreatePreambleOnFirstParse, 256,
    :CXTranslationUnit_KeepGoing, 512,
    :CXTranslationUnit_SingleFileParse, 1024,
    :CXTranslationUnit_LimitSkipFunctionBodiesToPreamble, 2048,
    :CXTranslationUnit_IncludeAttributedTypes, 4096,
    :CXTranslationUnit_VisitImplicitAttributes, 8192,
    :CXTranslationUnit_IgnoreNonErrorsFromIncludedFiles, 16384,
    :CXTranslationUnit_RetainExcludedConditionalBlocks, 32768
  )

  attach_function :clang_default_editing_translation_unit_options, :clang_defaultEditingTranslationUnitOptions, [], :uint
  attach_function :clang_parse_translation_unit, :clang_parseTranslationUnit, [:pointer, :string, :pointer, :int, CXUnsavedFile.by_ref, :uint, :uint], :pointer
  attach_function :clang_parse_translation_unit2, :clang_parseTranslationUnit2, [:pointer, :string, :pointer, :int, CXUnsavedFile.by_ref, :uint, :uint, :pointer], CXErrorCode
  attach_function :clang_parse_translation_unit2_full_argv, :clang_parseTranslationUnit2FullArgv, [:pointer, :string, :pointer, :int, CXUnsavedFile.by_ref, :uint, :uint, :pointer], CXErrorCode

  CXSaveTranslationUnitFlags = enum(
    :CXSaveTranslationUnit_None, 0
  )

  attach_function :clang_default_save_options, :clang_defaultSaveOptions, [:pointer], :uint

  CXSaveError = enum(
    :CXSaveError_None, 0,
    :CXSaveError_Unknown, 1,
    :CXSaveError_TranslationErrors, 2,
    :CXSaveError_InvalidTU, 3
  )

  attach_function :clang_save_translation_unit, :clang_saveTranslationUnit, [:pointer, :string, :uint], :int
  attach_function :clang_suspend_translation_unit, :clang_suspendTranslationUnit, [:pointer], :uint
  attach_function :clang_dispose_translation_unit, :clang_disposeTranslationUnit, [:pointer], :void

  CXReparseFlags = enum(
    :CXReparse_None, 0
  )

  attach_function :clang_default_reparse_options, :clang_defaultReparseOptions, [:pointer], :uint
  attach_function :clang_reparse_translation_unit, :clang_reparseTranslationUnit, [:pointer, :uint, CXUnsavedFile.by_ref, :uint], :int

  CXTUResourceUsageKind = enum(
    :CXTUResourceUsage_AST, 1,
    :CXTUResourceUsage_Identifiers, 2,
    :CXTUResourceUsage_Selectors, 3,
    :CXTUResourceUsage_GlobalCompletionResults, 4,
    :CXTUResourceUsage_SourceManagerContentCache, 5,
    :CXTUResourceUsage_AST_SideTables, 6,
    :CXTUResourceUsage_SourceManager_Membuffer_Malloc, 7,
    :CXTUResourceUsage_SourceManager_Membuffer_MMap, 8,
    :CXTUResourceUsage_ExternalASTSource_Membuffer_Malloc, 9,
    :CXTUResourceUsage_ExternalASTSource_Membuffer_MMap, 10,
    :CXTUResourceUsage_Preprocessor, 11,
    :CXTUResourceUsage_PreprocessingRecord, 12,
    :CXTUResourceUsage_SourceManager_DataStructures, 13,
    :CXTUResourceUsage_Preprocessor_HeaderSearch, 14,
    :CXTUResourceUsage_MEMORY_IN_BYTES_BEGIN, 1,
    :CXTUResourceUsage_MEMORY_IN_BYTES_END, 14,
    :CXTUResourceUsage_First, 1,
    :CXTUResourceUsage_Last, 14
  )

  attach_function :clang_get_tu_resource_usage_name, :clang_getTUResourceUsageName, [CXTUResourceUsageKind], :string

  class CXTUResourceUsageEntry < FFI::Struct
    layout :kind, CXTUResourceUsageKind,
           :amount, :ulong
  end

  class CXTUResourceUsage < FFI::Struct
    layout :data, :pointer,
           :num_entries, :uint,
           :entries, CXTUResourceUsageEntry.ptr
  end

  attach_function :clang_get_cxtu_resource_usage, :clang_getCXTUResourceUsage, [:pointer], CXTUResourceUsage.by_value
  attach_function :clang_dispose_cxtu_resource_usage, :clang_disposeCXTUResourceUsage, [CXTUResourceUsage.by_value], :void
  attach_function :clang_get_translation_unit_target_info, :clang_getTranslationUnitTargetInfo, [:pointer], :pointer
  attach_function :clang_target_info_dispose, :clang_TargetInfo_dispose, [:pointer], :void
  attach_function :clang_target_info_get_triple, :clang_TargetInfo_getTriple, [:pointer], CXString.by_value
  attach_function :clang_target_info_get_pointer_width, :clang_TargetInfo_getPointerWidth, [:pointer], :int

  CXCursorKind = enum(
    :CXCursor_UnexposedDecl, 1,
    :CXCursor_StructDecl, 2,
    :CXCursor_UnionDecl, 3,
    :CXCursor_ClassDecl, 4,
    :CXCursor_EnumDecl, 5,
    :CXCursor_FieldDecl, 6,
    :CXCursor_EnumConstantDecl, 7,
    :CXCursor_FunctionDecl, 8,
    :CXCursor_VarDecl, 9,
    :CXCursor_ParmDecl, 10,
    :CXCursor_ObjCInterfaceDecl, 11,
    :CXCursor_ObjCCategoryDecl, 12,
    :CXCursor_ObjCProtocolDecl, 13,
    :CXCursor_ObjCPropertyDecl, 14,
    :CXCursor_ObjCIvarDecl, 15,
    :CXCursor_ObjCInstanceMethodDecl, 16,
    :CXCursor_ObjCClassMethodDecl, 17,
    :CXCursor_ObjCImplementationDecl, 18,
    :CXCursor_ObjCCategoryImplDecl, 19,
    :CXCursor_TypedefDecl, 20,
    :CXCursor_CXXMethod, 21,
    :CXCursor_Namespace, 22,
    :CXCursor_LinkageSpec, 23,
    :CXCursor_Constructor, 24,
    :CXCursor_Destructor, 25,
    :CXCursor_ConversionFunction, 26,
    :CXCursor_TemplateTypeParameter, 27,
    :CXCursor_NonTypeTemplateParameter, 28,
    :CXCursor_TemplateTemplateParameter, 29,
    :CXCursor_FunctionTemplate, 30,
    :CXCursor_ClassTemplate, 31,
    :CXCursor_ClassTemplatePartialSpecialization, 32,
    :CXCursor_NamespaceAlias, 33,
    :CXCursor_UsingDirective, 34,
    :CXCursor_UsingDeclaration, 35,
    :CXCursor_TypeAliasDecl, 36,
    :CXCursor_ObjCSynthesizeDecl, 37,
    :CXCursor_ObjCDynamicDecl, 38,
    :CXCursor_CXXAccessSpecifier, 39,
    :CXCursor_FirstDecl, 1,
    :CXCursor_LastDecl, 39,
    :CXCursor_FirstRef, 40,
    :CXCursor_ObjCSuperClassRef, 40,
    :CXCursor_ObjCProtocolRef, 41,
    :CXCursor_ObjCClassRef, 42,
    :CXCursor_TypeRef, 43,
    :CXCursor_CXXBaseSpecifier, 44,
    :CXCursor_TemplateRef, 45,
    :CXCursor_NamespaceRef, 46,
    :CXCursor_MemberRef, 47,
    :CXCursor_LabelRef, 48,
    :CXCursor_OverloadedDeclRef, 49,
    :CXCursor_VariableRef, 50,
    :CXCursor_LastRef, 50,
    :CXCursor_FirstInvalid, 70,
    :CXCursor_InvalidFile, 70,
    :CXCursor_NoDeclFound, 71,
    :CXCursor_NotImplemented, 72,
    :CXCursor_InvalidCode, 73,
    :CXCursor_LastInvalid, 73,
    :CXCursor_FirstExpr, 100,
    :CXCursor_UnexposedExpr, 100,
    :CXCursor_DeclRefExpr, 101,
    :CXCursor_MemberRefExpr, 102,
    :CXCursor_CallExpr, 103,
    :CXCursor_ObjCMessageExpr, 104,
    :CXCursor_BlockExpr, 105,
    :CXCursor_IntegerLiteral, 106,
    :CXCursor_FloatingLiteral, 107,
    :CXCursor_ImaginaryLiteral, 108,
    :CXCursor_StringLiteral, 109,
    :CXCursor_CharacterLiteral, 110,
    :CXCursor_ParenExpr, 111,
    :CXCursor_UnaryOperator, 112,
    :CXCursor_ArraySubscriptExpr, 113,
    :CXCursor_BinaryOperator, 114,
    :CXCursor_CompoundAssignOperator, 115,
    :CXCursor_ConditionalOperator, 116,
    :CXCursor_CStyleCastExpr, 117,
    :CXCursor_CompoundLiteralExpr, 118,
    :CXCursor_InitListExpr, 119,
    :CXCursor_AddrLabelExpr, 120,
    :CXCursor_StmtExpr, 121,
    :CXCursor_GenericSelectionExpr, 122,
    :CXCursor_GNUNullExpr, 123,
    :CXCursor_CXXStaticCastExpr, 124,
    :CXCursor_CXXDynamicCastExpr, 125,
    :CXCursor_CXXReinterpretCastExpr, 126,
    :CXCursor_CXXConstCastExpr, 127,
    :CXCursor_CXXFunctionalCastExpr, 128,
    :CXCursor_CXXTypeidExpr, 129,
    :CXCursor_CXXBoolLiteralExpr, 130,
    :CXCursor_CXXNullPtrLiteralExpr, 131,
    :CXCursor_CXXThisExpr, 132,
    :CXCursor_CXXThrowExpr, 133,
    :CXCursor_CXXNewExpr, 134,
    :CXCursor_CXXDeleteExpr, 135,
    :CXCursor_UnaryExpr, 136,
    :CXCursor_ObjCStringLiteral, 137,
    :CXCursor_ObjCEncodeExpr, 138,
    :CXCursor_ObjCSelectorExpr, 139,
    :CXCursor_ObjCProtocolExpr, 140,
    :CXCursor_ObjCBridgedCastExpr, 141,
    :CXCursor_PackExpansionExpr, 142,
    :CXCursor_SizeOfPackExpr, 143,
    :CXCursor_LambdaExpr, 144,
    :CXCursor_ObjCBoolLiteralExpr, 145,
    :CXCursor_ObjCSelfExpr, 146,
    :CXCursor_OMPArraySectionExpr, 147,
    :CXCursor_ObjCAvailabilityCheckExpr, 148,
    :CXCursor_FixedPointLiteral, 149,
    :CXCursor_OMPArrayShapingExpr, 150,
    :CXCursor_OMPIteratorExpr, 151,
    :CXCursor_CXXAddrspaceCastExpr, 152,
    :CXCursor_ConceptSpecializationExpr, 153,
    :CXCursor_RequiresExpr, 154,
    :CXCursor_CXXParenListInitExpr, 155,
    :CXCursor_PackIndexingExpr, 156,
    :CXCursor_LastExpr, 156,
    :CXCursor_FirstStmt, 200,
    :CXCursor_UnexposedStmt, 200,
    :CXCursor_LabelStmt, 201,
    :CXCursor_CompoundStmt, 202,
    :CXCursor_CaseStmt, 203,
    :CXCursor_DefaultStmt, 204,
    :CXCursor_IfStmt, 205,
    :CXCursor_SwitchStmt, 206,
    :CXCursor_WhileStmt, 207,
    :CXCursor_DoStmt, 208,
    :CXCursor_ForStmt, 209,
    :CXCursor_GotoStmt, 210,
    :CXCursor_IndirectGotoStmt, 211,
    :CXCursor_ContinueStmt, 212,
    :CXCursor_BreakStmt, 213,
    :CXCursor_ReturnStmt, 214,
    :CXCursor_GCCAsmStmt, 215,
    :CXCursor_AsmStmt, 215,
    :CXCursor_ObjCAtTryStmt, 216,
    :CXCursor_ObjCAtCatchStmt, 217,
    :CXCursor_ObjCAtFinallyStmt, 218,
    :CXCursor_ObjCAtThrowStmt, 219,
    :CXCursor_ObjCAtSynchronizedStmt, 220,
    :CXCursor_ObjCAutoreleasePoolStmt, 221,
    :CXCursor_ObjCForCollectionStmt, 222,
    :CXCursor_CXXCatchStmt, 223,
    :CXCursor_CXXTryStmt, 224,
    :CXCursor_CXXForRangeStmt, 225,
    :CXCursor_SEHTryStmt, 226,
    :CXCursor_SEHExceptStmt, 227,
    :CXCursor_SEHFinallyStmt, 228,
    :CXCursor_MSAsmStmt, 229,
    :CXCursor_NullStmt, 230,
    :CXCursor_DeclStmt, 231,
    :CXCursor_OMPParallelDirective, 232,
    :CXCursor_OMPSimdDirective, 233,
    :CXCursor_OMPForDirective, 234,
    :CXCursor_OMPSectionsDirective, 235,
    :CXCursor_OMPSectionDirective, 236,
    :CXCursor_OMPSingleDirective, 237,
    :CXCursor_OMPParallelForDirective, 238,
    :CXCursor_OMPParallelSectionsDirective, 239,
    :CXCursor_OMPTaskDirective, 240,
    :CXCursor_OMPMasterDirective, 241,
    :CXCursor_OMPCriticalDirective, 242,
    :CXCursor_OMPTaskyieldDirective, 243,
    :CXCursor_OMPBarrierDirective, 244,
    :CXCursor_OMPTaskwaitDirective, 245,
    :CXCursor_OMPFlushDirective, 246,
    :CXCursor_SEHLeaveStmt, 247,
    :CXCursor_OMPOrderedDirective, 248,
    :CXCursor_OMPAtomicDirective, 249,
    :CXCursor_OMPForSimdDirective, 250,
    :CXCursor_OMPParallelForSimdDirective, 251,
    :CXCursor_OMPTargetDirective, 252,
    :CXCursor_OMPTeamsDirective, 253,
    :CXCursor_OMPTaskgroupDirective, 254,
    :CXCursor_OMPCancellationPointDirective, 255,
    :CXCursor_OMPCancelDirective, 256,
    :CXCursor_OMPTargetDataDirective, 257,
    :CXCursor_OMPTaskLoopDirective, 258,
    :CXCursor_OMPTaskLoopSimdDirective, 259,
    :CXCursor_OMPDistributeDirective, 260,
    :CXCursor_OMPTargetEnterDataDirective, 261,
    :CXCursor_OMPTargetExitDataDirective, 262,
    :CXCursor_OMPTargetParallelDirective, 263,
    :CXCursor_OMPTargetParallelForDirective, 264,
    :CXCursor_OMPTargetUpdateDirective, 265,
    :CXCursor_OMPDistributeParallelForDirective, 266,
    :CXCursor_OMPDistributeParallelForSimdDirective, 267,
    :CXCursor_OMPDistributeSimdDirective, 268,
    :CXCursor_OMPTargetParallelForSimdDirective, 269,
    :CXCursor_OMPTargetSimdDirective, 270,
    :CXCursor_OMPTeamsDistributeDirective, 271,
    :CXCursor_OMPTeamsDistributeSimdDirective, 272,
    :CXCursor_OMPTeamsDistributeParallelForSimdDirective, 273,
    :CXCursor_OMPTeamsDistributeParallelForDirective, 274,
    :CXCursor_OMPTargetTeamsDirective, 275,
    :CXCursor_OMPTargetTeamsDistributeDirective, 276,
    :CXCursor_OMPTargetTeamsDistributeParallelForDirective, 277,
    :CXCursor_OMPTargetTeamsDistributeParallelForSimdDirective, 278,
    :CXCursor_OMPTargetTeamsDistributeSimdDirective, 279,
    :CXCursor_BuiltinBitCastExpr, 280,
    :CXCursor_OMPMasterTaskLoopDirective, 281,
    :CXCursor_OMPParallelMasterTaskLoopDirective, 282,
    :CXCursor_OMPMasterTaskLoopSimdDirective, 283,
    :CXCursor_OMPParallelMasterTaskLoopSimdDirective, 284,
    :CXCursor_OMPParallelMasterDirective, 285,
    :CXCursor_OMPDepobjDirective, 286,
    :CXCursor_OMPScanDirective, 287,
    :CXCursor_OMPTileDirective, 288,
    :CXCursor_OMPCanonicalLoop, 289,
    :CXCursor_OMPInteropDirective, 290,
    :CXCursor_OMPDispatchDirective, 291,
    :CXCursor_OMPMaskedDirective, 292,
    :CXCursor_OMPUnrollDirective, 293,
    :CXCursor_OMPMetaDirective, 294,
    :CXCursor_OMPGenericLoopDirective, 295,
    :CXCursor_OMPTeamsGenericLoopDirective, 296,
    :CXCursor_OMPTargetTeamsGenericLoopDirective, 297,
    :CXCursor_OMPParallelGenericLoopDirective, 298,
    :CXCursor_OMPTargetParallelGenericLoopDirective, 299,
    :CXCursor_OMPParallelMaskedDirective, 300,
    :CXCursor_OMPMaskedTaskLoopDirective, 301,
    :CXCursor_OMPMaskedTaskLoopSimdDirective, 302,
    :CXCursor_OMPParallelMaskedTaskLoopDirective, 303,
    :CXCursor_OMPParallelMaskedTaskLoopSimdDirective, 304,
    :CXCursor_OMPErrorDirective, 305,
    :CXCursor_OMPScopeDirective, 306,
    :CXCursor_OpenACCComputeConstruct, 320,
    :CXCursor_LastStmt, 320,
    :CXCursor_TranslationUnit, 350,
    :CXCursor_FirstAttr, 400,
    :CXCursor_UnexposedAttr, 400,
    :CXCursor_IBActionAttr, 401,
    :CXCursor_IBOutletAttr, 402,
    :CXCursor_IBOutletCollectionAttr, 403,
    :CXCursor_CXXFinalAttr, 404,
    :CXCursor_CXXOverrideAttr, 405,
    :CXCursor_AnnotateAttr, 406,
    :CXCursor_AsmLabelAttr, 407,
    :CXCursor_PackedAttr, 408,
    :CXCursor_PureAttr, 409,
    :CXCursor_ConstAttr, 410,
    :CXCursor_NoDuplicateAttr, 411,
    :CXCursor_CUDAConstantAttr, 412,
    :CXCursor_CUDADeviceAttr, 413,
    :CXCursor_CUDAGlobalAttr, 414,
    :CXCursor_CUDAHostAttr, 415,
    :CXCursor_CUDASharedAttr, 416,
    :CXCursor_VisibilityAttr, 417,
    :CXCursor_DLLExport, 418,
    :CXCursor_DLLImport, 419,
    :CXCursor_NSReturnsRetained, 420,
    :CXCursor_NSReturnsNotRetained, 421,
    :CXCursor_NSReturnsAutoreleased, 422,
    :CXCursor_NSConsumesSelf, 423,
    :CXCursor_NSConsumed, 424,
    :CXCursor_ObjCException, 425,
    :CXCursor_ObjCNSObject, 426,
    :CXCursor_ObjCIndependentClass, 427,
    :CXCursor_ObjCPreciseLifetime, 428,
    :CXCursor_ObjCReturnsInnerPointer, 429,
    :CXCursor_ObjCRequiresSuper, 430,
    :CXCursor_ObjCRootClass, 431,
    :CXCursor_ObjCSubclassingRestricted, 432,
    :CXCursor_ObjCExplicitProtocolImpl, 433,
    :CXCursor_ObjCDesignatedInitializer, 434,
    :CXCursor_ObjCRuntimeVisible, 435,
    :CXCursor_ObjCBoxable, 436,
    :CXCursor_FlagEnum, 437,
    :CXCursor_ConvergentAttr, 438,
    :CXCursor_WarnUnusedAttr, 439,
    :CXCursor_WarnUnusedResultAttr, 440,
    :CXCursor_AlignedAttr, 441,
    :CXCursor_LastAttr, 441,
    :CXCursor_PreprocessingDirective, 500,
    :CXCursor_MacroDefinition, 501,
    :CXCursor_MacroExpansion, 502,
    :CXCursor_MacroInstantiation, 502,
    :CXCursor_InclusionDirective, 503,
    :CXCursor_FirstPreprocessing, 500,
    :CXCursor_LastPreprocessing, 503,
    :CXCursor_ModuleImportDecl, 600,
    :CXCursor_TypeAliasTemplateDecl, 601,
    :CXCursor_StaticAssert, 602,
    :CXCursor_FriendDecl, 603,
    :CXCursor_ConceptDecl, 604,
    :CXCursor_FirstExtraDecl, 600,
    :CXCursor_LastExtraDecl, 604,
    :CXCursor_OverloadCandidate, 700
  )

  class CXCursor < FFI::Struct
    layout :kind, CXCursorKind,
           :xdata, :int,
           :data, [:pointer, 3]
  end

  attach_function :clang_get_null_cursor, :clang_getNullCursor, [], CXCursor.by_value
  attach_function :clang_get_translation_unit_cursor, :clang_getTranslationUnitCursor, [:pointer], CXCursor.by_value
  attach_function :clang_equal_cursors, :clang_equalCursors, [CXCursor.by_value, CXCursor.by_value], :uint
  attach_function :clang_cursor_is_null, :clang_Cursor_isNull, [CXCursor.by_value], :int
  attach_function :clang_hash_cursor, :clang_hashCursor, [CXCursor.by_value], :uint
  attach_function :clang_get_cursor_kind, :clang_getCursorKind, [CXCursor.by_value], CXCursorKind
  attach_function :clang_is_declaration, :clang_isDeclaration, [CXCursorKind], :uint
  attach_function :clang_is_invalid_declaration, :clang_isInvalidDeclaration, [CXCursor.by_value], :uint
  attach_function :clang_is_reference, :clang_isReference, [CXCursorKind], :uint
  attach_function :clang_is_expression, :clang_isExpression, [CXCursorKind], :uint
  attach_function :clang_is_statement, :clang_isStatement, [CXCursorKind], :uint
  attach_function :clang_is_attribute, :clang_isAttribute, [CXCursorKind], :uint
  attach_function :clang_cursor_has_attrs, :clang_Cursor_hasAttrs, [CXCursor.by_value], :uint
  attach_function :clang_is_invalid, :clang_isInvalid, [CXCursorKind], :uint
  attach_function :clang_is_translation_unit, :clang_isTranslationUnit, [CXCursorKind], :uint
  attach_function :clang_is_preprocessing, :clang_isPreprocessing, [CXCursorKind], :uint
  attach_function :clang_is_unexposed, :clang_isUnexposed, [CXCursorKind], :uint

  CXLinkageKind = enum(
    :CXLinkage_Invalid, 0,
    :CXLinkage_NoLinkage, 1,
    :CXLinkage_Internal, 2,
    :CXLinkage_UniqueExternal, 3,
    :CXLinkage_External, 4
  )

  attach_function :clang_get_cursor_linkage, :clang_getCursorLinkage, [CXCursor.by_value], CXLinkageKind

  CXVisibilityKind = enum(
    :CXVisibility_Invalid, 0,
    :CXVisibility_Hidden, 1,
    :CXVisibility_Protected, 2,
    :CXVisibility_Default, 3
  )

  attach_function :clang_get_cursor_visibility, :clang_getCursorVisibility, [CXCursor.by_value], CXVisibilityKind
  attach_function :clang_get_cursor_availability, :clang_getCursorAvailability, [CXCursor.by_value], CXAvailabilityKind

  class CXPlatformAvailability < FFI::Struct
    layout :platform, CXString,
           :introduced, CXVersion,
           :deprecated, CXVersion,
           :obsoleted, CXVersion,
           :unavailable, :int,
           :message, CXString
  end

  attach_function :clang_get_cursor_platform_availability, :clang_getCursorPlatformAvailability, [CXCursor.by_value, :pointer, CXString.by_ref, :pointer, CXString.by_ref, CXPlatformAvailability.by_ref, :int], :int
  attach_function :clang_dispose_cx_platform_availability, :clang_disposeCXPlatformAvailability, [CXPlatformAvailability.by_ref], :void
  attach_function :clang_cursor_get_var_decl_initializer, :clang_Cursor_getVarDeclInitializer, [CXCursor.by_value], CXCursor.by_value
  attach_function :clang_cursor_has_var_decl_global_storage, :clang_Cursor_hasVarDeclGlobalStorage, [CXCursor.by_value], :int
  attach_function :clang_cursor_has_var_decl_external_storage, :clang_Cursor_hasVarDeclExternalStorage, [CXCursor.by_value], :int

  CXLanguageKind = enum(
    :CXLanguage_Invalid, 0,
    :CXLanguage_C, 1,
    :CXLanguage_ObjC, 2,
    :CXLanguage_CPlusPlus, 3
  )

  attach_function :clang_get_cursor_language, :clang_getCursorLanguage, [CXCursor.by_value], CXLanguageKind

  CXTLSKind = enum(
    :CXTLS_None, 0,
    :CXTLS_Dynamic, 1,
    :CXTLS_Static, 2
  )

  attach_function :clang_get_cursor_tls_kind, :clang_getCursorTLSKind, [CXCursor.by_value], CXTLSKind
  attach_function :clang_cursor_get_translation_unit, :clang_Cursor_getTranslationUnit, [CXCursor.by_value], :pointer
  typedef :pointer, :cx_cursor_set
  attach_function :clang_create_cx_cursor_set, :clang_createCXCursorSet, [], :pointer
  attach_function :clang_dispose_cx_cursor_set, :clang_disposeCXCursorSet, [:pointer], :void
  attach_function :clang_cx_cursor_set_contains, :clang_CXCursorSet_contains, [:pointer, CXCursor.by_value], :uint
  attach_function :clang_cx_cursor_set_insert, :clang_CXCursorSet_insert, [:pointer, CXCursor.by_value], :uint
  attach_function :clang_get_cursor_semantic_parent, :clang_getCursorSemanticParent, [CXCursor.by_value], CXCursor.by_value
  attach_function :clang_get_cursor_lexical_parent, :clang_getCursorLexicalParent, [CXCursor.by_value], CXCursor.by_value
  attach_function :clang_get_overridden_cursors, :clang_getOverriddenCursors, [CXCursor.by_value, :pointer, :pointer], :void
  attach_function :clang_dispose_overridden_cursors, :clang_disposeOverriddenCursors, [CXCursor.by_ref], :void
  attach_function :clang_get_included_file, :clang_getIncludedFile, [CXCursor.by_value], :pointer
  attach_function :clang_get_cursor, :clang_getCursor, [:pointer, CXSourceLocation.by_value], CXCursor.by_value
  attach_function :clang_get_cursor_location, :clang_getCursorLocation, [CXCursor.by_value], CXSourceLocation.by_value
  attach_function :clang_get_cursor_extent, :clang_getCursorExtent, [CXCursor.by_value], CXSourceRange.by_value

  CXTypeKind = enum(
    :CXType_Invalid, 0,
    :CXType_Unexposed, 1,
    :CXType_Void, 2,
    :CXType_Bool, 3,
    :CXType_Char_U, 4,
    :CXType_UChar, 5,
    :CXType_Char16, 6,
    :CXType_Char32, 7,
    :CXType_UShort, 8,
    :CXType_UInt, 9,
    :CXType_ULong, 10,
    :CXType_ULongLong, 11,
    :CXType_UInt128, 12,
    :CXType_Char_S, 13,
    :CXType_SChar, 14,
    :CXType_WChar, 15,
    :CXType_Short, 16,
    :CXType_Int, 17,
    :CXType_Long, 18,
    :CXType_LongLong, 19,
    :CXType_Int128, 20,
    :CXType_Float, 21,
    :CXType_Double, 22,
    :CXType_LongDouble, 23,
    :CXType_NullPtr, 24,
    :CXType_Overload, 25,
    :CXType_Dependent, 26,
    :CXType_ObjCId, 27,
    :CXType_ObjCClass, 28,
    :CXType_ObjCSel, 29,
    :CXType_Float128, 30,
    :CXType_Half, 31,
    :CXType_Float16, 32,
    :CXType_ShortAccum, 33,
    :CXType_Accum, 34,
    :CXType_LongAccum, 35,
    :CXType_UShortAccum, 36,
    :CXType_UAccum, 37,
    :CXType_ULongAccum, 38,
    :CXType_BFloat16, 39,
    :CXType_Ibm128, 40,
    :CXType_FirstBuiltin, 2,
    :CXType_LastBuiltin, 40,
    :CXType_Complex, 100,
    :CXType_Pointer, 101,
    :CXType_BlockPointer, 102,
    :CXType_LValueReference, 103,
    :CXType_RValueReference, 104,
    :CXType_Record, 105,
    :CXType_Enum, 106,
    :CXType_Typedef, 107,
    :CXType_ObjCInterface, 108,
    :CXType_ObjCObjectPointer, 109,
    :CXType_FunctionNoProto, 110,
    :CXType_FunctionProto, 111,
    :CXType_ConstantArray, 112,
    :CXType_Vector, 113,
    :CXType_IncompleteArray, 114,
    :CXType_VariableArray, 115,
    :CXType_DependentSizedArray, 116,
    :CXType_MemberPointer, 117,
    :CXType_Auto, 118,
    :CXType_Elaborated, 119,
    :CXType_Pipe, 120,
    :CXType_OCLImage1dRO, 121,
    :CXType_OCLImage1dArrayRO, 122,
    :CXType_OCLImage1dBufferRO, 123,
    :CXType_OCLImage2dRO, 124,
    :CXType_OCLImage2dArrayRO, 125,
    :CXType_OCLImage2dDepthRO, 126,
    :CXType_OCLImage2dArrayDepthRO, 127,
    :CXType_OCLImage2dMSAARO, 128,
    :CXType_OCLImage2dArrayMSAARO, 129,
    :CXType_OCLImage2dMSAADepthRO, 130,
    :CXType_OCLImage2dArrayMSAADepthRO, 131,
    :CXType_OCLImage3dRO, 132,
    :CXType_OCLImage1dWO, 133,
    :CXType_OCLImage1dArrayWO, 134,
    :CXType_OCLImage1dBufferWO, 135,
    :CXType_OCLImage2dWO, 136,
    :CXType_OCLImage2dArrayWO, 137,
    :CXType_OCLImage2dDepthWO, 138,
    :CXType_OCLImage2dArrayDepthWO, 139,
    :CXType_OCLImage2dMSAAWO, 140,
    :CXType_OCLImage2dArrayMSAAWO, 141,
    :CXType_OCLImage2dMSAADepthWO, 142,
    :CXType_OCLImage2dArrayMSAADepthWO, 143,
    :CXType_OCLImage3dWO, 144,
    :CXType_OCLImage1dRW, 145,
    :CXType_OCLImage1dArrayRW, 146,
    :CXType_OCLImage1dBufferRW, 147,
    :CXType_OCLImage2dRW, 148,
    :CXType_OCLImage2dArrayRW, 149,
    :CXType_OCLImage2dDepthRW, 150,
    :CXType_OCLImage2dArrayDepthRW, 151,
    :CXType_OCLImage2dMSAARW, 152,
    :CXType_OCLImage2dArrayMSAARW, 153,
    :CXType_OCLImage2dMSAADepthRW, 154,
    :CXType_OCLImage2dArrayMSAADepthRW, 155,
    :CXType_OCLImage3dRW, 156,
    :CXType_OCLSampler, 157,
    :CXType_OCLEvent, 158,
    :CXType_OCLQueue, 159,
    :CXType_OCLReserveID, 160,
    :CXType_ObjCObject, 161,
    :CXType_ObjCTypeParam, 162,
    :CXType_Attributed, 163,
    :CXType_OCLIntelSubgroupAVCMcePayload, 164,
    :CXType_OCLIntelSubgroupAVCImePayload, 165,
    :CXType_OCLIntelSubgroupAVCRefPayload, 166,
    :CXType_OCLIntelSubgroupAVCSicPayload, 167,
    :CXType_OCLIntelSubgroupAVCMceResult, 168,
    :CXType_OCLIntelSubgroupAVCImeResult, 169,
    :CXType_OCLIntelSubgroupAVCRefResult, 170,
    :CXType_OCLIntelSubgroupAVCSicResult, 171,
    :CXType_OCLIntelSubgroupAVCImeResultSingleReferenceStreamout, 172,
    :CXType_OCLIntelSubgroupAVCImeResultDualReferenceStreamout, 173,
    :CXType_OCLIntelSubgroupAVCImeSingleReferenceStreamin, 174,
    :CXType_OCLIntelSubgroupAVCImeDualReferenceStreamin, 175,
    :CXType_OCLIntelSubgroupAVCImeResultSingleRefStreamout, 172,
    :CXType_OCLIntelSubgroupAVCImeResultDualRefStreamout, 173,
    :CXType_OCLIntelSubgroupAVCImeSingleRefStreamin, 174,
    :CXType_OCLIntelSubgroupAVCImeDualRefStreamin, 175,
    :CXType_ExtVector, 176,
    :CXType_Atomic, 177,
    :CXType_BTFTagAttributed, 178
  )

  CXCallingConv = enum(
    :CXCallingConv_Default, 0,
    :CXCallingConv_C, 1,
    :CXCallingConv_X86StdCall, 2,
    :CXCallingConv_X86FastCall, 3,
    :CXCallingConv_X86ThisCall, 4,
    :CXCallingConv_X86Pascal, 5,
    :CXCallingConv_AAPCS, 6,
    :CXCallingConv_AAPCS_VFP, 7,
    :CXCallingConv_X86RegCall, 8,
    :CXCallingConv_IntelOclBicc, 9,
    :CXCallingConv_Win64, 10,
    :CXCallingConv_X86_64Win64, 10,
    :CXCallingConv_X86_64SysV, 11,
    :CXCallingConv_X86VectorCall, 12,
    :CXCallingConv_Swift, 13,
    :CXCallingConv_PreserveMost, 14,
    :CXCallingConv_PreserveAll, 15,
    :CXCallingConv_AArch64VectorCall, 16,
    :CXCallingConv_SwiftAsync, 17,
    :CXCallingConv_AArch64SVEPCS, 18,
    :CXCallingConv_M68kRTD, 19,
    :CXCallingConv_PreserveNone, 20,
    :CXCallingConv_RISCVVectorCall, 21,
    :CXCallingConv_Invalid, 100,
    :CXCallingConv_Unexposed, 200
  )

  class CXType < FFI::Struct
    layout :kind, CXTypeKind,
           :data, [:pointer, 2]
  end

  attach_function :clang_get_cursor_type, :clang_getCursorType, [CXCursor.by_value], CXType.by_value
  attach_function :clang_get_type_spelling, :clang_getTypeSpelling, [CXType.by_value], CXString.by_value
  attach_function :clang_get_typedef_decl_underlying_type, :clang_getTypedefDeclUnderlyingType, [CXCursor.by_value], CXType.by_value
  attach_function :clang_get_enum_decl_integer_type, :clang_getEnumDeclIntegerType, [CXCursor.by_value], CXType.by_value
  attach_function :clang_get_enum_constant_decl_value, :clang_getEnumConstantDeclValue, [CXCursor.by_value], :long_long
  attach_function :clang_get_enum_constant_decl_unsigned_value, :clang_getEnumConstantDeclUnsignedValue, [CXCursor.by_value], :ulong_long
  attach_function :clang_cursor_is_bit_field, :clang_Cursor_isBitField, [CXCursor.by_value], :uint
  attach_function :clang_get_field_decl_bit_width, :clang_getFieldDeclBitWidth, [CXCursor.by_value], :int
  attach_function :clang_cursor_get_num_arguments, :clang_Cursor_getNumArguments, [CXCursor.by_value], :int
  attach_function :clang_cursor_get_argument, :clang_Cursor_getArgument, [CXCursor.by_value, :uint], CXCursor.by_value

  CXTemplateArgumentKind = enum(
    :CXTemplateArgumentKind_Null, 0,
    :CXTemplateArgumentKind_Type, 1,
    :CXTemplateArgumentKind_Declaration, 2,
    :CXTemplateArgumentKind_NullPtr, 3,
    :CXTemplateArgumentKind_Integral, 4,
    :CXTemplateArgumentKind_Template, 5,
    :CXTemplateArgumentKind_TemplateExpansion, 6,
    :CXTemplateArgumentKind_Expression, 7,
    :CXTemplateArgumentKind_Pack, 8,
    :CXTemplateArgumentKind_Invalid, 9
  )

  attach_function :clang_cursor_get_num_template_arguments, :clang_Cursor_getNumTemplateArguments, [CXCursor.by_value], :int
  attach_function :clang_cursor_get_template_argument_kind, :clang_Cursor_getTemplateArgumentKind, [CXCursor.by_value, :uint], CXTemplateArgumentKind
  attach_function :clang_cursor_get_template_argument_type, :clang_Cursor_getTemplateArgumentType, [CXCursor.by_value, :uint], CXType.by_value
  attach_function :clang_cursor_get_template_argument_value, :clang_Cursor_getTemplateArgumentValue, [CXCursor.by_value, :uint], :long_long
  attach_function :clang_cursor_get_template_argument_unsigned_value, :clang_Cursor_getTemplateArgumentUnsignedValue, [CXCursor.by_value, :uint], :ulong_long
  attach_function :clang_equal_types, :clang_equalTypes, [CXType.by_value, CXType.by_value], :uint
  attach_function :clang_get_canonical_type, :clang_getCanonicalType, [CXType.by_value], CXType.by_value
  attach_function :clang_is_const_qualified_type, :clang_isConstQualifiedType, [CXType.by_value], :uint
  attach_function :clang_cursor_is_macro_function_like, :clang_Cursor_isMacroFunctionLike, [CXCursor.by_value], :uint
  attach_function :clang_cursor_is_macro_builtin, :clang_Cursor_isMacroBuiltin, [CXCursor.by_value], :uint
  attach_function :clang_cursor_is_function_inlined, :clang_Cursor_isFunctionInlined, [CXCursor.by_value], :uint
  attach_function :clang_is_volatile_qualified_type, :clang_isVolatileQualifiedType, [CXType.by_value], :uint
  attach_function :clang_is_restrict_qualified_type, :clang_isRestrictQualifiedType, [CXType.by_value], :uint
  attach_function :clang_get_address_space, :clang_getAddressSpace, [CXType.by_value], :uint
  attach_function :clang_get_typedef_name, :clang_getTypedefName, [CXType.by_value], CXString.by_value
  attach_function :clang_get_pointee_type, :clang_getPointeeType, [CXType.by_value], CXType.by_value
  attach_function :clang_get_unqualified_type, :clang_getUnqualifiedType, [CXType.by_value], CXType.by_value
  attach_function :clang_get_non_reference_type, :clang_getNonReferenceType, [CXType.by_value], CXType.by_value
  attach_function :clang_get_type_declaration, :clang_getTypeDeclaration, [CXType.by_value], CXCursor.by_value
  attach_function :clang_get_decl_obj_c_type_encoding, :clang_getDeclObjCTypeEncoding, [CXCursor.by_value], CXString.by_value
  attach_function :clang_type_get_obj_c_encoding, :clang_Type_getObjCEncoding, [CXType.by_value], CXString.by_value
  attach_function :clang_get_type_kind_spelling, :clang_getTypeKindSpelling, [CXTypeKind], CXString.by_value
  attach_function :clang_get_function_type_calling_conv, :clang_getFunctionTypeCallingConv, [CXType.by_value], CXCallingConv
  attach_function :clang_get_result_type, :clang_getResultType, [CXType.by_value], CXType.by_value
  attach_function :clang_get_exception_specification_type, :clang_getExceptionSpecificationType, [CXType.by_value], :int
  attach_function :clang_get_num_arg_types, :clang_getNumArgTypes, [CXType.by_value], :int
  attach_function :clang_get_arg_type, :clang_getArgType, [CXType.by_value, :uint], CXType.by_value
  attach_function :clang_type_get_obj_c_object_base_type, :clang_Type_getObjCObjectBaseType, [CXType.by_value], CXType.by_value
  attach_function :clang_type_get_num_obj_c_protocol_refs, :clang_Type_getNumObjCProtocolRefs, [CXType.by_value], :uint
  attach_function :clang_type_get_obj_c_protocol_decl, :clang_Type_getObjCProtocolDecl, [CXType.by_value, :uint], CXCursor.by_value
  attach_function :clang_type_get_num_obj_c_type_args, :clang_Type_getNumObjCTypeArgs, [CXType.by_value], :uint
  attach_function :clang_type_get_obj_c_type_arg, :clang_Type_getObjCTypeArg, [CXType.by_value, :uint], CXType.by_value
  attach_function :clang_is_function_type_variadic, :clang_isFunctionTypeVariadic, [CXType.by_value], :uint
  attach_function :clang_get_cursor_result_type, :clang_getCursorResultType, [CXCursor.by_value], CXType.by_value
  attach_function :clang_get_cursor_exception_specification_type, :clang_getCursorExceptionSpecificationType, [CXCursor.by_value], :int
  attach_function :clang_is_pod_type, :clang_isPODType, [CXType.by_value], :uint
  attach_function :clang_get_element_type, :clang_getElementType, [CXType.by_value], CXType.by_value
  attach_function :clang_get_num_elements, :clang_getNumElements, [CXType.by_value], :long_long
  attach_function :clang_get_array_element_type, :clang_getArrayElementType, [CXType.by_value], CXType.by_value
  attach_function :clang_get_array_size, :clang_getArraySize, [CXType.by_value], :long_long
  attach_function :clang_type_get_named_type, :clang_Type_getNamedType, [CXType.by_value], CXType.by_value
  attach_function :clang_type_is_transparent_tag_typedef, :clang_Type_isTransparentTagTypedef, [CXType.by_value], :uint

  CXTypeNullabilityKind = enum(
    :CXTypeNullability_NonNull, 0,
    :CXTypeNullability_Nullable, 1,
    :CXTypeNullability_Unspecified, 2,
    :CXTypeNullability_Invalid, 3,
    :CXTypeNullability_NullableResult, 4
  )

  attach_function :clang_type_get_nullability, :clang_Type_getNullability, [CXType.by_value], CXTypeNullabilityKind

  CXTypeLayoutError = enum(
    :CXTypeLayoutError_Invalid, -1,
    :CXTypeLayoutError_Incomplete, -2,
    :CXTypeLayoutError_Dependent, -3,
    :CXTypeLayoutError_NotConstantSize, -4,
    :CXTypeLayoutError_InvalidFieldName, -5,
    :CXTypeLayoutError_Undeduced, -6
  )

  attach_function :clang_type_get_align_of, :clang_Type_getAlignOf, [CXType.by_value], :long_long
  attach_function :clang_type_get_class_type, :clang_Type_getClassType, [CXType.by_value], CXType.by_value
  attach_function :clang_type_get_size_of, :clang_Type_getSizeOf, [CXType.by_value], :long_long
  attach_function :clang_type_get_offset_of, :clang_Type_getOffsetOf, [CXType.by_value, :string], :long_long
  attach_function :clang_type_get_modified_type, :clang_Type_getModifiedType, [CXType.by_value], CXType.by_value
  attach_function :clang_type_get_value_type, :clang_Type_getValueType, [CXType.by_value], CXType.by_value
  attach_function :clang_cursor_get_offset_of_field, :clang_Cursor_getOffsetOfField, [CXCursor.by_value], :long_long
  attach_function :clang_cursor_is_anonymous, :clang_Cursor_isAnonymous, [CXCursor.by_value], :uint
  attach_function :clang_cursor_is_anonymous_record_decl, :clang_Cursor_isAnonymousRecordDecl, [CXCursor.by_value], :uint
  attach_function :clang_cursor_is_inline_namespace, :clang_Cursor_isInlineNamespace, [CXCursor.by_value], :uint

  CXRefQualifierKind = enum(
    :CXRefQualifier_None, 0,
    :CXRefQualifier_LValue, 1,
    :CXRefQualifier_RValue, 2
  )

  attach_function :clang_type_get_num_template_arguments, :clang_Type_getNumTemplateArguments, [CXType.by_value], :int
  attach_function :clang_type_get_template_argument_as_type, :clang_Type_getTemplateArgumentAsType, [CXType.by_value, :uint], CXType.by_value
  attach_function :clang_type_get_cxx_ref_qualifier, :clang_Type_getCXXRefQualifier, [CXType.by_value], CXRefQualifierKind
  attach_function :clang_is_virtual_base, :clang_isVirtualBase, [CXCursor.by_value], :uint

  CXCXXAccessSpecifier = enum(
    :CX_CXXInvalidAccessSpecifier, 0,
    :CX_CXXPublic, 1,
    :CX_CXXProtected, 2,
    :CX_CXXPrivate, 3
  )

  attach_function :clang_get_cxx_access_specifier, :clang_getCXXAccessSpecifier, [CXCursor.by_value], CXCXXAccessSpecifier

  CXStorageClass = enum(
    :CX_SC_Invalid, 0,
    :CX_SC_None, 1,
    :CX_SC_Extern, 2,
    :CX_SC_Static, 3,
    :CX_SC_PrivateExtern, 4,
    :CX_SC_OpenCLWorkGroupLocal, 5,
    :CX_SC_Auto, 6,
    :CX_SC_Register, 7
  )

  attach_function :clang_cursor_get_storage_class, :clang_Cursor_getStorageClass, [CXCursor.by_value], CXStorageClass
  attach_function :clang_get_num_overloaded_decls, :clang_getNumOverloadedDecls, [CXCursor.by_value], :uint
  attach_function :clang_get_overloaded_decl, :clang_getOverloadedDecl, [CXCursor.by_value, :uint], CXCursor.by_value
  attach_function :clang_get_ib_outlet_collection_type, :clang_getIBOutletCollectionType, [CXCursor.by_value], CXType.by_value

  CXChildVisitResult = enum(
    :CXChildVisit_Break, 0,
    :CXChildVisit_Continue, 1,
    :CXChildVisit_Recurse, 2
  )

  callback :cx_cursor_visitor, [], CXChildVisitResult
  attach_function :clang_visit_children, :clang_visitChildren, [CXCursor.by_value, :pointer, :pointer], :uint
  typedef :pointer, :cx_cursor_visitor_block
  attach_function :clang_visit_children_with_block, :clang_visitChildrenWithBlock, [CXCursor.by_value, :pointer], :uint
  attach_function :clang_get_cursor_usr, :clang_getCursorUSR, [CXCursor.by_value], CXString.by_value
  attach_function :clang_construct_usr_obj_c_class, :clang_constructUSR_ObjCClass, [:string], CXString.by_value
  attach_function :clang_construct_usr_obj_c_category, :clang_constructUSR_ObjCCategory, [:string, :string], CXString.by_value
  attach_function :clang_construct_usr_obj_c_protocol, :clang_constructUSR_ObjCProtocol, [:string], CXString.by_value
  attach_function :clang_construct_usr_obj_c_ivar, :clang_constructUSR_ObjCIvar, [:string, CXString.by_value], CXString.by_value
  attach_function :clang_construct_usr_obj_c_method, :clang_constructUSR_ObjCMethod, [:string, :uint, CXString.by_value], CXString.by_value
  attach_function :clang_construct_usr_obj_c_property, :clang_constructUSR_ObjCProperty, [:string, CXString.by_value], CXString.by_value
  attach_function :clang_get_cursor_spelling, :clang_getCursorSpelling, [CXCursor.by_value], CXString.by_value
  attach_function :clang_cursor_get_spelling_name_range, :clang_Cursor_getSpellingNameRange, [CXCursor.by_value, :uint, :uint], CXSourceRange.by_value
  typedef :pointer, :cx_printing_policy

  CXPrintingPolicyProperty = enum(
    :CXPrintingPolicy_Indentation, 0,
    :CXPrintingPolicy_SuppressSpecifiers, 1,
    :CXPrintingPolicy_SuppressTagKeyword, 2,
    :CXPrintingPolicy_IncludeTagDefinition, 3,
    :CXPrintingPolicy_SuppressScope, 4,
    :CXPrintingPolicy_SuppressUnwrittenScope, 5,
    :CXPrintingPolicy_SuppressInitializers, 6,
    :CXPrintingPolicy_ConstantArraySizeAsWritten, 7,
    :CXPrintingPolicy_AnonymousTagLocations, 8,
    :CXPrintingPolicy_SuppressStrongLifetime, 9,
    :CXPrintingPolicy_SuppressLifetimeQualifiers, 10,
    :CXPrintingPolicy_SuppressTemplateArgsInCXXConstructors, 11,
    :CXPrintingPolicy_Bool, 12,
    :CXPrintingPolicy_Restrict, 13,
    :CXPrintingPolicy_Alignof, 14,
    :CXPrintingPolicy_UnderscoreAlignof, 15,
    :CXPrintingPolicy_UseVoidForZeroParams, 16,
    :CXPrintingPolicy_TerseOutput, 17,
    :CXPrintingPolicy_PolishForDeclaration, 18,
    :CXPrintingPolicy_Half, 19,
    :CXPrintingPolicy_MSWChar, 20,
    :CXPrintingPolicy_IncludeNewlines, 21,
    :CXPrintingPolicy_MSVCFormatting, 22,
    :CXPrintingPolicy_ConstantsAsWritten, 23,
    :CXPrintingPolicy_SuppressImplicitBase, 24,
    :CXPrintingPolicy_FullyQualifiedName, 25,
    :CXPrintingPolicy_LastProperty, 25
  )

  attach_function :clang_printing_policy_get_property, :clang_PrintingPolicy_getProperty, [:pointer, CXPrintingPolicyProperty], :uint
  attach_function :clang_printing_policy_set_property, :clang_PrintingPolicy_setProperty, [:pointer, CXPrintingPolicyProperty, :uint], :void
  attach_function :clang_get_cursor_printing_policy, :clang_getCursorPrintingPolicy, [CXCursor.by_value], :pointer
  attach_function :clang_printing_policy_dispose, :clang_PrintingPolicy_dispose, [:pointer], :void
  attach_function :clang_get_cursor_pretty_printed, :clang_getCursorPrettyPrinted, [CXCursor.by_value, :pointer], CXString.by_value
  attach_function :clang_get_cursor_display_name, :clang_getCursorDisplayName, [CXCursor.by_value], CXString.by_value
  attach_function :clang_get_cursor_referenced, :clang_getCursorReferenced, [CXCursor.by_value], CXCursor.by_value
  attach_function :clang_get_cursor_definition, :clang_getCursorDefinition, [CXCursor.by_value], CXCursor.by_value
  attach_function :clang_is_cursor_definition, :clang_isCursorDefinition, [CXCursor.by_value], :uint
  attach_function :clang_get_canonical_cursor, :clang_getCanonicalCursor, [CXCursor.by_value], CXCursor.by_value
  attach_function :clang_cursor_get_obj_c_selector_index, :clang_Cursor_getObjCSelectorIndex, [CXCursor.by_value], :int
  attach_function :clang_cursor_is_dynamic_call, :clang_Cursor_isDynamicCall, [CXCursor.by_value], :int
  attach_function :clang_cursor_get_receiver_type, :clang_Cursor_getReceiverType, [CXCursor.by_value], CXType.by_value

  CXObjCPropertyAttrKind = enum(
    :CXObjCPropertyAttr_noattr, 0,
    :CXObjCPropertyAttr_readonly, 1,
    :CXObjCPropertyAttr_getter, 2,
    :CXObjCPropertyAttr_assign, 4,
    :CXObjCPropertyAttr_readwrite, 8,
    :CXObjCPropertyAttr_retain, 16,
    :CXObjCPropertyAttr_copy, 32,
    :CXObjCPropertyAttr_nonatomic, 64,
    :CXObjCPropertyAttr_setter, 128,
    :CXObjCPropertyAttr_atomic, 256,
    :CXObjCPropertyAttr_weak, 512,
    :CXObjCPropertyAttr_strong, 1024,
    :CXObjCPropertyAttr_unsafe_unretained, 2048,
    :CXObjCPropertyAttr_class, 4096
  )

  attach_function :clang_cursor_get_obj_c_property_attributes, :clang_Cursor_getObjCPropertyAttributes, [CXCursor.by_value, :uint], :uint
  attach_function :clang_cursor_get_obj_c_property_getter_name, :clang_Cursor_getObjCPropertyGetterName, [CXCursor.by_value], CXString.by_value
  attach_function :clang_cursor_get_obj_c_property_setter_name, :clang_Cursor_getObjCPropertySetterName, [CXCursor.by_value], CXString.by_value

  CXObjCDeclQualifierKind = enum(
    :CXObjCDeclQualifier_None, 0,
    :CXObjCDeclQualifier_In, 1,
    :CXObjCDeclQualifier_Inout, 2,
    :CXObjCDeclQualifier_Out, 4,
    :CXObjCDeclQualifier_Bycopy, 8,
    :CXObjCDeclQualifier_Byref, 16,
    :CXObjCDeclQualifier_Oneway, 32
  )

  attach_function :clang_cursor_get_obj_c_decl_qualifiers, :clang_Cursor_getObjCDeclQualifiers, [CXCursor.by_value], :uint
  attach_function :clang_cursor_is_obj_c_optional, :clang_Cursor_isObjCOptional, [CXCursor.by_value], :uint
  attach_function :clang_cursor_is_variadic, :clang_Cursor_isVariadic, [CXCursor.by_value], :uint
  attach_function :clang_cursor_is_external_symbol, :clang_Cursor_isExternalSymbol, [CXCursor.by_value, CXString.by_ref, CXString.by_ref, :pointer], :uint
  attach_function :clang_cursor_get_comment_range, :clang_Cursor_getCommentRange, [CXCursor.by_value], CXSourceRange.by_value
  attach_function :clang_cursor_get_raw_comment_text, :clang_Cursor_getRawCommentText, [CXCursor.by_value], CXString.by_value
  attach_function :clang_cursor_get_brief_comment_text, :clang_Cursor_getBriefCommentText, [CXCursor.by_value], CXString.by_value
  attach_function :clang_cursor_get_mangling, :clang_Cursor_getMangling, [CXCursor.by_value], CXString.by_value
  attach_function :clang_cursor_get_cxx_manglings, :clang_Cursor_getCXXManglings, [CXCursor.by_value], CXStringSet.by_ref
  attach_function :clang_cursor_get_obj_c_manglings, :clang_Cursor_getObjCManglings, [CXCursor.by_value], CXStringSet.by_ref
  typedef :pointer, :cx_module
  attach_function :clang_cursor_get_module, :clang_Cursor_getModule, [CXCursor.by_value], :pointer
  attach_function :clang_get_module_for_file, :clang_getModuleForFile, [:pointer, :pointer], :pointer
  attach_function :clang_module_get_ast_file, :clang_Module_getASTFile, [:pointer], :pointer
  attach_function :clang_module_get_parent, :clang_Module_getParent, [:pointer], :pointer
  attach_function :clang_module_get_name, :clang_Module_getName, [:pointer], CXString.by_value
  attach_function :clang_module_get_full_name, :clang_Module_getFullName, [:pointer], CXString.by_value
  attach_function :clang_module_is_system, :clang_Module_isSystem, [:pointer], :int
  attach_function :clang_module_get_num_top_level_headers, :clang_Module_getNumTopLevelHeaders, [:pointer, :pointer], :uint
  attach_function :clang_module_get_top_level_header, :clang_Module_getTopLevelHeader, [:pointer, :pointer, :uint], :pointer
  attach_function :clang_cxx_constructor_is_converting_constructor, :clang_CXXConstructor_isConvertingConstructor, [CXCursor.by_value], :uint
  attach_function :clang_cxx_constructor_is_copy_constructor, :clang_CXXConstructor_isCopyConstructor, [CXCursor.by_value], :uint
  attach_function :clang_cxx_constructor_is_default_constructor, :clang_CXXConstructor_isDefaultConstructor, [CXCursor.by_value], :uint
  attach_function :clang_cxx_constructor_is_move_constructor, :clang_CXXConstructor_isMoveConstructor, [CXCursor.by_value], :uint
  attach_function :clang_cxx_field_is_mutable, :clang_CXXField_isMutable, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_defaulted, :clang_CXXMethod_isDefaulted, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_deleted, :clang_CXXMethod_isDeleted, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_pure_virtual, :clang_CXXMethod_isPureVirtual, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_static, :clang_CXXMethod_isStatic, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_virtual, :clang_CXXMethod_isVirtual, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_copy_assignment_operator, :clang_CXXMethod_isCopyAssignmentOperator, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_move_assignment_operator, :clang_CXXMethod_isMoveAssignmentOperator, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_explicit, :clang_CXXMethod_isExplicit, [CXCursor.by_value], :uint
  attach_function :clang_cxx_record_is_abstract, :clang_CXXRecord_isAbstract, [CXCursor.by_value], :uint
  attach_function :clang_enum_decl_is_scoped, :clang_EnumDecl_isScoped, [CXCursor.by_value], :uint
  attach_function :clang_cxx_method_is_const, :clang_CXXMethod_isConst, [CXCursor.by_value], :uint
  attach_function :clang_get_template_cursor_kind, :clang_getTemplateCursorKind, [CXCursor.by_value], CXCursorKind
  attach_function :clang_get_specialized_cursor_template, :clang_getSpecializedCursorTemplate, [CXCursor.by_value], CXCursor.by_value
  attach_function :clang_get_cursor_reference_name_range, :clang_getCursorReferenceNameRange, [CXCursor.by_value, :uint, :uint], CXSourceRange.by_value

  CXNameRefFlags = enum(
    :CXNameRange_WantQualifier, 1,
    :CXNameRange_WantTemplateArgs, 2,
    :CXNameRange_WantSinglePiece, 4
  )

  CXTokenKind = enum(
    :CXToken_Punctuation, 0,
    :CXToken_Keyword, 1,
    :CXToken_Identifier, 2,
    :CXToken_Literal, 3,
    :CXToken_Comment, 4
  )

  class CXToken < FFI::Struct
    layout :int_data, [:uint, 4],
           :ptr_data, :pointer
  end

  attach_function :clang_get_token, :clang_getToken, [:pointer, CXSourceLocation.by_value], CXToken.by_ref
  attach_function :clang_get_token_kind, :clang_getTokenKind, [CXToken.by_value], CXTokenKind
  attach_function :clang_get_token_spelling, :clang_getTokenSpelling, [:pointer, CXToken.by_value], CXString.by_value
  attach_function :clang_get_token_location, :clang_getTokenLocation, [:pointer, CXToken.by_value], CXSourceLocation.by_value
  attach_function :clang_get_token_extent, :clang_getTokenExtent, [:pointer, CXToken.by_value], CXSourceRange.by_value
  attach_function :clang_tokenize, :clang_tokenize, [:pointer, CXSourceRange.by_value, :pointer, :pointer], :void
  attach_function :clang_annotate_tokens, :clang_annotateTokens, [:pointer, CXToken.by_ref, :uint, CXCursor.by_ref], :void
  attach_function :clang_dispose_tokens, :clang_disposeTokens, [:pointer, CXToken.by_ref, :uint], :void
  attach_function :clang_get_cursor_kind_spelling, :clang_getCursorKindSpelling, [CXCursorKind], CXString.by_value
  attach_function :clang_get_definition_spelling_and_extent, :clang_getDefinitionSpellingAndExtent, [CXCursor.by_value, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :void
  attach_function :clang_enable_stack_traces, :clang_enableStackTraces, [], :void
  callback :clang_executeOnThread_fn_callback, [:pointer], :void
  attach_function :clang_execute_on_thread, :clang_executeOnThread, [:clang_executeOnThread_fn_callback, :pointer, :uint], :void
  typedef :pointer, :cx_completion_string

  class CXCompletionResult < FFI::Struct
    layout :cursor_kind, CXCursorKind,
           :completion_string, :pointer
  end

  CXCompletionChunkKind = enum(
    :CXCompletionChunk_Optional, 0,
    :CXCompletionChunk_TypedText, 1,
    :CXCompletionChunk_Text, 2,
    :CXCompletionChunk_Placeholder, 3,
    :CXCompletionChunk_Informative, 4,
    :CXCompletionChunk_CurrentParameter, 5,
    :CXCompletionChunk_LeftParen, 6,
    :CXCompletionChunk_RightParen, 7,
    :CXCompletionChunk_LeftBracket, 8,
    :CXCompletionChunk_RightBracket, 9,
    :CXCompletionChunk_LeftBrace, 10,
    :CXCompletionChunk_RightBrace, 11,
    :CXCompletionChunk_LeftAngle, 12,
    :CXCompletionChunk_RightAngle, 13,
    :CXCompletionChunk_Comma, 14,
    :CXCompletionChunk_ResultType, 15,
    :CXCompletionChunk_Colon, 16,
    :CXCompletionChunk_SemiColon, 17,
    :CXCompletionChunk_Equal, 18,
    :CXCompletionChunk_HorizontalSpace, 19,
    :CXCompletionChunk_VerticalSpace, 20
  )

  attach_function :clang_get_completion_chunk_kind, :clang_getCompletionChunkKind, [:pointer, :uint], CXCompletionChunkKind
  attach_function :clang_get_completion_chunk_text, :clang_getCompletionChunkText, [:pointer, :uint], CXString.by_value
  attach_function :clang_get_completion_chunk_completion_string, :clang_getCompletionChunkCompletionString, [:pointer, :uint], :pointer
  attach_function :clang_get_num_completion_chunks, :clang_getNumCompletionChunks, [:pointer], :uint
  attach_function :clang_get_completion_priority, :clang_getCompletionPriority, [:pointer], :uint
  attach_function :clang_get_completion_availability, :clang_getCompletionAvailability, [:pointer], CXAvailabilityKind
  attach_function :clang_get_completion_num_annotations, :clang_getCompletionNumAnnotations, [:pointer], :uint
  attach_function :clang_get_completion_annotation, :clang_getCompletionAnnotation, [:pointer, :uint], CXString.by_value
  attach_function :clang_get_completion_parent, :clang_getCompletionParent, [:pointer, :pointer], CXString.by_value
  attach_function :clang_get_completion_brief_comment, :clang_getCompletionBriefComment, [:pointer], CXString.by_value
  attach_function :clang_get_cursor_completion_string, :clang_getCursorCompletionString, [CXCursor.by_value], :pointer

  class CXCodeCompleteResults < FFI::Struct
    layout :results, CXCompletionResult.ptr,
           :num_results, :uint
  end

  attach_function :clang_get_completion_num_fix_its, :clang_getCompletionNumFixIts, [CXCodeCompleteResults.by_ref, :uint], :uint
  attach_function :clang_get_completion_fix_it, :clang_getCompletionFixIt, [CXCodeCompleteResults.by_ref, :uint, :uint, CXSourceRange.by_ref], CXString.by_value

  CXCodeCompleteFlags = enum(
    :CXCodeComplete_IncludeMacros, 1,
    :CXCodeComplete_IncludeCodePatterns, 2,
    :CXCodeComplete_IncludeBriefComments, 4,
    :CXCodeComplete_SkipPreamble, 8,
    :CXCodeComplete_IncludeCompletionsWithFixIts, 16
  )

  CXCompletionContext = enum(
    :CXCompletionContext_Unexposed, 0,
    :CXCompletionContext_AnyType, 1,
    :CXCompletionContext_AnyValue, 2,
    :CXCompletionContext_ObjCObjectValue, 4,
    :CXCompletionContext_ObjCSelectorValue, 8,
    :CXCompletionContext_CXXClassTypeValue, 16,
    :CXCompletionContext_DotMemberAccess, 32,
    :CXCompletionContext_ArrowMemberAccess, 64,
    :CXCompletionContext_ObjCPropertyAccess, 128,
    :CXCompletionContext_EnumTag, 256,
    :CXCompletionContext_UnionTag, 512,
    :CXCompletionContext_StructTag, 1024,
    :CXCompletionContext_ClassTag, 2048,
    :CXCompletionContext_Namespace, 4096,
    :CXCompletionContext_NestedNameSpecifier, 8192,
    :CXCompletionContext_ObjCInterface, 16384,
    :CXCompletionContext_ObjCProtocol, 32768,
    :CXCompletionContext_ObjCCategory, 65536,
    :CXCompletionContext_ObjCInstanceMessage, 131072,
    :CXCompletionContext_ObjCClassMessage, 262144,
    :CXCompletionContext_ObjCSelectorName, 524288,
    :CXCompletionContext_MacroName, 1048576,
    :CXCompletionContext_NaturalLanguage, 2097152,
    :CXCompletionContext_IncludedFile, 4194304,
    :CXCompletionContext_Unknown, 8388607
  )

  attach_function :clang_default_code_complete_options, :clang_defaultCodeCompleteOptions, [], :uint
  attach_function :clang_code_complete_at, :clang_codeCompleteAt, [:pointer, :string, :uint, :uint, CXUnsavedFile.by_ref, :uint, :uint], CXCodeCompleteResults.by_ref
  attach_function :clang_sort_code_completion_results, :clang_sortCodeCompletionResults, [CXCompletionResult.by_ref, :uint], :void
  attach_function :clang_dispose_code_complete_results, :clang_disposeCodeCompleteResults, [CXCodeCompleteResults.by_ref], :void
  attach_function :clang_code_complete_get_num_diagnostics, :clang_codeCompleteGetNumDiagnostics, [CXCodeCompleteResults.by_ref], :uint
  attach_function :clang_code_complete_get_diagnostic, :clang_codeCompleteGetDiagnostic, [CXCodeCompleteResults.by_ref, :uint], :pointer
  attach_function :clang_code_complete_get_contexts, :clang_codeCompleteGetContexts, [CXCodeCompleteResults.by_ref], :ulong_long
  attach_function :clang_code_complete_get_container_kind, :clang_codeCompleteGetContainerKind, [CXCodeCompleteResults.by_ref, :pointer], CXCursorKind
  attach_function :clang_code_complete_get_container_usr, :clang_codeCompleteGetContainerUSR, [CXCodeCompleteResults.by_ref], CXString.by_value
  attach_function :clang_code_complete_get_obj_c_selector, :clang_codeCompleteGetObjCSelector, [CXCodeCompleteResults.by_ref], CXString.by_value
  attach_function :clang_get_clang_version, :clang_getClangVersion, [], CXString.by_value
  attach_function :clang_toggle_crash_recovery, :clang_toggleCrashRecovery, [:uint], :void
  callback :cx_inclusion_visitor, [], :void
  attach_function :clang_get_inclusions, :clang_getInclusions, [:pointer, :pointer, :pointer], :void

  CXEvalResultKind = enum(
    :CXEval_Int, 1,
    :CXEval_Float, 2,
    :CXEval_ObjCStrLiteral, 3,
    :CXEval_StrLiteral, 4,
    :CXEval_CFStr, 5,
    :CXEval_Other, 6,
    :CXEval_UnExposed, 0
  )

  typedef :pointer, :cx_eval_result
  attach_function :clang_cursor_evaluate, :clang_Cursor_Evaluate, [CXCursor.by_value], :pointer
  attach_function :clang_eval_result_get_kind, :clang_EvalResult_getKind, [:pointer], CXEvalResultKind
  attach_function :clang_eval_result_get_as_int, :clang_EvalResult_getAsInt, [:pointer], :int
  attach_function :clang_eval_result_get_as_long_long, :clang_EvalResult_getAsLongLong, [:pointer], :long_long
  attach_function :clang_eval_result_is_unsigned_int, :clang_EvalResult_isUnsignedInt, [:pointer], :uint
  attach_function :clang_eval_result_get_as_unsigned, :clang_EvalResult_getAsUnsigned, [:pointer], :ulong_long
  attach_function :clang_eval_result_get_as_double, :clang_EvalResult_getAsDouble, [:pointer], :double
  attach_function :clang_eval_result_get_as_str, :clang_EvalResult_getAsStr, [:pointer], :string
  attach_function :clang_eval_result_dispose, :clang_EvalResult_dispose, [:pointer], :void
  typedef :pointer, :cx_remapping
  attach_function :clang_get_remappings, :clang_getRemappings, [:string], :pointer
  attach_function :clang_get_remappings_from_file_list, :clang_getRemappingsFromFileList, [:pointer, :uint], :pointer
  attach_function :clang_remap_get_num_files, :clang_remap_getNumFiles, [:pointer], :uint
  attach_function :clang_remap_get_filenames, :clang_remap_getFilenames, [:pointer, :uint, CXString.by_ref, CXString.by_ref], :void
  attach_function :clang_remap_dispose, :clang_remap_dispose, [:pointer], :void

  CXVisitorResult = enum(
    :CXVisit_Break, 0,
    :CXVisit_Continue, 1
  )

  callback :CXCursorAndRangeVisitor_visit_callback, [:pointer, CXCursor.by_value, CXSourceRange.by_value], CXVisitorResult

  class CXCursorAndRangeVisitor < FFI::Struct
    layout :context, :pointer,
           :visit, :CXCursorAndRangeVisitor_visit_callback
  end

  CXResult = enum(
    :CXResult_Success, 0,
    :CXResult_Invalid, 1,
    :CXResult_VisitBreak, 2
  )

  attach_function :clang_find_references_in_file, :clang_findReferencesInFile, [CXCursor.by_value, :pointer, CXCursorAndRangeVisitor.by_value], CXResult
  attach_function :clang_find_includes_in_file, :clang_findIncludesInFile, [:pointer, :pointer, CXCursorAndRangeVisitor.by_value], CXResult
  typedef :pointer, :cx_cursor_and_range_visitor_block
  attach_function :clang_find_references_in_file_with_block, :clang_findReferencesInFileWithBlock, [CXCursor.by_value, :pointer, :pointer], CXResult
  attach_function :clang_find_includes_in_file_with_block, :clang_findIncludesInFileWithBlock, [:pointer, :pointer, :pointer], CXResult
  typedef :pointer, :cx_idx_client_file
  typedef :pointer, :cx_idx_client_entity
  typedef :pointer, :cx_idx_client_container
  typedef :pointer, :cx_idx_client_ast_file

  class CXIdxLoc < FFI::Struct
    layout :ptr_data, [:pointer, 2],
           :int_data, :uint
  end

  class CXIdxIncludedFileInfo < FFI::Struct
    layout :hash_loc, CXIdxLoc,
           :filename, :string,
           :file, :pointer,
           :is_import, :int,
           :is_angled, :int,
           :is_module_import, :int
  end

  class CXIdxImportedASTFileInfo < FFI::Struct
    layout :file, :pointer,
           :module, :pointer,
           :loc, CXIdxLoc,
           :is_implicit, :int
  end

  CXIdxEntityKind = enum(
    :CXIdxEntity_Unexposed, 0,
    :CXIdxEntity_Typedef, 1,
    :CXIdxEntity_Function, 2,
    :CXIdxEntity_Variable, 3,
    :CXIdxEntity_Field, 4,
    :CXIdxEntity_EnumConstant, 5,
    :CXIdxEntity_ObjCClass, 6,
    :CXIdxEntity_ObjCProtocol, 7,
    :CXIdxEntity_ObjCCategory, 8,
    :CXIdxEntity_ObjCInstanceMethod, 9,
    :CXIdxEntity_ObjCClassMethod, 10,
    :CXIdxEntity_ObjCProperty, 11,
    :CXIdxEntity_ObjCIvar, 12,
    :CXIdxEntity_Enum, 13,
    :CXIdxEntity_Struct, 14,
    :CXIdxEntity_Union, 15,
    :CXIdxEntity_CXXClass, 16,
    :CXIdxEntity_CXXNamespace, 17,
    :CXIdxEntity_CXXNamespaceAlias, 18,
    :CXIdxEntity_CXXStaticVariable, 19,
    :CXIdxEntity_CXXStaticMethod, 20,
    :CXIdxEntity_CXXInstanceMethod, 21,
    :CXIdxEntity_CXXConstructor, 22,
    :CXIdxEntity_CXXDestructor, 23,
    :CXIdxEntity_CXXConversionFunction, 24,
    :CXIdxEntity_CXXTypeAlias, 25,
    :CXIdxEntity_CXXInterface, 26,
    :CXIdxEntity_CXXConcept, 27
  )

  CXIdxEntityLanguage = enum(
    :CXIdxEntityLang_None, 0,
    :CXIdxEntityLang_C, 1,
    :CXIdxEntityLang_ObjC, 2,
    :CXIdxEntityLang_CXX, 3,
    :CXIdxEntityLang_Swift, 4
  )

  CXIdxEntityCXXTemplateKind = enum(
    :CXIdxEntity_NonTemplate, 0,
    :CXIdxEntity_Template, 1,
    :CXIdxEntity_TemplatePartialSpecialization, 2,
    :CXIdxEntity_TemplateSpecialization, 3
  )

  CXIdxAttrKind = enum(
    :CXIdxAttr_Unexposed, 0,
    :CXIdxAttr_IBAction, 1,
    :CXIdxAttr_IBOutlet, 2,
    :CXIdxAttr_IBOutletCollection, 3
  )

  class CXIdxAttrInfo < FFI::Struct
    layout :kind, CXIdxAttrKind,
           :cursor, CXCursor,
           :loc, CXIdxLoc
  end

  class CXIdxEntityInfo < FFI::Struct
    layout :kind, CXIdxEntityKind,
           :template_kind, CXIdxEntityCXXTemplateKind,
           :lang, CXIdxEntityLanguage,
           :name, :string,
           :usr, :string,
           :cursor, CXCursor,
           :attributes, :pointer,
           :num_attributes, :uint
  end

  class CXIdxContainerInfo < FFI::Struct
    layout :cursor, CXCursor
  end

  class CXIdxIBOutletCollectionAttrInfo < FFI::Struct
    layout :attr_info, CXIdxAttrInfo.ptr,
           :objc_class, CXIdxEntityInfo.ptr,
           :class_cursor, CXCursor,
           :class_loc, CXIdxLoc
  end

  CXIdxDeclInfoFlags = enum(
    :CXIdxDeclFlag_Skipped, 1
  )

  class CXIdxDeclInfo < FFI::Struct
    layout :entity_info, CXIdxEntityInfo.ptr,
           :cursor, CXCursor,
           :loc, CXIdxLoc,
           :semantic_container, CXIdxContainerInfo.ptr,
           :lexical_container, CXIdxContainerInfo.ptr,
           :is_redeclaration, :int,
           :is_definition, :int,
           :is_container, :int,
           :decl_as_container, CXIdxContainerInfo.ptr,
           :is_implicit, :int,
           :attributes, :pointer,
           :num_attributes, :uint,
           :flags, :uint
  end

  CXIdxObjCContainerKind = enum(
    :CXIdxObjCContainer_ForwardRef, 0,
    :CXIdxObjCContainer_Interface, 1,
    :CXIdxObjCContainer_Implementation, 2
  )

  class CXIdxObjCContainerDeclInfo < FFI::Struct
    layout :decl_info, CXIdxDeclInfo.ptr,
           :kind, CXIdxObjCContainerKind
  end

  class CXIdxBaseClassInfo < FFI::Struct
    layout :base, CXIdxEntityInfo.ptr,
           :cursor, CXCursor,
           :loc, CXIdxLoc
  end

  class CXIdxObjCProtocolRefInfo < FFI::Struct
    layout :protocol, CXIdxEntityInfo.ptr,
           :cursor, CXCursor,
           :loc, CXIdxLoc
  end

  class CXIdxObjCProtocolRefListInfo < FFI::Struct
    layout :protocols, :pointer,
           :num_protocols, :uint
  end

  class CXIdxObjCInterfaceDeclInfo < FFI::Struct
    layout :container_info, CXIdxObjCContainerDeclInfo.ptr,
           :super_info, CXIdxBaseClassInfo.ptr,
           :protocols, CXIdxObjCProtocolRefListInfo.ptr
  end

  class CXIdxObjCCategoryDeclInfo < FFI::Struct
    layout :container_info, CXIdxObjCContainerDeclInfo.ptr,
           :objc_class, CXIdxEntityInfo.ptr,
           :class_cursor, CXCursor,
           :class_loc, CXIdxLoc,
           :protocols, CXIdxObjCProtocolRefListInfo.ptr
  end

  class CXIdxObjCPropertyDeclInfo < FFI::Struct
    layout :decl_info, CXIdxDeclInfo.ptr,
           :getter, CXIdxEntityInfo.ptr,
           :setter, CXIdxEntityInfo.ptr
  end

  class CXIdxCXXClassDeclInfo < FFI::Struct
    layout :decl_info, CXIdxDeclInfo.ptr,
           :bases, :pointer,
           :num_bases, :uint
  end

  CXIdxEntityRefKind = enum(
    :CXIdxEntityRef_Direct, 1,
    :CXIdxEntityRef_Implicit, 2
  )

  CXSymbolRole = enum(
    :CXSymbolRole_None, 0,
    :CXSymbolRole_Declaration, 1,
    :CXSymbolRole_Definition, 2,
    :CXSymbolRole_Reference, 4,
    :CXSymbolRole_Read, 8,
    :CXSymbolRole_Write, 16,
    :CXSymbolRole_Call, 32,
    :CXSymbolRole_Dynamic, 64,
    :CXSymbolRole_AddressOf, 128,
    :CXSymbolRole_Implicit, 256
  )

  class CXIdxEntityRefInfo < FFI::Struct
    layout :kind, CXIdxEntityRefKind,
           :cursor, CXCursor,
           :loc, CXIdxLoc,
           :referenced_entity, CXIdxEntityInfo.ptr,
           :parent_entity, CXIdxEntityInfo.ptr,
           :container, CXIdxContainerInfo.ptr,
           :role, CXSymbolRole
  end

  callback :IndexerCallbacks_abortQuery_callback, [:pointer, :pointer], :int
  callback :IndexerCallbacks_diagnostic_callback, [:pointer, :pointer, :pointer], :void
  callback :IndexerCallbacks_enteredMainFile_callback, [:pointer, :pointer, :pointer], :pointer
  callback :IndexerCallbacks_ppIncludedFile_callback, [:pointer, :pointer], :pointer
  callback :IndexerCallbacks_importedASTFile_callback, [:pointer, :pointer], :pointer
  callback :IndexerCallbacks_startedTranslationUnit_callback, [:pointer, :pointer], :pointer
  callback :IndexerCallbacks_indexDeclaration_callback, [:pointer, :pointer], :void
  callback :IndexerCallbacks_indexEntityReference_callback, [:pointer, :pointer], :void

  class IndexerCallbacks < FFI::Struct
    layout :abort_query, :IndexerCallbacks_abortQuery_callback,
           :diagnostic, :IndexerCallbacks_diagnostic_callback,
           :entered_main_file, :IndexerCallbacks_enteredMainFile_callback,
           :pp_included_file, :IndexerCallbacks_ppIncludedFile_callback,
           :imported_ast_file, :IndexerCallbacks_importedASTFile_callback,
           :started_translation_unit, :IndexerCallbacks_startedTranslationUnit_callback,
           :index_declaration, :IndexerCallbacks_indexDeclaration_callback,
           :index_entity_reference, :IndexerCallbacks_indexEntityReference_callback
  end

  attach_function :clang_index_is_entity_obj_c_container_kind, :clang_index_isEntityObjCContainerKind, [CXIdxEntityKind], :int
  attach_function :clang_index_get_obj_c_container_decl_info, :clang_index_getObjCContainerDeclInfo, [CXIdxDeclInfo.by_ref], CXIdxObjCContainerDeclInfo.by_ref
  attach_function :clang_index_get_obj_c_interface_decl_info, :clang_index_getObjCInterfaceDeclInfo, [CXIdxDeclInfo.by_ref], CXIdxObjCInterfaceDeclInfo.by_ref
  attach_function :clang_index_get_obj_c_category_decl_info, :clang_index_getObjCCategoryDeclInfo, [CXIdxDeclInfo.by_ref], CXIdxObjCCategoryDeclInfo.by_ref
  attach_function :clang_index_get_obj_c_protocol_ref_list_info, :clang_index_getObjCProtocolRefListInfo, [CXIdxDeclInfo.by_ref], CXIdxObjCProtocolRefListInfo.by_ref
  attach_function :clang_index_get_obj_c_property_decl_info, :clang_index_getObjCPropertyDeclInfo, [CXIdxDeclInfo.by_ref], CXIdxObjCPropertyDeclInfo.by_ref
  attach_function :clang_index_get_ib_outlet_collection_attr_info, :clang_index_getIBOutletCollectionAttrInfo, [CXIdxAttrInfo.by_ref], CXIdxIBOutletCollectionAttrInfo.by_ref
  attach_function :clang_index_get_cxx_class_decl_info, :clang_index_getCXXClassDeclInfo, [CXIdxDeclInfo.by_ref], CXIdxCXXClassDeclInfo.by_ref
  attach_function :clang_index_get_client_container, :clang_index_getClientContainer, [CXIdxContainerInfo.by_ref], :pointer
  attach_function :clang_index_set_client_container, :clang_index_setClientContainer, [CXIdxContainerInfo.by_ref, :pointer], :void
  attach_function :clang_index_get_client_entity, :clang_index_getClientEntity, [CXIdxEntityInfo.by_ref], :pointer
  attach_function :clang_index_set_client_entity, :clang_index_setClientEntity, [CXIdxEntityInfo.by_ref, :pointer], :void
  typedef :pointer, :cx_index_action
  attach_function :clang_index_action_create, :clang_IndexAction_create, [:pointer], :pointer
  attach_function :clang_index_action_dispose, :clang_IndexAction_dispose, [:pointer], :void

  CXIndexOptFlags = enum(
    :CXIndexOpt_None, 0,
    :CXIndexOpt_SuppressRedundantRefs, 1,
    :CXIndexOpt_IndexFunctionLocalSymbols, 2,
    :CXIndexOpt_IndexImplicitTemplateInstantiations, 4,
    :CXIndexOpt_SuppressWarnings, 8,
    :CXIndexOpt_SkipParsedBodiesInSession, 16
  )

  attach_function :clang_index_source_file, :clang_indexSourceFile, [:pointer, :pointer, IndexerCallbacks.by_ref, :uint, :uint, :string, :pointer, :int, CXUnsavedFile.by_ref, :uint, :pointer, :uint], :int
  attach_function :clang_index_source_file_full_argv, :clang_indexSourceFileFullArgv, [:pointer, :pointer, IndexerCallbacks.by_ref, :uint, :uint, :string, :pointer, :int, CXUnsavedFile.by_ref, :uint, :pointer, :uint], :int
  attach_function :clang_index_translation_unit, :clang_indexTranslationUnit, [:pointer, :pointer, IndexerCallbacks.by_ref, :uint, :uint, :pointer], :int
  attach_function :clang_index_loc_get_file_location, :clang_indexLoc_getFileLocation, [CXIdxLoc.by_value, :pointer, :pointer, :pointer, :pointer, :pointer], :void
  attach_function :clang_index_loc_get_cx_source_location, :clang_indexLoc_getCXSourceLocation, [CXIdxLoc.by_value], CXSourceLocation.by_value
  callback :cx_field_visitor, [], CXVisitorResult
  attach_function :clang_type_visit_fields, :clang_Type_visitFields, [CXType.by_value, :pointer, :pointer], :uint

  CXBinaryOperatorKind = enum(
    :CXBinaryOperator_Invalid, 0,
    :CXBinaryOperator_PtrMemD, 1,
    :CXBinaryOperator_PtrMemI, 2,
    :CXBinaryOperator_Mul, 3,
    :CXBinaryOperator_Div, 4,
    :CXBinaryOperator_Rem, 5,
    :CXBinaryOperator_Add, 6,
    :CXBinaryOperator_Sub, 7,
    :CXBinaryOperator_Shl, 8,
    :CXBinaryOperator_Shr, 9,
    :CXBinaryOperator_Cmp, 10,
    :CXBinaryOperator_LT, 11,
    :CXBinaryOperator_GT, 12,
    :CXBinaryOperator_LE, 13,
    :CXBinaryOperator_GE, 14,
    :CXBinaryOperator_EQ, 15,
    :CXBinaryOperator_NE, 16,
    :CXBinaryOperator_And, 17,
    :CXBinaryOperator_Xor, 18,
    :CXBinaryOperator_Or, 19,
    :CXBinaryOperator_LAnd, 20,
    :CXBinaryOperator_LOr, 21,
    :CXBinaryOperator_Assign, 22,
    :CXBinaryOperator_MulAssign, 23,
    :CXBinaryOperator_DivAssign, 24,
    :CXBinaryOperator_RemAssign, 25,
    :CXBinaryOperator_AddAssign, 26,
    :CXBinaryOperator_SubAssign, 27,
    :CXBinaryOperator_ShlAssign, 28,
    :CXBinaryOperator_ShrAssign, 29,
    :CXBinaryOperator_AndAssign, 30,
    :CXBinaryOperator_XorAssign, 31,
    :CXBinaryOperator_OrAssign, 32,
    :CXBinaryOperator_Comma, 33
  )

  attach_function :clang_get_binary_operator_kind_spelling, :clang_getBinaryOperatorKindSpelling, [CXBinaryOperatorKind], CXString.by_value
  attach_function :clang_get_cursor_binary_operator_kind, :clang_getCursorBinaryOperatorKind, [CXCursor.by_value], CXBinaryOperatorKind

  CXUnaryOperatorKind = enum(
    :CXUnaryOperator_Invalid, 0,
    :CXUnaryOperator_PostInc, 1,
    :CXUnaryOperator_PostDec, 2,
    :CXUnaryOperator_PreInc, 3,
    :CXUnaryOperator_PreDec, 4,
    :CXUnaryOperator_AddrOf, 5,
    :CXUnaryOperator_Deref, 6,
    :CXUnaryOperator_Plus, 7,
    :CXUnaryOperator_Minus, 8,
    :CXUnaryOperator_Not, 9,
    :CXUnaryOperator_LNot, 10,
    :CXUnaryOperator_Real, 11,
    :CXUnaryOperator_Imag, 12,
    :CXUnaryOperator_Extension, 13,
    :CXUnaryOperator_Coawait, 14
  )

  attach_function :clang_get_unary_operator_kind_spelling, :clang_getUnaryOperatorKindSpelling, [CXUnaryOperatorKind], CXString.by_value
  attach_function :clang_get_cursor_unary_operator_kind, :clang_getCursorUnaryOperatorKind, [CXCursor.by_value], CXUnaryOperatorKind
end
