// Generated by ruby-bindgen (1.0.0)

#include <guards/base.hpp>
#include "base-rb.hpp"

using namespace Rice;

void Init_Base()
{
  Module rb_mGuardFixtures = define_module("GuardFixtures");

  Rice::Data_Type<GuardFixtures::Base> rb_cGuardFixturesBase = define_class_under<GuardFixtures::Base>(rb_mGuardFixtures, "Base")
    .define_constructor(Constructor<GuardFixtures::Base>());
}
