// Generated by ruby-bindgen (1.0.0)

#include <guards/cudaarithm.hpp>
#include "cudaarithm-rb.hpp"

using namespace Rice;

void Init_Cudaarithm()
{
  Module rb_mGuardFixtures = define_module("GuardFixtures");

  Rice::Data_Type<GuardFixtures::Cudaarithm> rb_cGuardFixturesCudaarithm = define_class_under<GuardFixtures::Cudaarithm>(rb_mGuardFixtures, "Cudaarithm")
    .define_constructor(Constructor<GuardFixtures::Cudaarithm>());
}
