// Generated by ruby-bindgen (1.0.0)

#include <guards/cudaimgproc.hpp>
#include "cudaimgproc-rb.hpp"

using namespace Rice;

void Init_Cudaimgproc()
{
  Module rb_mGuardFixtures = define_module("GuardFixtures");

  Rice::Data_Type<GuardFixtures::Cudaimgproc> rb_cGuardFixturesCudaimgproc = define_class_under<GuardFixtures::Cudaimgproc>(rb_mGuardFixtures, "Cudaimgproc")
    .define_constructor(Constructor<GuardFixtures::Cudaimgproc>());
}
