# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

FFI::DynamicLibrary::SEARCH_PATH = ["c:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin"]

module CXString
  extend FFI::Library

  def self.library_names
    ["clang"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  
  class CXString < FFI::Struct
    layout :data, :pointer,
      :private_flags, :uint
  end
  
  
  class CXStringSet < FFI::Struct
    layout :Strings, CXString.ptr,
      :Count, :uint
  end
  
  attach_function :clang_getCString, :clang_getCString, [CXString.by_value], :string
  attach_function :clang_disposeString, :clang_disposeString, [CXString.by_value], :void
  attach_function :clang_disposeStringSet, :clang_disposeStringSet, [CXStringSet.by_ref], :void
end
