// Generated by ruby-bindgen (1.0.0)

template<typename T>
inline Rice::Data_Type<Tests::Array<T>> Array_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Array<T>>(parent, name)
    .define_constructor(Constructor<Tests::Array<T>, const std::vector<typename Tests::Array<T>::HT> &>(),
      Arg("values"));
}
