// Generated by ruby-bindgen (1.0.0)

#include <class_template_typedef_qualification.hpp>
#include "class_template_typedef_qualification-rb.hpp"

using namespace Rice;

#include "class_template_typedef_qualification-rb.ipp"

void Init_ClassTemplateTypedefQualification()
{
  Module rb_mTests = define_module("Tests");
}
