// Generated by ruby-bindgen (1.0.0)

template<typename Net>
inline Rice::Data_Type<Tests::PortCfg<Net>> PortCfg_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::PortCfg<Net>>(parent, name);
}

template<typename Net>
inline Rice::Data_Type<Tests::Params<Net>> Params_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Params<Net>>(parent, name)
    .template define_method<Tests::Params<Net> &(Tests::Params<Net>::*)(const typename Tests::PortCfg<Net>::In &)>("cfg_input_layers", &Tests::Params<Net>::cfgInputLayers,
      Arg("layer_names"))
    .template define_method<Tests::Params<Net> &(Tests::Params<Net>::*)(const typename Tests::PortCfg<Net>::Out &)>("cfg_output_layers", &Tests::Params<Net>::cfgOutputLayers,
      Arg("layer_name"));
}

template<typename T>
inline Rice::Data_Type<Tests::Array<T>> Array_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Array<T>>(parent, name)
    .define_constructor(Constructor<Tests::Array<T>>())
    .define_constructor(Constructor<Tests::Array<T>, const std::vector<typename Tests::Array<T>::HT> &>(),
      Arg("values"));
}
