// Generated by ruby-bindgen (1.0.0)

#include <dependent_nested_types.hpp>
#include "dependent_nested_types-rb.hpp"

using namespace Rice;

#include "dependent_nested_types-rb.ipp"

void Init_DependentNestedTypes()
{
  Module rb_mTests = define_module("Tests");
}
