// Generated by ruby-bindgen (1.0.0)

#include <dependent_template_parameter_fidelity.hpp>
#include "dependent_template_parameter_fidelity-rb.hpp"

using namespace Rice;

#include "dependent_template_parameter_fidelity-rb.ipp"

void Init_DependentTemplateParameterFidelity()
{
  Module rb_mSupport = define_module("Support");

  Rice::Data_Type<Support::Net> rb_cSupportNet = define_class_under<Support::Net>(rb_mSupport, "Net")
    .define_constructor(Constructor<Support::Net>());

  Module rb_mTests = define_module("Tests");
}
