// Generated by ruby-bindgen (1.0.0)

template<typename T>
inline Rice::Data_Type<Outer::UsesSkippedType<T>> UsesSkippedType_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Outer::UsesSkippedType<T>>(parent, name)
    .define_constructor(Constructor<Outer::UsesSkippedType<T>>())
    .template define_method<void(Outer::UsesSkippedType<T>::*)()>("normal_method", &Outer::UsesSkippedType<T>::normalMethod)
    .define_constant("NORMAL_CONST", (int)Outer::UsesSkippedType<T>::NORMAL_CONST);
}

template<typename T>
inline Rice::Data_Type<Outer::Wrapper<T>> Wrapper_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Outer::Wrapper<T>>(parent, name)
    .define_constructor(Constructor<Outer::Wrapper<T>>())
    .template define_method<void(Outer::Wrapper<T>::*)(T*)>("wrap", &Outer::Wrapper<T>::wrap,
      std::conditional_t<std::is_fundamental_v<T>, ArgBuffer, Arg>("obj"));
}

template<typename T>
inline Rice::Data_Type<Outer::DeprecatedTemplate<T>> DeprecatedTemplate_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Outer::DeprecatedTemplate<T>>(parent, name);
}

template<typename T, int N>
inline Rice::Data_Type<Outer::Vec<T, N>> Vec_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Outer::Vec<T, N>>(parent, name)
    .define_attr("data", &Outer::Vec<T, N>::data, Rice::AttrAccess::Read);
}

template<typename T>
inline Rice::Data_Type<Outer::DataType<T>> DataType_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Outer::DataType<T>>(parent, name)
    .define_constructor(Constructor<Outer::DataType<T>>())
    .template define_method<void(Outer::DataType<T>::*)()>("info", &Outer::DataType<T>::info);
}
