// Generated by ruby-bindgen (1.0.0)

#include <implicit_default_constructor.hpp>
#include "implicit_default_constructor-rb.hpp"

using namespace Rice;

void Init_ImplicitDefaultConstructor()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::NonDefaultConstructible> rb_cTestsNonDefaultConstructible = define_class_under<Tests::NonDefaultConstructible>(rb_mTests, "NonDefaultConstructible");
}
