// Generated by ruby-bindgen (1.0.0)

#include <macro_template_parameters.hpp>
#include "macro_template_parameters-rb.hpp"

using namespace Rice;

#include "macro_template_parameters-rb.ipp"

void Init_MacroTemplateParameters()
{
  Module rb_mTests = define_module("Tests");

  Module rb_mTestsInternal = define_module_under(rb_mTests, "Internal");
}
