// Generated by ruby-bindgen (1.0.0)

template<typename T>
inline Rice::Data_Type<Tests::Internal::CheckMember_fmt<T>> CheckMember_fmt_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Internal::CheckMember_fmt<T>>(parent, name)
    .define_constant("Value", (int)Tests::Internal::CheckMember_fmt<T>::value);
}

template<typename T>
inline Rice::Data_Type<Tests::Internal::CheckMember_type<T>> CheckMember_type_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Internal::CheckMember_type<T>>(parent, name)
    .define_constant("Value", (int)Tests::Internal::CheckMember_type<T>::value);
}

template<typename T, bool available>
inline Rice::Data_Type<Tests::SafeType<T, available>> SafeType_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::SafeType<T, available>>(parent, name)
    .define_constant("Value", (int)Tests::SafeType<T, available>::value);
}

template<typename T, bool available>
inline Rice::Data_Type<Tests::SafeFmt<T, available>> SafeFmt_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::SafeFmt<T, available>>(parent, name)
    .define_constant("Value", (int)Tests::SafeFmt<T, available>::value);
}
