// Generated by ruby-bindgen (1.0.0)

#include <nested_class_templates.hpp>
#include "nested_class_templates-rb.hpp"

using namespace Rice;

#include "nested_class_templates-rb.ipp"

void Init_NestedClassTemplates()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::Allocator<int>> rb_cAllocatori = Allocator_instantiate<int>(rb_mTests, "Allocatori");
}
