// Generated by ruby-bindgen (1.0.0)

template<typename T>
inline Rice::Data_Type<Tests::Allocator<T>> Allocator_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Allocator<T>>(parent, name);
}
