// Generated by ruby-bindgen (1.0.0)

#include <non_system_incomplete_refs.hpp>
#include "non_system_incomplete_refs-rb.hpp"

using namespace Rice;

void Init_NonSystemIncompleteRefs()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::NonSystemIncompleteRefs> rb_cTestsNonSystemIncompleteRefs = define_class_under<Tests::NonSystemIncompleteRefs>(rb_mTests, "NonSystemIncompleteRefs")
    .define_constructor(Constructor<Tests::NonSystemIncompleteRefs>())
    .define_method<int &(Tests::NonSystemIncompleteRefs::*)()>("value_ref", &Tests::NonSystemIncompleteRefs::valueRef)
    .define_method<const int &(Tests::NonSystemIncompleteRefs::*)() const>("value_const_ref", &Tests::NonSystemIncompleteRefs::valueConstRef)
    .define_attr("value", &Tests::NonSystemIncompleteRefs::value);
}
