// Generated by ruby-bindgen (1.0.0)

#include <partial_namespace_template_args.hpp>
#include "partial_namespace_template_args-rb.hpp"

using namespace Rice;

#include "partial_namespace_template_args-rb.ipp"

void Init_PartialNamespaceTemplateArgs()
{
  Module rb_mCv = define_module("Cv");

  Module rb_mCvGapi = define_module_under(rb_mCv, "Gapi");

  Module rb_mCvGapiOak = define_module_under(rb_mCvGapi, "Oak");

  Rice::Data_Type<cv::gapi::oak::ColorCameraParams> rb_cCvGapiOakColorCameraParams = define_class_under<cv::gapi::oak::ColorCameraParams>(rb_mCvGapiOak, "ColorCameraParams")
    .define_constructor(Constructor<cv::gapi::oak::ColorCameraParams>());

  Rice::Data_Type<cv::gapi::oak::EncoderConfig> rb_cCvGapiOakEncoderConfig = define_class_under<cv::gapi::oak::EncoderConfig>(rb_mCvGapiOak, "EncoderConfig")
    .define_constructor(Constructor<cv::gapi::oak::EncoderConfig>());

  Module rb_mCvDetail = define_module_under(rb_mCv, "Detail");

  Rice::Data_Type<cv::detail::CompileArgTag<cv::gapi::oak::ColorCameraParams>> rb_cCvDetailCompileArgTagGapiOakColorCameraParams = define_class_under<cv::detail::CompileArgTag<cv::gapi::oak::ColorCameraParams>>(rb_mCvDetail, "ColorCameraParams")
    .define_constructor(Constructor<cv::detail::CompileArgTag<cv::gapi::oak::ColorCameraParams>>())
    .define_singleton_function<const char *(*)()>("tag", &cv::detail::CompileArgTag<cv::gapi::oak::ColorCameraParams>::tag);

  Rice::Data_Type<cv::detail::CompileArgTag<cv::gapi::oak::EncoderConfig>> rb_cCvDetailCompileArgTagGapiOakEncoderConfig = define_class_under<cv::detail::CompileArgTag<cv::gapi::oak::EncoderConfig>>(rb_mCvDetail, "EncoderConfig")
    .define_constructor(Constructor<cv::detail::CompileArgTag<cv::gapi::oak::EncoderConfig>>())
    .define_singleton_function<const char *(*)()>("tag", &cv::detail::CompileArgTag<cv::gapi::oak::EncoderConfig>::tag);
}
