// Generated by ruby-bindgen (1.0.0)

template<typename T>
inline Rice::Data_Type<cv::detail::CompileArgTag<T>> CompileArgTag_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<cv::detail::CompileArgTag<T>>(parent, name)
    .template define_singleton_function<const char *(*)()>("tag", &cv::detail::CompileArgTag<T>::tag);
}
