// Generated by ruby-bindgen (1.0.0)

#include <reference_fields.hpp>
#include "reference_fields-rb.hpp"

using namespace Rice;

void Init_ReferenceFields()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::ReferenceField> rb_cTestsReferenceField = define_class_under<Tests::ReferenceField>(rb_mTests, "ReferenceField")
    .define_constructor(Constructor<Tests::ReferenceField, int &>(),
      Arg("input"))
    .define_attr("value", &Tests::ReferenceField::value);
}
