// Generated by ruby-bindgen (1.0.0)

#include <rice_unsupported_types.hpp>
#include "rice_unsupported_types-rb.hpp"

using namespace Rice;

void Init_RiceUnsupportedTypes()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::UnsupportedRiceTypes> rb_cTestsUnsupportedRiceTypes = define_class_under<Tests::UnsupportedRiceTypes>(rb_mTests, "UnsupportedRiceTypes");

  Rice::Data_Type<Tests::UnsupportedRiceTypes::Priv> rb_cTestsUnsupportedRiceTypesPriv = define_class_under<Tests::UnsupportedRiceTypes::Priv>(rb_cTestsUnsupportedRiceTypes, "Priv");
  rb_cTestsUnsupportedRiceTypes
    .define_constructor(Constructor<Tests::UnsupportedRiceTypes>())
    .define_constructor(Constructor<Tests::UnsupportedRiceTypes, const Tests::UnsupportedRiceTypes::Callback &>(),
      Arg("callback"))
    .define_method<void(Tests::UnsupportedRiceTypes::*)(const Tests::UnsupportedRiceTypes::Callback &)>("set_callback", &Tests::UnsupportedRiceTypes::setCallback,
      Arg("callback"))
    .define_singleton_function<void(*)(const Tests::UnsupportedRiceTypes::NestedCallback &)>("install", &Tests::UnsupportedRiceTypes::install,
      Arg("callback"))
    .define_singleton_function<void(*)(std::function<void ()> &&)>("notify", &Tests::UnsupportedRiceTypes::notify,
      Arg("callback"))
    .define_method<Tests::UnsupportedRiceTypes::Priv &(Tests::UnsupportedRiceTypes::*)()>("priv", &Tests::UnsupportedRiceTypes::priv)
    .define_method<const Tests::UnsupportedRiceTypes::Priv &(Tests::UnsupportedRiceTypes::*)() const>("priv", &Tests::UnsupportedRiceTypes::priv)
    .define_attr("callback", &Tests::UnsupportedRiceTypes::callback)
    .define_attr("nested_callback", &Tests::UnsupportedRiceTypes::nestedCallback)
    .define_attr("value", &Tests::UnsupportedRiceTypes::value);
}
