// Generated by ruby-bindgen (1.0.0)

#include <system_incomplete_refs.hpp>
#include "system_incomplete_refs-rb.hpp"

using namespace Rice;

void Init_SystemIncompleteRefs()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::SystemIncompleteRefs> rb_cTestsSystemIncompleteRefs = define_class_under<Tests::SystemIncompleteRefs>(rb_mTests, "SystemIncompleteRefs")
    .define_constructor(Constructor<Tests::SystemIncompleteRefs>())
    .define_method<int &(Tests::SystemIncompleteRefs::*)()>("value_ref", &Tests::SystemIncompleteRefs::valueRef)
    .define_method<const int &(Tests::SystemIncompleteRefs::*)() const>("value_const_ref", &Tests::SystemIncompleteRefs::valueConstRef)
    .define_attr("value", &Tests::SystemIncompleteRefs::value);
}
