// Generated by ruby-bindgen (1.0.0)

template<typename T>
inline Rice::Data_Type<Tests::Array<T>> Array_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Array<T>>(parent, name);
}

template<typename T>
inline Rice::Data_Type<Tests::detail::get_in<T>> get_in_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::detail::get_in<T>>(parent, name)
    .template define_singleton_function<T(*)(Tests::Context &, int)>("get", &Tests::detail::get_in<T>::get,
      Arg("ctx"), Arg("idx"));
}

template<typename Impl, typename K>
inline Rice::Data_Type<Tests::KernelImpl<Impl, K>> KernelImpl_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::KernelImpl<Impl, K>>(parent, name)
    .template define_singleton_function<int(*)()>("backend", &Tests::KernelImpl<Impl, K>::backend)
    .template define_singleton_function<int(*)()>("kernel", &Tests::KernelImpl<Impl, K>::kernel);
}
