// Generated by ruby-bindgen (1.0.0)

#include <template_defaults.hpp>
#include "template_defaults-rb.hpp"

using namespace Rice;

#include "template_defaults-rb.ipp"

void Init_TemplateDefaults()
{
  Rice::Data_Type<Matrix<int, 2>> rb_cMatrix2i = Matrix_instantiate<int, 2, 1>(Rice::Module(rb_cObject), "Matrix2i");

  Rice::Data_Type<Matrix<double, 3>> rb_cMatrix3d = Matrix_instantiate<double, 3, 1>(Rice::Module(rb_cObject), "Matrix3d");

  Rice::Data_Type<Matrix<float, 4>> rb_cMatrix4f = Matrix_instantiate<float, 4, 1>(Rice::Module(rb_cObject), "Matrix4f");

  Rice::Data_Type<Matrix<int, 2, 2>> rb_cMatrix22i = Matrix_instantiate<int, 2, 2>(Rice::Module(rb_cObject), "Matrix22i");

  Rice::Data_Type<Matrix<double, 3, 3>> rb_cMatrix33d = Matrix_instantiate<double, 3, 3>(Rice::Module(rb_cObject), "Matrix33d");

  Rice::Data_Type<MultiDefault<int>> rb_cMultiDefaultInt = MultiDefault_instantiate<int, 10, 20, 30>(Rice::Module(rb_cObject), "MultiDefaultInt");

  Rice::Data_Type<MultiDefault<int, 5>> rb_cMultiDefaultInt5 = MultiDefault_instantiate<int, 5, 20, 30>(Rice::Module(rb_cObject), "MultiDefaultInt5");

  Rice::Data_Type<MultiDefault<int, 5, 15>> rb_cMultiDefaultInt515 = MultiDefault_instantiate<int, 5, 15, 30>(Rice::Module(rb_cObject), "MultiDefaultInt515");

  Rice::Data_Type<MultiDefault<int, 5, 15, 25>> rb_cMultiDefaultInt51525 = MultiDefault_instantiate<int, 5, 15, 25>(Rice::Module(rb_cObject), "MultiDefaultInt51525");

  Rice::Data_Type<TypeDefault<double>> rb_cTypeDefaultDouble = TypeDefault_instantiate<double, int>(Rice::Module(rb_cObject), "TypeDefaultDouble");

  Rice::Data_Type<TypeDefault<double, float>> rb_cTypeDefaultDF = TypeDefault_instantiate<double, float>(Rice::Module(rb_cObject), "TypeDefaultDF");

  Module rb_mQualifiedDefaults = define_module("QualifiedDefaults");

  Enum<QualifiedDefaults::Counts> rb_cQualifiedDefaultsCounts = define_enum_under<QualifiedDefaults::Counts>("Counts", rb_mQualifiedDefaults)
    .define_value("DefaultCount", QualifiedDefaults::Counts::DefaultCount);

  Rice::Data_Type<QualifiedDefaults::Tag> rb_cQualifiedDefaultsTag = define_class_under<QualifiedDefaults::Tag>(rb_mQualifiedDefaults, "Tag")
    .define_constructor(Constructor<QualifiedDefaults::Tag>())
    .define_attr("value", &QualifiedDefaults::Tag::value);

  Rice::Data_Type<QualifiedDefaults::QualifiedTypeDefault<int>> rb_cQualifiedTypeDefaultInt = QualifiedTypeDefault_instantiate<int, QualifiedDefaults::Tag>(Rice::Module(rb_cObject), "QualifiedTypeDefaultInt");

  Rice::Data_Type<QualifiedDefaults::QualifiedNestedDefault<int>> rb_cQualifiedNestedDefaultInt = QualifiedNestedDefault_instantiate<int, QualifiedDefaults::Box<QualifiedDefaults::Tag>>(Rice::Module(rb_cObject), "QualifiedNestedDefaultInt");

  Rice::Data_Type<QualifiedDefaults::QualifiedValueDefault<int>> rb_cQualifiedValueDefaultInt = QualifiedValueDefault_instantiate<int, QualifiedDefaults::DefaultCount>(Rice::Module(rb_cObject), "QualifiedValueDefaultInt");

  Module rb_mDependentDefaults = define_module("DependentDefaults");

  Rice::Data_Type<DependentDefaults::DependentTypeDefault<int>> rb_cDependentTypeDefaultInt = DependentTypeDefault_instantiate<int, DependentDefaults::Base<int>>(Rice::Module(rb_cObject), "DependentTypeDefaultInt");

  Module rb_mTemplateTemplateDefaults = define_module("TemplateTemplateDefaults");

  Rice::Data_Type<TemplateTemplateDefaults::Holder<int>> rb_cHolderInt = Holder_instantiate<int, TemplateTemplateDefaults::Box>(Rice::Module(rb_cObject), "HolderInt");

  Rice::Data_Type<TemplateTemplateDefaults::HolderWithInnerDefault<float>> rb_cHolderWithInnerDefaultFloat = HolderWithInnerDefault_instantiate<float, TemplateTemplateDefaults::BoxWithInnerDefault>(Rice::Module(rb_cObject), "HolderWithInnerDefaultFloat");

  Rice::Data_Type<FunctionTypeDefault<void (*)(int, int)>> rb_cFunctionTypeDefaultFn = FunctionTypeDefault_instantiate<void (*)(int, int), int>(Rice::Module(rb_cObject), "FunctionTypeDefaultFn");

  Rice::Data_Type<ExprValue<1 + 2>> rb_cExprValueSum = ExprValue_instantiate<1 + 2>(Rice::Module(rb_cObject), "ExprValueSum");
}
