// Generated by ruby-bindgen (1.0.0)

template<typename Signature>
inline Rice::Data_Type<Tests::FunctionBase<Signature>> FunctionBase_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::FunctionBase<Signature>>(parent, name)
    .define_constructor(Constructor<Tests::FunctionBase<Signature>>());
}

template<typename T>
inline Rice::Data_Type<Tests::Traits<T>> Traits_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Traits<T>>(parent, name);
}

template<typename T>
inline Rice::Data_Type<Tests::DependentBase<T>> DependentBase_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::DependentBase<T>>(parent, name)
    .define_constructor(Constructor<Tests::DependentBase<T>>());
}

template<typename T>
inline Rice::Data_Type<Tests::DependentDerived<T>> DependentDerived_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::DependentDerived<T>, Tests::DependentBase<typename Tests::Traits<T>::type>>(parent, name)
    .define_constructor(Constructor<Tests::DependentDerived<T>>());
}

template<typename Signature>
inline Rice::Data_Type<Tests::FunctionDerived<Signature>> FunctionDerived_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::FunctionDerived<Signature>, Tests::FunctionBase<Signature>>(parent, name)
    .define_constructor(Constructor<Tests::FunctionDerived<Signature>>());
}

template<typename Signature>
inline Rice::Data_Type<Tests::CallbackBase<Signature>> CallbackBase_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::CallbackBase<Signature>>(parent, name)
    .define_constructor(Constructor<Tests::CallbackBase<Signature>>());
}

template<typename Result, typename Left, typename Right>
inline Rice::Data_Type<Tests::CallbackDerived<Result, Left, Right>> CallbackDerived_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::CallbackDerived<Result, Left, Right>, Tests::CallbackBase<Result (*)(Left, Right)>>(parent, name)
    .define_constructor(Constructor<Tests::CallbackDerived<Result, Left, Right>>());
}

template<typename T>
inline Rice::Data_Type<Tests::BasePtr<T>> BasePtr_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::BasePtr<T>>(parent, name)
    .define_attr("data", &Tests::BasePtr<T>::data)
    .define_constructor(Constructor<Tests::BasePtr<T>>())
    .define_constructor(Constructor<Tests::BasePtr<T>, T *>(),
      std::conditional_t<std::is_fundamental_v<T>, ArgBuffer, Arg>("data_"));
}

template<typename T>
inline Rice::Data_Type<Tests::DerivedPtr<T>> DerivedPtr_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::DerivedPtr<T>, Tests::BasePtr<T>>(parent, name)
    .define_attr("step", &Tests::DerivedPtr<T>::step)
    .define_constructor(Constructor<Tests::DerivedPtr<T>>())
    .define_constructor(Constructor<Tests::DerivedPtr<T>, T *, int>(),
      std::conditional_t<std::is_fundamental_v<T>, ArgBuffer, Arg>("data_"), Arg("step_"));
}

template<typename P>
inline Rice::Data_Type<Tests::WarperBase<P>> WarperBase_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::WarperBase<P>>(parent, name)
    .define_attr("projector", &Tests::WarperBase<P>::projector)
    .template define_method<void(Tests::WarperBase<P>::*)(const P &)>("set_projector", &Tests::WarperBase<P>::setProjector,
      Arg("p"));
}

template<typename _Tp, int m, int n>
inline Rice::Data_Type<Tests::Matx<_Tp, m, n>> Matx_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Matx<_Tp, m, n>>(parent, name)
    .define_constant("Rows", Tests::Matx<_Tp, m, n>::rows)
    .define_constant("Cols", Tests::Matx<_Tp, m, n>::cols)
    .define_attr("val", &Tests::Matx<_Tp, m, n>::val, Rice::AttrAccess::Read)
    .define_constructor(Constructor<Tests::Matx<_Tp, m, n>>())
    .template define_method<_Tp(Tests::Matx<_Tp, m, n>::*)(const Tests::Matx<_Tp, m, n> &) const>("dot", &Tests::Matx<_Tp, m, n>::dot,
      Arg("other"));
}

template<typename _Tp, int cn>
inline Rice::Data_Type<Tests::Vec<_Tp, cn>> Vec_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Vec<_Tp, cn>, Tests::Matx<_Tp, cn, 1>>(parent, name)
    .define_constant("Channels", Tests::Vec<_Tp, cn>::channels)
    .define_constructor(Constructor<Tests::Vec<_Tp, cn>>())
    .template define_method<_Tp(Tests::Vec<_Tp, cn>::*)(const Tests::Vec<_Tp, cn> &) const>("cross", &Tests::Vec<_Tp, cn>::cross,
      Arg("other"));
}

template<typename _Tp>
inline Rice::Data_Type<Tests::Mat_<_Tp>> Mat__instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Mat_<_Tp>, Tests::Mat>(parent, name)
    .define_constructor(Constructor<Tests::Mat_<_Tp>>())
    .define_constructor(Constructor<Tests::Mat_<_Tp>, int, int>(),
      Arg("rows_"), Arg("cols_"))
    .template define_method<_Tp &(Tests::Mat_<_Tp>::*)(int, int)>("at", &Tests::Mat_<_Tp>::at,
      Arg("row"), Arg("col"));
}

template<typename T>
inline Rice::Data_Type<Support::ForeignBase<T>> ForeignBase_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Support::ForeignBase<T>>(parent, name)
    .define_attr("value", &Support::ForeignBase<T>::value)
    .define_constructor(Constructor<Support::ForeignBase<T>>())
    .define_constructor(Constructor<Support::ForeignBase<T>, T>(),
      Arg("value_"));
}

template<typename T>
inline Rice::Data_Type<Tests::ForeignDerived<T>> ForeignDerived_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::ForeignDerived<T>, Support::ForeignBase<T>>(parent, name)
    .define_constructor(Constructor<Tests::ForeignDerived<T>>())
    .define_constructor(Constructor<Tests::ForeignDerived<T>, T>(),
      Arg("value_"));
}
