// Generated by ruby-bindgen (1.0.0)

template<typename T, int Rows, int Cols>
inline Rice::Data_Type<Matrix<T, Rows, Cols>> Matrix_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Matrix<T, Rows, Cols>>(parent, name)
    .define_attr("data", &Matrix<T, Rows, Cols>::data, Rice::AttrAccess::Read)
    .template define_method<int(Matrix<T, Rows, Cols>::*)() const>("rows", &Matrix<T, Rows, Cols>::rows)
    .template define_method<int(Matrix<T, Rows, Cols>::*)() const>("cols", &Matrix<T, Rows, Cols>::cols);
}

template<typename T, int A, int B, int C>
inline Rice::Data_Type<MultiDefault<T, A, B, C>> MultiDefault_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<MultiDefault<T, A, B, C>>(parent, name)
    .define_constant("Sum", MultiDefault<T, A, B, C>::sum);
}

template<typename T, typename U>
inline Rice::Data_Type<TypeDefault<T, U>> TypeDefault_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<TypeDefault<T, U>>(parent, name)
    .define_attr("first", &TypeDefault<T, U>::first)
    .define_attr("second", &TypeDefault<T, U>::second);
}

template<typename T>
inline Rice::Data_Type<QualifiedDefaults::Box<T>> Box_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<QualifiedDefaults::Box<T>>(parent, name)
    .define_attr("value", &QualifiedDefaults::Box<T>::value);
}

template<typename T, typename U>
inline Rice::Data_Type<QualifiedDefaults::QualifiedTypeDefault<T, U>> QualifiedTypeDefault_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<QualifiedDefaults::QualifiedTypeDefault<T, U>>(parent, name)
    .define_attr("first", &QualifiedDefaults::QualifiedTypeDefault<T, U>::first)
    .define_attr("second", &QualifiedDefaults::QualifiedTypeDefault<T, U>::second);
}

template<typename T, typename U>
inline Rice::Data_Type<QualifiedDefaults::QualifiedNestedDefault<T, U>> QualifiedNestedDefault_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<QualifiedDefaults::QualifiedNestedDefault<T, U>>(parent, name)
    .define_attr("first", &QualifiedDefaults::QualifiedNestedDefault<T, U>::first)
    .define_attr("second", &QualifiedDefaults::QualifiedNestedDefault<T, U>::second);
}

template<typename T, int N>
inline Rice::Data_Type<QualifiedDefaults::QualifiedValueDefault<T, N>> QualifiedValueDefault_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<QualifiedDefaults::QualifiedValueDefault<T, N>>(parent, name)
    .define_constant("Value", QualifiedDefaults::QualifiedValueDefault<T, N>::value);
}

template<typename T>
inline Rice::Data_Type<TemplateTemplateDefaults::Box<T>> Box_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<TemplateTemplateDefaults::Box<T>>(parent, name)
    .define_attr("value", &TemplateTemplateDefaults::Box<T>::value);
}

template<typename T, template<typename> class Container>
inline Rice::Data_Type<TemplateTemplateDefaults::Holder<T, Container>> Holder_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<TemplateTemplateDefaults::Holder<T, Container>>(parent, name)
    .define_attr("value", &TemplateTemplateDefaults::Holder<T, Container>::value);
}

template<typename T>
inline Rice::Data_Type<TemplateTemplateDefaults::BoxWithInnerDefault<T>> BoxWithInnerDefault_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<TemplateTemplateDefaults::BoxWithInnerDefault<T>>(parent, name)
    .define_attr("value", &TemplateTemplateDefaults::BoxWithInnerDefault<T>::value);
}

template<typename T, template<typename U = int> class Container>
inline Rice::Data_Type<TemplateTemplateDefaults::HolderWithInnerDefault<T, Container>> HolderWithInnerDefault_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<TemplateTemplateDefaults::HolderWithInnerDefault<T, Container>>(parent, name)
    .define_attr("value", &TemplateTemplateDefaults::HolderWithInnerDefault<T, Container>::value);
}
