// Generated by ruby-bindgen (1.0.0)

template<typename Net>
inline Rice::Data_Type<Tests::TemplateParamShadow<Net>> TemplateParamShadow_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::TemplateParamShadow<Net>>(parent, name)
    .template define_method<Tests::TemplateParamShadow<Net> &(Tests::TemplateParamShadow<Net>::*)(const Net &)>("assign", &Tests::TemplateParamShadow<Net>::assign,
      Arg("value"));
}

template<typename... Ts>
inline Rice::Data_Type<Tests::ParameterPackHolder<Ts...>> ParameterPackHolder_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::ParameterPackHolder<Ts...>>(parent, name)
    .define_constructor(Constructor<Tests::ParameterPackHolder<Ts...>>())
    .define_constructor(Constructor<Tests::ParameterPackHolder<Ts...>, const Tests::ParameterPackHolder<Ts...> &>(),
      Arg("other"))
    .template define_method<void(Tests::ParameterPackHolder<Ts...>::*)(Tests::ParameterPackHolder<Ts...> &)>("swap", &Tests::ParameterPackHolder<Ts...>::swap,
      Arg("rhs"));
}
