// Generated by ruby-bindgen (1.0.0)

#include <template_partial_specializations.hpp>
#include "template_partial_specializations-rb.hpp"

using namespace Rice;

#include "template_partial_specializations-rb.ipp"

void Init_TemplatePartialSpecializations()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::Context> rb_cTestsContext = define_class_under<Tests::Context>(rb_mTests, "Context")
    .define_constructor(Constructor<Tests::Context>());

  Rice::Data_Type<Tests::Mat> rb_cTestsMat = define_class_under<Tests::Mat>(rb_mTests, "Mat")
    .define_constructor(Constructor<Tests::Mat>());

  Rice::Data_Type<Tests::Token> rb_cTestsToken = define_class_under<Tests::Token>(rb_mTests, "Token")
    .define_constructor(Constructor<Tests::Token>());

  Module rb_mTestsDetail = define_module_under(rb_mTests, "Detail");

  Rice::Data_Type<Tests::detail::get_in<Tests::Array<Tests::Token>>> rb_cTestsDetailGetInArrayToken = define_class_under<Tests::detail::get_in<Tests::Array<Tests::Token>>, Tests::detail::get_in<Tests::Array<Tests::Mat>>>(rb_mTestsDetail, "GetInArrayToken")
    .define_constructor(Constructor<Tests::detail::get_in<Tests::Array<Tests::Token>>>());

  Rice::Data_Type<Tests::detail::get_out<Tests::Array<Tests::Token>>> rb_cTestsDetailGetOutArrayToken = define_class_under<Tests::detail::get_out<Tests::Array<Tests::Token>>, Tests::detail::get_out<Tests::Array<Tests::Mat>>>(rb_mTestsDetail, "GetOutArrayToken")
    .define_constructor(Constructor<Tests::detail::get_out<Tests::Array<Tests::Token>>>());

  Rice::Data_Type<Tests::FileStorage> rb_cTestsFileStorage = define_class_under<Tests::FileStorage>(rb_mTests, "FileStorage");

  Rice::Data_Type<Tests::FileStorage::Impl> rb_cTestsFileStorageImpl = define_class_under<Tests::FileStorage::Impl>(rb_cTestsFileStorage, "Impl");
  rb_cTestsFileStorage
    .define_constructor(Constructor<Tests::FileStorage>());
}
