// Generated by ruby-bindgen (1.0.0)

#include <unions.hpp>
#include "unions-rb.hpp"

using namespace Rice;

void Init_Unions()
{
  Module rb_mUnions = define_module("Unions");

  Rice::Data_Type<Unions::SimpleUnion> simple_union = define_class<Unions::SimpleUnion>("SimpleUnion")
    .define_attr("i", &Unions::SimpleUnion::i)
    .define_attr("d", &Unions::SimpleUnion::d);

  Rice::Data_Type<Unions::NestedUnion::Inner> inner = define_class<Unions::NestedUnion::Inner>("Inner")
    .define_attr("x", &Unions::NestedUnion::Inner::x)
    .define_attr("y", &Unions::NestedUnion::Inner::y);

  Rice::Data_Type<Unions::NestedUnion> nested_union = define_class<Unions::NestedUnion>("NestedUnion")
    .define_attr("inner", &Unions::NestedUnion::inner)
    .define_attr("z", &Unions::NestedUnion::z);

  Rice::Data_Type<Unions::UnionWithStruct::Data> rb_cUnionsUnionWithStructData = define_class<Unions::UnionWithStruct::Data>("Data")
    .define_constructor(Constructor<Unions::UnionWithStruct::Data>())
    .define_attr("a", &Unions::UnionWithStruct::Data::a)
    .define_attr("b", &Unions::UnionWithStruct::Data::b);

  Rice::Data_Type<Unions::UnionWithStruct> union_with_struct = define_class<Unions::UnionWithStruct>("UnionWithStruct")
    .define_attr("data", &Unions::UnionWithStruct::data)
    .define_attr("raw", &Unions::UnionWithStruct::raw);

  Rice::Data_Type<Unions::UnionWithAnonymousStruct> union_with_anonymous_struct = define_class<Unions::UnionWithAnonymousStruct>("UnionWithAnonymousStruct")
    .define_attr("raw", &Unions::UnionWithAnonymousStruct::raw);

  Rice::Data_Type<Unions::UnionWithCallback> union_with_callback = define_class<Unions::UnionWithCallback>("UnionWithCallback")
    .define_attr("handler", &Unions::UnionWithCallback::handler)
    .define_attr("raw", &Unions::UnionWithCallback::raw);
}
