// Generated by ruby-bindgen (1.0.0)

#include <unresolved_inline_calls.hpp>
#include "unresolved_inline_calls-rb.hpp"

using namespace Rice;

#include "unresolved_inline_calls-rb.ipp"

void Init_UnresolvedInlineCalls()
{
  Module rb_mTests = define_module("Tests");

  Module rb_mTestsBroken = define_module_under(rb_mTests, "Broken");
}
