// Generated by ruby-bindgen (1.0.0)

template<typename T>
inline Rice::Data_Type<Tests::Params<T>> Params_instantiate(Rice::Module parent, const char* name)
{
  return Rice::define_class_under<Tests::Params<T>>(parent, name)
    .template define_method<int(Tests::Params<T>::*)() const>("ok", &Tests::Params<T>::ok);
}
