// Generated by ruby-bindgen (1.0.0)

#include <unsupported_vector_returns.hpp>
#include "unsupported_vector_returns-rb.hpp"

using namespace Rice;

void Init_UnsupportedVectorReturns()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::UnsupportedVectorValue> rb_cTestsUnsupportedVectorValue = define_class_under<Tests::UnsupportedVectorValue>(rb_mTests, "UnsupportedVectorValue")
    .define_constructor(Constructor<Tests::UnsupportedVectorValue>())
    .define_attr("value", &Tests::UnsupportedVectorValue::value);

  Rice::Data_Type<Tests::UnsupportedVectorReturns> rb_cTestsUnsupportedVectorReturns = define_class_under<Tests::UnsupportedVectorReturns>(rb_mTests, "UnsupportedVectorReturns")
    .define_constructor(Constructor<Tests::UnsupportedVectorReturns>())
    .define_method<Tests::UnsupportedVectorReturns::Items(Tests::UnsupportedVectorReturns::*)() const>("items", &Tests::UnsupportedVectorReturns::items)
    .define_method("to_items", [](Tests::UnsupportedVectorReturns& self) -> Tests::UnsupportedVectorReturns::Items
    {
      return static_cast<Tests::UnsupportedVectorReturns::Items>(self);
    });
}
