// Generated by ruby-bindgen (1.0.0)

#include <vector_variant_attrs.hpp>
#include "vector_variant_attrs-rb.hpp"

using namespace Rice;

void Init_VectorVariantAttrs()
{
  Module rb_mTests = define_module("Tests");

  Rice::Data_Type<Tests::Token> rb_cTestsToken = define_class_under<Tests::Token>(rb_mTests, "Token")
    .define_constructor(Constructor<Tests::Token>());

  Rice::Data_Type<Tests::VariantVectorHolder> rb_cTestsVariantVectorHolder = define_class_under<Tests::VariantVectorHolder>(rb_mTests, "VariantVectorHolder")
    .define_constructor(Constructor<Tests::VariantVectorHolder>())
    .define_attr("values", &Tests::VariantVectorHolder::values)
    .define_attr("numbers", &Tests::VariantVectorHolder::numbers);
}
