// Generated by ruby-bindgen (1.0.0)

#include <version_guards.hpp>
#include "version_guards-rb.hpp"

using namespace Rice;

#include "version_guards-rb.ipp"

void Init_VersionGuards()
{
  Module rb_mGuards = define_module("Guards");

  Rice::Data_Type<Guards::MyClass> rb_cGuardsMyClass = define_class_under<Guards::MyClass>(rb_mGuards, "MyClass")
    .define_constructor(Constructor<Guards::MyClass>())
    .define_method<void(Guards::MyClass::*)()>("existing_method", &Guards::MyClass::existingMethod)
    .define_method<void(Guards::MyClass::*)(int)>("overloaded", &Guards::MyClass::overloaded,
      Arg("x"))
    .define_constant("EXISTING_CONST", (int)Guards::MyClass::EXISTING_CONST)
    #if TEST_VERSION >= 20000
    .define_constructor(Constructor<Guards::MyClass, int, bool>(),
      Arg("x"), Arg("flag"))
    .define_method<void(Guards::MyClass::*)()>("new_method", &Guards::MyClass::newMethod)
    .define_method<void(Guards::MyClass::*)(int, bool)>("overloaded", &Guards::MyClass::overloaded,
      Arg("x"), Arg("flag"))
    .define_constant("NEW_CONST", (int)Guards::MyClass::NEW_CONST)
    #endif
    ;

  rb_mGuards.define_constant("EXISTING_FLAG", (int)Guards::EXISTING_FLAG);

  #if TEST_VERSION >= 20000

  rb_mGuards.define_constant("NEW_FLAG", (int)Guards::NEW_FLAG);

  #endif

  Rice::Data_Type<Guards::DataType<int>> rb_cGuardsDataTypeInt = define_class_under<Guards::DataType<int>>(rb_mGuards, "DataTypeInt")
    .define_constructor(Constructor<Guards::DataType<int>>())
    .define_singleton_function<int(*)()>("depth", &Guards::DataType<int>::depth);

  #if TEST_VERSION >= 20000

  rb_mGuards.define_module_function<void(*)(int)>("new_function", &Guards::newFunction,
    Arg("x"));

  Rice::Data_Type<Guards::HalfFloat> rb_cGuardsHalfFloat = define_class_under<Guards::HalfFloat>(rb_mGuards, "HalfFloat")
    .define_constructor(Constructor<Guards::HalfFloat>())
    .define_attr("value", &Guards::HalfFloat::value);

  Rice::Data_Type<Guards::DataType<Guards::HalfFloat>> rb_cGuardsDataTypeHalfFloat = define_class_under<Guards::DataType<Guards::HalfFloat>>(rb_mGuards, "DataTypeHalfFloat")
    .define_constructor(Constructor<Guards::DataType<Guards::HalfFloat>>())
    .define_singleton_function<int(*)()>("depth", &Guards::DataType<Guards::HalfFloat>::depth);

  rb_mGuards.define_module_function<Guards::HalfFloat(*)(int)>("saturate_cast", &Guards::saturate_cast,
    Arg("v"));

  #endif
}
