// Generated by ruby-bindgen (1.0.0)

#include <guards/dnn/layer.hpp>
#include "layer-rb.hpp"

using namespace Rice;

void Init_Dnn_Layer()
{
  Module rb_mGuardFixtures = define_module("GuardFixtures");

  Module rb_mGuardFixturesDnn = define_module_under(rb_mGuardFixtures, "Dnn");

  Rice::Data_Type<GuardFixtures::Dnn::Layer> rb_cGuardFixturesDnnLayer = define_class_under<GuardFixtures::Dnn::Layer>(rb_mGuardFixturesDnn, "Layer")
    .define_constructor(Constructor<GuardFixtures::Dnn::Layer>());
}
