# Generated by ruby-bindgen (1.0.0)

module Constants
  ConstInt = 10
  StaticConstInt = 20
  ConstDouble = 3.14
  ConstFloat = 2.5f
  ConstChar = 'A'
  ConstLong = 100000L
  ConstUint = 42

  enum(
    :ANON_MAX_SIZE, 100,
    :ANON_MIN_SIZE, 10
  )
end
