# Generated by ruby-bindgen (1.0.0)

module Constants
  ConstInt = 10
  StaticConstInt = 20
  ConstDouble = 3.14
  ConstFloat = 2.5
  ConstChar = 'A'
  ConstLong = 100000
  ConstUint = 42
  ConstUll = 1
  ConstUllLong = 0xffffffff
  ConstHex = 0xff
  ConstHexUpper = 0xFF

  enum(
    :ANON_MAX_SIZE, 100,
    :ANON_MIN_SIZE, 10
  )
end
