# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

FFI::DynamicLibrary::SEARCH_PATH = ["c:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin"]

module Filtering
  extend FFI::Library

  def self.library_names
    ["filtering"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  attach_function :included_function, :includedFunction, [:int], :int
  attach_function :keep_this_function, :keepThisFunction, [:double, :double], :double

  class IncludedStruct < FFI::Struct
    layout :x, :int,
           :y, :int
  end

  IncludedEnum = enum(
    :value_one, 0,
    :value_two, 1
  )

  typedef :int, :included_typedef
end
