# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

module Forward
  extend FFI::Library

  def self.library_names
    ["forward"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  class F < FFI::Struct
    layout :b, :pointer,
           :c, :pointer
  end

  class B < FFI::Struct
    layout :bname, :pointer
  end

  class C < FFI::Struct
    layout :cname, :pointer
  end

  typedef :pointer, :Opaque
  attach_function :use_opaque, :use_opaque, [:pointer], :void
  attach_function :create_opaque, :create_opaque, [], :pointer
end
