# Generated by ruby-bindgen (1.0.0)

module Functions
  attach_function :add, :add, [:int, :int], :int
  attach_function :my_printf, :my_printf, [:string, :varargs], :int
  attach_function :log_message, :log_message, [:int, :string, :string, :varargs], :void
end
