# Generated by ruby-bindgen (1.0.0)

module LinkageSpec
  attach_function :extern_c_function, :extern_c_function, [:int], :int

  class ExternCStruct < FFI::Struct
    layout :field, :int,
           :value, :double
  end

  ExternCEnum = enum(
    :EXTERN_A, 0,
    :EXTERN_B, 1
  )

  typedef :int, :extern_c_typedef
end
