# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

module Proj
  module Api
    extend FFI::Library

    def self.library_names
      ["proj"]
    end

    def self.library_versions
      []
    end

    def self.search_names
      result = Array.new
      self.library_names.each do |name|
        result << "lib#{name}"
        self.library_versions.each do |version|
          case RbConfig::CONFIG['host_os']
            when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
              result << "lib#{name}-#{version}"
              result << "lib#{name}_#{version}"
            when /darwin|mac os/
              result << "lib#{name}.#{version}"
            else
              result << "lib#{name}.so.#{version}"
          end
        end
      end
      result
    end

    ffi_lib self.search_names
  end
end

require_relative 'proj_version'
require_relative './proj'
require_relative './proj_experimental'
