# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

FFI::DynamicLibrary::SEARCH_PATH = ["c:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin"]

module Proj
  extend FFI::Library

  def self.library_names
    ["proj"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  PROJ_VERSION_MAJOR = 9
  PROJ_VERSION_MINOR = 6
  PROJ_VERSION_PATCH = 2
  PJ_DEFAULT_CTX = 0
  PROJ_ERR_INVALID_OP = 1024
  PROJ_ERR_COORD_TRANSFM = 2048
  PROJ_ERR_OTHER = 4096
  attach_variable :PjRelease, :pj_release, :string
  typedef :pointer, :PJ_AREA

  class P5_FACTORS < FFI::Struct
    layout :meridional_scale, :double,
           :parallel_scale, :double,
           :areal_scale, :double,
           :angular_distortion, :double,
           :meridian_parallel_angle, :double,
           :meridian_convergence, :double,
           :tissot_semimajor, :double,
           :tissot_semiminor, :double,
           :dx_dlam, :double,
           :dx_dphi, :double,
           :dy_dlam, :double,
           :dy_dphi, :double
  end

  typedef :pointer, :PJconsts
  callback :PJ_LIST_proj_callback, [:pointer], :pointer

  class PJ_LIST < FFI::Struct
    layout :id, :string,
           :proj, :PJ_LIST_proj_callback,
           :descr, :pointer
  end

  class PJ_ELLPS < FFI::Struct
    layout :id, :string,
           :major, :string,
           :ell, :string,
           :name, :string
  end

  class PJ_UNITS < FFI::Struct
    layout :id, :string,
           :to_meter, :string,
           :name, :string,
           :factor, :double
  end

  class PJ_PRIME_MERIDIANS < FFI::Struct
    layout :id, :string,
           :defn, :string
  end

  class PJ_XYZT < FFI::Struct
    layout :x, :double,
           :y, :double,
           :z, :double,
           :t, :double
  end

  class PJ_UVWT < FFI::Struct
    layout :u, :double,
           :v, :double,
           :w, :double,
           :t, :double
  end

  class PJ_LPZT < FFI::Struct
    layout :lam, :double,
           :phi, :double,
           :z, :double,
           :t, :double
  end

  class PJ_OPK < FFI::Struct
    layout :o, :double,
           :p, :double,
           :k, :double
  end

  class PJ_ENU < FFI::Struct
    layout :e, :double,
           :n, :double,
           :u, :double
  end

  class PJ_GEOD < FFI::Struct
    layout :s, :double,
           :a1, :double,
           :a2, :double
  end

  class PJ_UV < FFI::Struct
    layout :u, :double,
           :v, :double
  end

  class PJ_XY < FFI::Struct
    layout :x, :double,
           :y, :double
  end

  class PJ_LP < FFI::Struct
    layout :lam, :double,
           :phi, :double
  end

  class PJ_XYZ < FFI::Struct
    layout :x, :double,
           :y, :double,
           :z, :double
  end

  class PJ_UVW < FFI::Struct
    layout :u, :double,
           :v, :double,
           :w, :double
  end

  class PJ_LPZ < FFI::Struct
    layout :lam, :double,
           :phi, :double,
           :z, :double
  end

  class PJ_COORD < FFI::Union
    layout :v, [:double, 4],
           :xyzt, PJ_XYZT,
           :uvwt, PJ_UVWT,
           :lpzt, PJ_LPZT,
           :geod, PJ_GEOD,
           :opk, PJ_OPK,
           :enu, PJ_ENU,
           :xyz, PJ_XYZ,
           :uvw, PJ_UVW,
           :lpz, PJ_LPZ,
           :xy, PJ_XY,
           :uv, PJ_UV,
           :lp, PJ_LP
  end

  class PJ_INFO < FFI::Struct
    layout :major, :int,
           :minor, :int,
           :patch, :int,
           :release, :string,
           :version, :string,
           :searchpath, :string,
           :paths, :pointer,
           :path_count, :ulong
  end

  class PJ_PROJ_INFO < FFI::Struct
    layout :id, :string,
           :description, :string,
           :definition, :string,
           :has_inverse, :int,
           :accuracy, :double
  end

  class PJ_GRID_INFO < FFI::Struct
    layout :gridname, [:char, 32],
           :filename, [:char, 260],
           :format, [:char, 8],
           :lowerleft, PJ_LP,
           :upperright, PJ_LP,
           :n_lon, :int,
           :n_lat, :int,
           :cs_lon, :double,
           :cs_lat, :double
  end

  class PJ_INIT_INFO < FFI::Struct
    layout :name, [:char, 32],
           :filename, [:char, 260],
           :version, [:char, 32],
           :origin, [:char, 32],
           :lastupdate, [:char, 16]
  end

  PJ_LOG_LEVEL = enum(
    :pj_log_none, 0,
    :pj_log_error, 1,
    :pj_log_debug, 2,
    :pj_log_trace, 3,
    :pj_log_tell, 4,
    :pj_log_debug_major, 2,
    :pj_log_debug_minor, 3
  )

  callback :pj_log_function, [], :void
  typedef :pointer, :PjCtx
  attach_function :proj_context_create, :proj_context_create, [], :pointer
  attach_function :proj_context_destroy, :proj_context_destroy, [:pointer], :pointer
  attach_function :proj_context_clone, :proj_context_clone, [:pointer], :pointer
  callback :proj_file_finder, [], :pointer
  attach_function :proj_context_set_file_finder, :proj_context_set_file_finder, [:pointer, :pointer, :pointer], :void
  attach_function :proj_context_set_search_paths, :proj_context_set_search_paths, [:pointer, :int, :pointer], :void
  attach_function :proj_context_set_ca_bundle_path, :proj_context_set_ca_bundle_path, [:pointer, :string], :void
  attach_function :proj_context_use_proj4_init_rules, :proj_context_use_proj4_init_rules, [:pointer, :int], :void
  attach_function :proj_context_get_use_proj4_init_rules, :proj_context_get_use_proj4_init_rules, [:pointer, :int], :int
  typedef :pointer, :PROJ_FILE_HANDLE

  PROJ_OPEN_ACCESS = enum(
    :proj_open_access_read_only, 0,
    :proj_open_access_read_update, 1,
    :proj_open_access_create, 2
  )

  callback :PROJ_FILE_API_open_cbk_callback, [:pointer, :string, PROJ_OPEN_ACCESS, :pointer], :pointer
  callback :PROJ_FILE_API_read_cbk_callback, [:pointer, :pointer, :pointer, :ulong, :pointer], :ulong
  callback :PROJ_FILE_API_write_cbk_callback, [:pointer, :pointer, :pointer, :ulong, :pointer], :ulong
  callback :PROJ_FILE_API_seek_cbk_callback, [:pointer, :pointer, :long_long, :int, :pointer], :int
  callback :PROJ_FILE_API_tell_cbk_callback, [:pointer, :pointer, :pointer], :ulong_long
  callback :PROJ_FILE_API_close_cbk_callback, [:pointer, :pointer, :pointer], :void
  callback :PROJ_FILE_API_exists_cbk_callback, [:pointer, :string, :pointer], :int
  callback :PROJ_FILE_API_mkdir_cbk_callback, [:pointer, :string, :pointer], :int
  callback :PROJ_FILE_API_unlink_cbk_callback, [:pointer, :string, :pointer], :int
  callback :PROJ_FILE_API_rename_cbk_callback, [:pointer, :string, :string, :pointer], :int

  class PROJ_FILE_API < FFI::Struct
    layout :version, :int,
           :open_cbk, :PROJ_FILE_API_open_cbk_callback,
           :read_cbk, :PROJ_FILE_API_read_cbk_callback,
           :write_cbk, :PROJ_FILE_API_write_cbk_callback,
           :seek_cbk, :PROJ_FILE_API_seek_cbk_callback,
           :tell_cbk, :PROJ_FILE_API_tell_cbk_callback,
           :close_cbk, :PROJ_FILE_API_close_cbk_callback,
           :exists_cbk, :PROJ_FILE_API_exists_cbk_callback,
           :mkdir_cbk, :PROJ_FILE_API_mkdir_cbk_callback,
           :unlink_cbk, :PROJ_FILE_API_unlink_cbk_callback,
           :rename_cbk, :PROJ_FILE_API_rename_cbk_callback
  end

  attach_function :proj_context_set_fileapi, :proj_context_set_fileapi, [:pointer, PROJ_FILE_API.by_ref, :pointer], :int
  attach_function :proj_context_set_sqlite3_vfs_name, :proj_context_set_sqlite3_vfs_name, [:pointer, :string], :void
  typedef :pointer, :PROJ_NETWORK_HANDLE
  callback :proj_network_open_cbk_type, [], :pointer
  callback :proj_network_close_cbk_type, [], :void
  callback :proj_network_get_header_value_cbk_type, [], :pointer
  callback :proj_network_read_range_type, [], :ulong
  attach_function :proj_context_set_network_callbacks, :proj_context_set_network_callbacks, [:pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_context_set_enable_network, :proj_context_set_enable_network, [:pointer, :int], :int
  attach_function :proj_context_is_network_enabled, :proj_context_is_network_enabled, [:pointer], :int
  attach_function :proj_context_set_url_endpoint, :proj_context_set_url_endpoint, [:pointer, :string], :void
  attach_function :proj_context_get_url_endpoint, :proj_context_get_url_endpoint, [:pointer], :string
  attach_function :proj_context_get_user_writable_directory, :proj_context_get_user_writable_directory, [:pointer, :int], :string
  attach_function :proj_context_set_user_writable_directory, :proj_context_set_user_writable_directory, [:pointer, :string, :int], :void
  attach_function :proj_grid_cache_set_enable, :proj_grid_cache_set_enable, [:pointer, :int], :void
  attach_function :proj_grid_cache_set_filename, :proj_grid_cache_set_filename, [:pointer, :string], :void
  attach_function :proj_grid_cache_set_max_size, :proj_grid_cache_set_max_size, [:pointer, :int], :void
  attach_function :proj_grid_cache_set_ttl, :proj_grid_cache_set_ttl, [:pointer, :int], :void
  attach_function :proj_grid_cache_clear, :proj_grid_cache_clear, [:pointer], :void
  attach_function :proj_is_download_needed, :proj_is_download_needed, [:pointer, :string, :int], :int
  callback :proj_download_file_progress_cbk_callback, [:pointer, :double, :pointer], :int
  attach_function :proj_download_file, :proj_download_file, [:pointer, :string, :int, :proj_download_file_progress_cbk_callback, :pointer], :int
  attach_function :proj_create, :proj_create, [:pointer, :string], :pointer
  attach_function :proj_create_argv, :proj_create_argv, [:pointer, :int, :pointer], :pointer
  attach_function :proj_create_crs_to_crs, :proj_create_crs_to_crs, [:pointer, :string, :string, :pointer], :pointer
  attach_function :proj_create_crs_to_crs_from_pj, :proj_create_crs_to_crs_from_pj, [:pointer, :pointer, :pointer, :pointer, :pointer], :pointer
  attach_function :proj_normalize_for_visualization, :proj_normalize_for_visualization, [:pointer, :pointer], :pointer
  attach_function :proj_assign_context, :proj_assign_context, [:pointer, :pointer], :void
  attach_function :proj_destroy, :proj_destroy, [:pointer], :pointer
  attach_function :proj_area_create, :proj_area_create, [], :pointer
  attach_function :proj_area_set_bbox, :proj_area_set_bbox, [:pointer, :double, :double, :double, :double], :void
  attach_function :proj_area_set_name, :proj_area_set_name, [:pointer, :string], :void
  attach_function :proj_area_destroy, :proj_area_destroy, [:pointer], :void

  PJ_DIRECTION = enum(
    :pj_fwd, 1,
    :pj_ident, 0,
    :pj_inv, -1
  )

  attach_function :proj_angular_input, :proj_angular_input, [:pointer, PJ_DIRECTION], :int
  attach_function :proj_angular_output, :proj_angular_output, [:pointer, PJ_DIRECTION], :int
  attach_function :proj_degree_input, :proj_degree_input, [:pointer, PJ_DIRECTION], :int
  attach_function :proj_degree_output, :proj_degree_output, [:pointer, PJ_DIRECTION], :int
  attach_function :proj_trans, :proj_trans, [:pointer, PJ_DIRECTION, PJ_COORD.by_value], PJ_COORD.by_value
  attach_function :proj_trans_get_last_used_operation, :proj_trans_get_last_used_operation, [:pointer], :pointer
  attach_function :proj_trans_array, :proj_trans_array, [:pointer, PJ_DIRECTION, :ulong, PJ_COORD.by_ref], :int
  attach_function :proj_trans_generic, :proj_trans_generic, [:pointer, PJ_DIRECTION, :pointer, :ulong, :ulong, :pointer, :ulong, :ulong, :pointer, :ulong, :ulong, :pointer, :ulong, :ulong], :ulong
  attach_function :proj_trans_bounds, :proj_trans_bounds, [:pointer, :pointer, PJ_DIRECTION, :double, :double, :double, :double, :pointer, :pointer, :pointer, :pointer, :int], :int
  attach_function :proj_trans_bounds_3d, :proj_trans_bounds_3D, [:pointer, :pointer, PJ_DIRECTION, :double, :double, :double, :double, :double, :double, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer, :int], :int
  attach_function :proj_coord, :proj_coord, [:double, :double, :double, :double], PJ_COORD.by_value
  attach_function :proj_roundtrip, :proj_roundtrip, [:pointer, PJ_DIRECTION, :int, PJ_COORD.by_ref], :double
  attach_function :proj_lp_dist, :proj_lp_dist, [:pointer, PJ_COORD.by_value, PJ_COORD.by_value], :double
  attach_function :proj_lpz_dist, :proj_lpz_dist, [:pointer, PJ_COORD.by_value, PJ_COORD.by_value], :double
  attach_function :proj_xy_dist, :proj_xy_dist, [PJ_COORD.by_value, PJ_COORD.by_value], :double
  attach_function :proj_xyz_dist, :proj_xyz_dist, [PJ_COORD.by_value, PJ_COORD.by_value], :double
  attach_function :proj_geod, :proj_geod, [:pointer, PJ_COORD.by_value, PJ_COORD.by_value], PJ_COORD.by_value
  attach_function :proj_context_errno, :proj_context_errno, [:pointer], :int
  attach_function :proj_errno, :proj_errno, [:pointer], :int
  attach_function :proj_errno_set, :proj_errno_set, [:pointer, :int], :int
  attach_function :proj_errno_reset, :proj_errno_reset, [:pointer], :int
  attach_function :proj_errno_restore, :proj_errno_restore, [:pointer, :int], :int
  attach_function :proj_errno_string, :proj_errno_string, [:int], :string
  attach_function :proj_context_errno_string, :proj_context_errno_string, [:pointer, :int], :string
  attach_function :proj_log_level, :proj_log_level, [:pointer, PJ_LOG_LEVEL], PJ_LOG_LEVEL
  attach_function :proj_log_func, :proj_log_func, [:pointer, :pointer, :pointer], :void
  attach_function :proj_factors, :proj_factors, [:pointer, PJ_COORD.by_value], P5_FACTORS.by_value
  attach_function :proj_info, :proj_info, [], PJ_INFO.by_value
  attach_function :proj_pj_info, :proj_pj_info, [:pointer], PJ_PROJ_INFO.by_value
  attach_function :proj_grid_info, :proj_grid_info, [:string], PJ_GRID_INFO.by_value
  attach_function :proj_init_info, :proj_init_info, [:string], PJ_INIT_INFO.by_value
  attach_function :proj_list_operations, :proj_list_operations, [], PJ_LIST.by_ref
  attach_function :proj_list_ellps, :proj_list_ellps, [], PJ_ELLPS.by_ref
  attach_function :proj_list_prime_meridians, :proj_list_prime_meridians, [], PJ_PRIME_MERIDIANS.by_ref
  attach_function :proj_torad, :proj_torad, [:double], :double
  attach_function :proj_todeg, :proj_todeg, [:double], :double
  attach_function :proj_dmstor, :proj_dmstor, [:string, :pointer], :double
  attach_function :proj_rtodms2, :proj_rtodms2, [:string, :ulong, :double, :int, :int], :string
  attach_function :proj_cleanup, :proj_cleanup, [], :void
  typedef :pointer, :proj_string_list

  PJ_GUESSED_WKT_DIALECT = enum(
    :pj_guessed_wkt2_2019, 0,
    :pj_guessed_wkt2_2018, 0,
    :pj_guessed_wkt2_2015, 1,
    :pj_guessed_wkt1_gdal, 2,
    :pj_guessed_wkt1_esri, 3,
    :pj_guessed_not_wkt, 4
  )

  PJ_CATEGORY = enum(
    :pj_category_ellipsoid, 0,
    :pj_category_prime_meridian, 1,
    :pj_category_datum, 2,
    :pj_category_crs, 3,
    :pj_category_coordinate_operation, 4,
    :pj_category_datum_ensemble, 5
  )

  PJ_TYPE = enum(
    :pj_type_unknown, 0,
    :pj_type_ellipsoid, 1,
    :pj_type_prime_meridian, 2,
    :pj_type_geodetic_reference_frame, 3,
    :pj_type_dynamic_geodetic_reference_frame, 4,
    :pj_type_vertical_reference_frame, 5,
    :pj_type_dynamic_vertical_reference_frame, 6,
    :pj_type_datum_ensemble, 7,
    :pj_type_crs, 8,
    :pj_type_geodetic_crs, 9,
    :pj_type_geocentric_crs, 10,
    :pj_type_geographic_crs, 11,
    :pj_type_geographic_2d_crs, 12,
    :pj_type_geographic_3d_crs, 13,
    :pj_type_vertical_crs, 14,
    :pj_type_projected_crs, 15,
    :pj_type_compound_crs, 16,
    :pj_type_temporal_crs, 17,
    :pj_type_engineering_crs, 18,
    :pj_type_bound_crs, 19,
    :pj_type_other_crs, 20,
    :pj_type_conversion, 21,
    :pj_type_transformation, 22,
    :pj_type_concatenated_operation, 23,
    :pj_type_other_coordinate_operation, 24,
    :pj_type_temporal_datum, 25,
    :pj_type_engineering_datum, 26,
    :pj_type_parametric_datum, 27,
    :pj_type_derived_projected_crs, 28,
    :pj_type_coordinate_metadata, 29
  )

  PJ_COMPARISON_CRITERION = enum(
    :pj_comp_strict, 0,
    :pj_comp_equivalent, 1,
    :pj_comp_equivalent_except_axis_order_geogcrs, 2
  )

  PJ_WKT_TYPE = enum(
    :pj_wkt2_2015, 0,
    :pj_wkt2_2015_simplified, 1,
    :pj_wkt2_2019, 2,
    :pj_wkt2_2018, 2,
    :pj_wkt2_2019_simplified, 3,
    :pj_wkt2_2018_simplified, 3,
    :pj_wkt1_gdal, 4,
    :pj_wkt1_esri, 5
  )

  PROJ_CRS_EXTENT_USE = enum(
    :pj_crs_extent_none, 0,
    :pj_crs_extent_both, 1,
    :pj_crs_extent_intersection, 2,
    :pj_crs_extent_smallest, 3
  )

  PROJ_GRID_AVAILABILITY_USE = enum(
    :proj_grid_availability_used_for_sorting, 0,
    :proj_grid_availability_discard_operation_if_missing_grid, 1,
    :proj_grid_availability_ignored, 2,
    :proj_grid_availability_known_available, 3
  )

  PJ_PROJ_STRING_TYPE = enum(
    :pj_proj_5, 0,
    :pj_proj_4, 1
  )

  PROJ_SPATIAL_CRITERION = enum(
    :proj_spatial_criterion_strict_containment, 0,
    :proj_spatial_criterion_partial_intersection, 1
  )

  PROJ_INTERMEDIATE_CRS_USE = enum(
    :proj_intermediate_crs_use_always, 0,
    :proj_intermediate_crs_use_if_no_direct_transformation, 1,
    :proj_intermediate_crs_use_never, 2
  )

  PJ_COORDINATE_SYSTEM_TYPE = enum(
    :pj_cs_type_unknown, 0,
    :pj_cs_type_cartesian, 1,
    :pj_cs_type_ellipsoidal, 2,
    :pj_cs_type_vertical, 3,
    :pj_cs_type_spherical, 4,
    :pj_cs_type_ordinal, 5,
    :pj_cs_type_parametric, 6,
    :pj_cs_type_datetimetemporal, 7,
    :pj_cs_type_temporalcount, 8,
    :pj_cs_type_temporalmeasure, 9
  )

  class PROJ_CRS_INFO < FFI::Struct
    layout :auth_name, :string,
           :code, :string,
           :name, :string,
           :type, PJ_TYPE,
           :deprecated, :int,
           :bbox_valid, :int,
           :west_lon_degree, :double,
           :south_lat_degree, :double,
           :east_lon_degree, :double,
           :north_lat_degree, :double,
           :area_name, :string,
           :projection_method_name, :string,
           :celestial_body_name, :string
  end

  class PROJ_CRS_LIST_PARAMETERS < FFI::Struct
    layout :types, :pointer,
           :types_count, :ulong,
           :crs_area_of_use_contains_bbox, :int,
           :bbox_valid, :int,
           :west_lon_degree, :double,
           :south_lat_degree, :double,
           :east_lon_degree, :double,
           :north_lat_degree, :double,
           :allow_deprecated, :int,
           :celestial_body_name, :string
  end

  class PROJ_UNIT_INFO < FFI::Struct
    layout :auth_name, :string,
           :code, :string,
           :name, :string,
           :category, :string,
           :conv_factor, :double,
           :proj_short_name, :string,
           :deprecated, :int
  end

  class PROJ_CELESTIAL_BODY_INFO < FFI::Struct
    layout :auth_name, :string,
           :name, :string
  end

  typedef :pointer, :PJ_OBJ_LIST
  attach_function :proj_string_list_destroy, :proj_string_list_destroy, [:pointer], :void
  attach_function :proj_context_set_autoclose_database, :proj_context_set_autoclose_database, [:pointer, :int], :void
  attach_function :proj_context_set_database_path, :proj_context_set_database_path, [:pointer, :string, :pointer, :pointer], :int
  attach_function :proj_context_get_database_path, :proj_context_get_database_path, [:pointer], :string
  attach_function :proj_context_get_database_metadata, :proj_context_get_database_metadata, [:pointer, :string], :string
  attach_function :proj_context_get_database_structure, :proj_context_get_database_structure, [:pointer, :pointer], :pointer
  attach_function :proj_context_guess_wkt_dialect, :proj_context_guess_wkt_dialect, [:pointer, :string], PJ_GUESSED_WKT_DIALECT
  attach_function :proj_create_from_wkt, :proj_create_from_wkt, [:pointer, :string, :pointer, :pointer, :pointer], :pointer
  attach_function :proj_create_from_database, :proj_create_from_database, [:pointer, :string, :string, PJ_CATEGORY, :int, :pointer], :pointer
  attach_function :proj_uom_get_info_from_database, :proj_uom_get_info_from_database, [:pointer, :string, :string, :pointer, :pointer, :pointer], :int
  attach_function :proj_grid_get_info_from_database, :proj_grid_get_info_from_database, [:pointer, :string, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_clone, :proj_clone, [:pointer, :pointer], :pointer
  attach_function :proj_create_from_name, :proj_create_from_name, [:pointer, :string, :string, :pointer, :ulong, :int, :ulong, :pointer], :pointer
  attach_function :proj_get_type, :proj_get_type, [:pointer], PJ_TYPE
  attach_function :proj_is_deprecated, :proj_is_deprecated, [:pointer], :int
  attach_function :proj_get_non_deprecated, :proj_get_non_deprecated, [:pointer, :pointer], :pointer
  attach_function :proj_is_equivalent_to, :proj_is_equivalent_to, [:pointer, :pointer, PJ_COMPARISON_CRITERION], :int
  attach_function :proj_is_equivalent_to_with_ctx, :proj_is_equivalent_to_with_ctx, [:pointer, :pointer, :pointer, PJ_COMPARISON_CRITERION], :int
  attach_function :proj_is_crs, :proj_is_crs, [:pointer], :int
  attach_function :proj_get_name, :proj_get_name, [:pointer], :string
  attach_function :proj_get_id_auth_name, :proj_get_id_auth_name, [:pointer, :int], :string
  attach_function :proj_get_id_code, :proj_get_id_code, [:pointer, :int], :string
  attach_function :proj_get_remarks, :proj_get_remarks, [:pointer], :string
  attach_function :proj_get_domain_count, :proj_get_domain_count, [:pointer], :int
  attach_function :proj_get_scope, :proj_get_scope, [:pointer], :string
  attach_function :proj_get_scope_ex, :proj_get_scope_ex, [:pointer, :int], :string
  attach_function :proj_get_area_of_use, :proj_get_area_of_use, [:pointer, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_get_area_of_use_ex, :proj_get_area_of_use_ex, [:pointer, :pointer, :int, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_as_wkt, :proj_as_wkt, [:pointer, :pointer, PJ_WKT_TYPE, :pointer], :string
  attach_function :proj_as_proj_string, :proj_as_proj_string, [:pointer, :pointer, PJ_PROJ_STRING_TYPE, :pointer], :string
  attach_function :proj_as_projjson, :proj_as_projjson, [:pointer, :pointer, :pointer], :string
  attach_function :proj_get_source_crs, :proj_get_source_crs, [:pointer, :pointer], :pointer
  attach_function :proj_get_target_crs, :proj_get_target_crs, [:pointer, :pointer], :pointer
  attach_function :proj_identify, :proj_identify, [:pointer, :pointer, :string, :pointer, :pointer], :pointer
  attach_function :proj_get_geoid_models_from_database, :proj_get_geoid_models_from_database, [:pointer, :string, :string, :pointer], :pointer
  attach_function :proj_int_list_destroy, :proj_int_list_destroy, [:pointer], :void
  attach_function :proj_get_authorities_from_database, :proj_get_authorities_from_database, [:pointer], :pointer
  attach_function :proj_get_codes_from_database, :proj_get_codes_from_database, [:pointer, :string, PJ_TYPE, :int], :pointer
  attach_function :proj_get_celestial_body_list_from_database, :proj_get_celestial_body_list_from_database, [:pointer, :string, :pointer], :pointer
  attach_function :proj_celestial_body_list_destroy, :proj_celestial_body_list_destroy, [:pointer], :void
  attach_function :proj_get_crs_list_parameters_create, :proj_get_crs_list_parameters_create, [], PROJ_CRS_LIST_PARAMETERS.by_ref
  attach_function :proj_get_crs_list_parameters_destroy, :proj_get_crs_list_parameters_destroy, [PROJ_CRS_LIST_PARAMETERS.by_ref], :void
  attach_function :proj_get_crs_info_list_from_database, :proj_get_crs_info_list_from_database, [:pointer, :string, PROJ_CRS_LIST_PARAMETERS.by_ref, :pointer], :pointer
  attach_function :proj_crs_info_list_destroy, :proj_crs_info_list_destroy, [:pointer], :void
  attach_function :proj_get_units_from_database, :proj_get_units_from_database, [:pointer, :string, :string, :int, :pointer], :pointer
  attach_function :proj_unit_list_destroy, :proj_unit_list_destroy, [:pointer], :void
  typedef :pointer, :PJ_INSERT_SESSION
  attach_function :proj_insert_object_session_create, :proj_insert_object_session_create, [:pointer], :pointer
  attach_function :proj_insert_object_session_destroy, :proj_insert_object_session_destroy, [:pointer, :pointer], :void
  attach_function :proj_get_insert_statements, :proj_get_insert_statements, [:pointer, :pointer, :pointer, :string, :string, :int, :pointer, :pointer], :pointer
  attach_function :proj_suggests_code_for, :proj_suggests_code_for, [:pointer, :pointer, :string, :int, :pointer], :string
  attach_function :proj_string_destroy, :proj_string_destroy, [:string], :void
  typedef :pointer, :PJ_OPERATION_FACTORY_CONTEXT
  attach_function :proj_create_operation_factory_context, :proj_create_operation_factory_context, [:pointer, :string], :pointer
  attach_function :proj_operation_factory_context_destroy, :proj_operation_factory_context_destroy, [:pointer], :void
  attach_function :proj_operation_factory_context_set_desired_accuracy, :proj_operation_factory_context_set_desired_accuracy, [:pointer, :pointer, :double], :void
  attach_function :proj_operation_factory_context_set_area_of_interest, :proj_operation_factory_context_set_area_of_interest, [:pointer, :pointer, :double, :double, :double, :double], :void
  attach_function :proj_operation_factory_context_set_area_of_interest_name, :proj_operation_factory_context_set_area_of_interest_name, [:pointer, :pointer, :string], :void
  attach_function :proj_operation_factory_context_set_crs_extent_use, :proj_operation_factory_context_set_crs_extent_use, [:pointer, :pointer, PROJ_CRS_EXTENT_USE], :void
  attach_function :proj_operation_factory_context_set_spatial_criterion, :proj_operation_factory_context_set_spatial_criterion, [:pointer, :pointer, PROJ_SPATIAL_CRITERION], :void
  attach_function :proj_operation_factory_context_set_grid_availability_use, :proj_operation_factory_context_set_grid_availability_use, [:pointer, :pointer, PROJ_GRID_AVAILABILITY_USE], :void
  attach_function :proj_operation_factory_context_set_use_proj_alternative_grid_names, :proj_operation_factory_context_set_use_proj_alternative_grid_names, [:pointer, :pointer, :int], :void
  attach_function :proj_operation_factory_context_set_allow_use_intermediate_crs, :proj_operation_factory_context_set_allow_use_intermediate_crs, [:pointer, :pointer, PROJ_INTERMEDIATE_CRS_USE], :void
  attach_function :proj_operation_factory_context_set_allowed_intermediate_crs, :proj_operation_factory_context_set_allowed_intermediate_crs, [:pointer, :pointer, :pointer], :void
  attach_function :proj_operation_factory_context_set_discard_superseded, :proj_operation_factory_context_set_discard_superseded, [:pointer, :pointer, :int], :void
  attach_function :proj_operation_factory_context_set_allow_ballpark_transformations, :proj_operation_factory_context_set_allow_ballpark_transformations, [:pointer, :pointer, :int], :void
  attach_function :proj_create_operations, :proj_create_operations, [:pointer, :pointer, :pointer, :pointer], :pointer
  attach_function :proj_list_get_count, :proj_list_get_count, [:pointer], :int
  attach_function :proj_list_get, :proj_list_get, [:pointer, :pointer, :int], :pointer
  attach_function :proj_list_destroy, :proj_list_destroy, [:pointer], :void
  attach_function :proj_get_suggested_operation, :proj_get_suggested_operation, [:pointer, :pointer, PJ_DIRECTION, PJ_COORD.by_value], :int
  attach_function :proj_crs_is_derived, :proj_crs_is_derived, [:pointer, :pointer], :int
  attach_function :proj_crs_get_geodetic_crs, :proj_crs_get_geodetic_crs, [:pointer, :pointer], :pointer
  attach_function :proj_crs_get_horizontal_datum, :proj_crs_get_horizontal_datum, [:pointer, :pointer], :pointer
  attach_function :proj_crs_get_sub_crs, :proj_crs_get_sub_crs, [:pointer, :pointer, :int], :pointer
  attach_function :proj_crs_get_datum, :proj_crs_get_datum, [:pointer, :pointer], :pointer
  attach_function :proj_crs_get_datum_ensemble, :proj_crs_get_datum_ensemble, [:pointer, :pointer], :pointer
  attach_function :proj_crs_get_datum_forced, :proj_crs_get_datum_forced, [:pointer, :pointer], :pointer
  attach_function :proj_crs_has_point_motion_operation, :proj_crs_has_point_motion_operation, [:pointer, :pointer], :int
  attach_function :proj_datum_ensemble_get_member_count, :proj_datum_ensemble_get_member_count, [:pointer, :pointer], :int
  attach_function :proj_datum_ensemble_get_accuracy, :proj_datum_ensemble_get_accuracy, [:pointer, :pointer], :double
  attach_function :proj_datum_ensemble_get_member, :proj_datum_ensemble_get_member, [:pointer, :pointer, :int], :pointer
  attach_function :proj_dynamic_datum_get_frame_reference_epoch, :proj_dynamic_datum_get_frame_reference_epoch, [:pointer, :pointer], :double
  attach_function :proj_crs_get_coordinate_system, :proj_crs_get_coordinate_system, [:pointer, :pointer], :pointer
  attach_function :proj_cs_get_type, :proj_cs_get_type, [:pointer, :pointer], PJ_COORDINATE_SYSTEM_TYPE
  attach_function :proj_cs_get_axis_count, :proj_cs_get_axis_count, [:pointer, :pointer], :int
  attach_function :proj_cs_get_axis_info, :proj_cs_get_axis_info, [:pointer, :pointer, :int, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_get_ellipsoid, :proj_get_ellipsoid, [:pointer, :pointer], :pointer
  attach_function :proj_ellipsoid_get_parameters, :proj_ellipsoid_get_parameters, [:pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_get_celestial_body_name, :proj_get_celestial_body_name, [:pointer, :pointer], :string
  attach_function :proj_get_prime_meridian, :proj_get_prime_meridian, [:pointer, :pointer], :pointer
  attach_function :proj_prime_meridian_get_parameters, :proj_prime_meridian_get_parameters, [:pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_crs_get_coordoperation, :proj_crs_get_coordoperation, [:pointer, :pointer], :pointer
  attach_function :proj_coordoperation_get_method_info, :proj_coordoperation_get_method_info, [:pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_coordoperation_is_instantiable, :proj_coordoperation_is_instantiable, [:pointer, :pointer], :int
  attach_function :proj_coordoperation_has_ballpark_transformation, :proj_coordoperation_has_ballpark_transformation, [:pointer, :pointer], :int
  attach_function :proj_coordoperation_requires_per_coordinate_input_time, :proj_coordoperation_requires_per_coordinate_input_time, [:pointer, :pointer], :int
  attach_function :proj_coordoperation_get_param_count, :proj_coordoperation_get_param_count, [:pointer, :pointer], :int
  attach_function :proj_coordoperation_get_param_index, :proj_coordoperation_get_param_index, [:pointer, :pointer, :string], :int
  attach_function :proj_coordoperation_get_param, :proj_coordoperation_get_param, [:pointer, :pointer, :int, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_coordoperation_get_grid_used_count, :proj_coordoperation_get_grid_used_count, [:pointer, :pointer], :int
  attach_function :proj_coordoperation_get_grid_used, :proj_coordoperation_get_grid_used, [:pointer, :pointer, :int, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :proj_coordoperation_get_accuracy, :proj_coordoperation_get_accuracy, [:pointer, :pointer], :double
  attach_function :proj_coordoperation_get_towgs84_values, :proj_coordoperation_get_towgs84_values, [:pointer, :pointer, :pointer, :int, :int], :int
  attach_function :proj_coordoperation_create_inverse, :proj_coordoperation_create_inverse, [:pointer, :pointer], :pointer
  attach_function :proj_concatoperation_get_step_count, :proj_concatoperation_get_step_count, [:pointer, :pointer], :int
  attach_function :proj_concatoperation_get_step, :proj_concatoperation_get_step, [:pointer, :pointer, :int], :pointer
  attach_function :proj_coordinate_metadata_create, :proj_coordinate_metadata_create, [:pointer, :pointer, :double], :pointer
  attach_function :proj_coordinate_metadata_get_epoch, :proj_coordinate_metadata_get_epoch, [:pointer, :pointer], :double

  PJ_UNIT_TYPE = enum(
    :pj_ut_angular, 0,
    :pj_ut_linear, 1,
    :pj_ut_scale, 2,
    :pj_ut_time, 3,
    :pj_ut_parametric, 4
  )

  class PJ_AXIS_DESCRIPTION < FFI::Struct
    layout :name, :string,
           :abbreviation, :string,
           :direction, :string,
           :unit_name, :string,
           :unit_conv_factor, :double,
           :unit_type, PJ_UNIT_TYPE
  end

  PJ_CARTESIAN_CS_2D_TYPE = enum(
    :pj_cart2d_easting_northing, 0,
    :pj_cart2d_northing_easting, 1,
    :pj_cart2d_north_pole_easting_south_northing_south, 2,
    :pj_cart2d_south_pole_easting_north_northing_north, 3,
    :pj_cart2d_westing_southing, 4
  )

  PJ_ELLIPSOIDAL_CS_2D_TYPE = enum(
    :pj_ellps2d_longitude_latitude, 0,
    :pj_ellps2d_latitude_longitude, 1
  )

  PJ_ELLIPSOIDAL_CS_3D_TYPE = enum(
    :pj_ellps3d_longitude_latitude_height, 0,
    :pj_ellps3d_latitude_longitude_height, 1
  )

  class PJ_PARAM_DESCRIPTION < FFI::Struct
    layout :name, :string,
           :auth_name, :string,
           :code, :string,
           :value, :double,
           :unit_name, :string,
           :unit_conv_factor, :double,
           :unit_type, PJ_UNIT_TYPE
  end

  attach_function :proj_create_cs, :proj_create_cs, [:pointer, PJ_COORDINATE_SYSTEM_TYPE, :int, PJ_AXIS_DESCRIPTION.by_ref], :pointer
  attach_function :proj_create_cartesian_2d_cs, :proj_create_cartesian_2D_cs, [:pointer, PJ_CARTESIAN_CS_2D_TYPE, :string, :double], :pointer
  attach_function :proj_create_ellipsoidal_2d_cs, :proj_create_ellipsoidal_2D_cs, [:pointer, PJ_ELLIPSOIDAL_CS_2D_TYPE, :string, :double], :pointer
  attach_function :proj_create_ellipsoidal_3d_cs, :proj_create_ellipsoidal_3D_cs, [:pointer, PJ_ELLIPSOIDAL_CS_3D_TYPE, :string, :double, :string, :double], :pointer
  attach_function :proj_query_geodetic_crs_from_datum, :proj_query_geodetic_crs_from_datum, [:pointer, :string, :string, :string, :string], :pointer
  attach_function :proj_create_geographic_crs, :proj_create_geographic_crs, [:pointer, :string, :string, :string, :double, :double, :string, :double, :string, :double, :pointer], :pointer
  attach_function :proj_create_geographic_crs_from_datum, :proj_create_geographic_crs_from_datum, [:pointer, :string, :pointer, :pointer], :pointer
  attach_function :proj_create_geocentric_crs, :proj_create_geocentric_crs, [:pointer, :string, :string, :string, :double, :double, :string, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_geocentric_crs_from_datum, :proj_create_geocentric_crs_from_datum, [:pointer, :string, :pointer, :string, :double], :pointer
  attach_function :proj_create_derived_geographic_crs, :proj_create_derived_geographic_crs, [:pointer, :string, :pointer, :pointer, :pointer], :pointer
  attach_function :proj_is_derived_crs, :proj_is_derived_crs, [:pointer, :pointer], :int
  attach_function :proj_alter_name, :proj_alter_name, [:pointer, :pointer, :string], :pointer
  attach_function :proj_alter_id, :proj_alter_id, [:pointer, :pointer, :string, :string], :pointer
  attach_function :proj_crs_alter_geodetic_crs, :proj_crs_alter_geodetic_crs, [:pointer, :pointer, :pointer], :pointer
  attach_function :proj_crs_alter_cs_angular_unit, :proj_crs_alter_cs_angular_unit, [:pointer, :pointer, :string, :double, :string, :string], :pointer
  attach_function :proj_crs_alter_cs_linear_unit, :proj_crs_alter_cs_linear_unit, [:pointer, :pointer, :string, :double, :string, :string], :pointer
  attach_function :proj_crs_alter_parameters_linear_unit, :proj_crs_alter_parameters_linear_unit, [:pointer, :pointer, :string, :double, :string, :string, :int], :pointer
  attach_function :proj_crs_promote_to_3d, :proj_crs_promote_to_3D, [:pointer, :string, :pointer], :pointer
  attach_function :proj_crs_create_projected_3d_crs_from_2d, :proj_crs_create_projected_3D_crs_from_2D, [:pointer, :string, :pointer, :pointer], :pointer
  attach_function :proj_crs_demote_to_2d, :proj_crs_demote_to_2D, [:pointer, :string, :pointer], :pointer
  attach_function :proj_create_engineering_crs, :proj_create_engineering_crs, [:pointer, :string], :pointer
  attach_function :proj_create_vertical_crs, :proj_create_vertical_crs, [:pointer, :string, :string, :string, :double], :pointer
  attach_function :proj_create_vertical_crs_ex, :proj_create_vertical_crs_ex, [:pointer, :string, :string, :string, :string, :string, :double, :string, :string, :string, :pointer, :pointer], :pointer
  attach_function :proj_create_compound_crs, :proj_create_compound_crs, [:pointer, :string, :pointer, :pointer], :pointer
  attach_function :proj_create_conversion, :proj_create_conversion, [:pointer, :string, :string, :string, :string, :string, :string, :int, PJ_PARAM_DESCRIPTION.by_ref], :pointer
  attach_function :proj_create_transformation, :proj_create_transformation, [:pointer, :string, :string, :string, :pointer, :pointer, :pointer, :string, :string, :string, :int, PJ_PARAM_DESCRIPTION.by_ref, :double], :pointer
  attach_function :proj_convert_conversion_to_other_method, :proj_convert_conversion_to_other_method, [:pointer, :pointer, :int, :string], :pointer
  attach_function :proj_create_projected_crs, :proj_create_projected_crs, [:pointer, :string, :pointer, :pointer, :pointer], :pointer
  attach_function :proj_crs_create_bound_crs, :proj_crs_create_bound_crs, [:pointer, :pointer, :pointer, :pointer], :pointer
  attach_function :proj_crs_create_bound_crs_to_wgs84, :proj_crs_create_bound_crs_to_WGS84, [:pointer, :pointer, :pointer], :pointer
  attach_function :proj_crs_create_bound_vertical_crs, :proj_crs_create_bound_vertical_crs, [:pointer, :pointer, :pointer, :string], :pointer
  attach_function :proj_create_conversion_utm, :proj_create_conversion_utm, [:pointer, :int, :int], :pointer
  attach_function :proj_create_conversion_transverse_mercator, :proj_create_conversion_transverse_mercator, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_gauss_schreiber_transverse_mercator, :proj_create_conversion_gauss_schreiber_transverse_mercator, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_transverse_mercator_south_oriented, :proj_create_conversion_transverse_mercator_south_oriented, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_two_point_equidistant, :proj_create_conversion_two_point_equidistant, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_tunisia_mapping_grid, :proj_create_conversion_tunisia_mapping_grid, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_tunisia_mining_grid, :proj_create_conversion_tunisia_mining_grid, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_albers_equal_area, :proj_create_conversion_albers_equal_area, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_lambert_conic_conformal_1sp, :proj_create_conversion_lambert_conic_conformal_1sp, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_lambert_conic_conformal_1sp_variant_b, :proj_create_conversion_lambert_conic_conformal_1sp_variant_b, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_lambert_conic_conformal_2sp, :proj_create_conversion_lambert_conic_conformal_2sp, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_lambert_conic_conformal_2sp_michigan, :proj_create_conversion_lambert_conic_conformal_2sp_michigan, [:pointer, :double, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_lambert_conic_conformal_2sp_belgium, :proj_create_conversion_lambert_conic_conformal_2sp_belgium, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_azimuthal_equidistant, :proj_create_conversion_azimuthal_equidistant, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_guam_projection, :proj_create_conversion_guam_projection, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_bonne, :proj_create_conversion_bonne, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_lambert_cylindrical_equal_area_spherical, :proj_create_conversion_lambert_cylindrical_equal_area_spherical, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_lambert_cylindrical_equal_area, :proj_create_conversion_lambert_cylindrical_equal_area, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_cassini_soldner, :proj_create_conversion_cassini_soldner, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_equidistant_conic, :proj_create_conversion_equidistant_conic, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_eckert_i, :proj_create_conversion_eckert_i, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_eckert_ii, :proj_create_conversion_eckert_ii, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_eckert_iii, :proj_create_conversion_eckert_iii, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_eckert_iv, :proj_create_conversion_eckert_iv, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_eckert_v, :proj_create_conversion_eckert_v, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_eckert_vi, :proj_create_conversion_eckert_vi, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_equidistant_cylindrical, :proj_create_conversion_equidistant_cylindrical, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_equidistant_cylindrical_spherical, :proj_create_conversion_equidistant_cylindrical_spherical, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_gall, :proj_create_conversion_gall, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_goode_homolosine, :proj_create_conversion_goode_homolosine, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_interrupted_goode_homolosine, :proj_create_conversion_interrupted_goode_homolosine, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_geostationary_satellite_sweep_x, :proj_create_conversion_geostationary_satellite_sweep_x, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_geostationary_satellite_sweep_y, :proj_create_conversion_geostationary_satellite_sweep_y, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_gnomonic, :proj_create_conversion_gnomonic, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_hotine_oblique_mercator_variant_a, :proj_create_conversion_hotine_oblique_mercator_variant_a, [:pointer, :double, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_hotine_oblique_mercator_variant_b, :proj_create_conversion_hotine_oblique_mercator_variant_b, [:pointer, :double, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_hotine_oblique_mercator_two_point_natural_origin, :proj_create_conversion_hotine_oblique_mercator_two_point_natural_origin, [:pointer, :double, :double, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_laborde_oblique_mercator, :proj_create_conversion_laborde_oblique_mercator, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_international_map_world_polyconic, :proj_create_conversion_international_map_world_polyconic, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_krovak_north_oriented, :proj_create_conversion_krovak_north_oriented, [:pointer, :double, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_krovak, :proj_create_conversion_krovak, [:pointer, :double, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_lambert_azimuthal_equal_area, :proj_create_conversion_lambert_azimuthal_equal_area, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_miller_cylindrical, :proj_create_conversion_miller_cylindrical, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_mercator_variant_a, :proj_create_conversion_mercator_variant_a, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_mercator_variant_b, :proj_create_conversion_mercator_variant_b, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_popular_visualisation_pseudo_mercator, :proj_create_conversion_popular_visualisation_pseudo_mercator, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_mollweide, :proj_create_conversion_mollweide, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_new_zealand_mapping_grid, :proj_create_conversion_new_zealand_mapping_grid, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_oblique_stereographic, :proj_create_conversion_oblique_stereographic, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_orthographic, :proj_create_conversion_orthographic, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_local_orthographic, :proj_create_conversion_local_orthographic, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_american_polyconic, :proj_create_conversion_american_polyconic, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_polar_stereographic_variant_a, :proj_create_conversion_polar_stereographic_variant_a, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_polar_stereographic_variant_b, :proj_create_conversion_polar_stereographic_variant_b, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_robinson, :proj_create_conversion_robinson, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_sinusoidal, :proj_create_conversion_sinusoidal, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_stereographic, :proj_create_conversion_stereographic, [:pointer, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_van_der_grinten, :proj_create_conversion_van_der_grinten, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_wagner_i, :proj_create_conversion_wagner_i, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_wagner_ii, :proj_create_conversion_wagner_ii, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_wagner_iii, :proj_create_conversion_wagner_iii, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_wagner_iv, :proj_create_conversion_wagner_iv, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_wagner_v, :proj_create_conversion_wagner_v, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_wagner_vi, :proj_create_conversion_wagner_vi, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_wagner_vii, :proj_create_conversion_wagner_vii, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_quadrilateralized_spherical_cube, :proj_create_conversion_quadrilateralized_spherical_cube, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_spherical_cross_track_height, :proj_create_conversion_spherical_cross_track_height, [:pointer, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_equal_earth, :proj_create_conversion_equal_earth, [:pointer, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_vertical_perspective, :proj_create_conversion_vertical_perspective, [:pointer, :double, :double, :double, :double, :double, :double, :string, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_pole_rotation_grib_convention, :proj_create_conversion_pole_rotation_grib_convention, [:pointer, :double, :double, :double, :string, :double], :pointer
  attach_function :proj_create_conversion_pole_rotation_netcdf_cf_convention, :proj_create_conversion_pole_rotation_netcdf_cf_convention, [:pointer, :double, :double, :double, :string, :double], :pointer
end
