# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

FFI::DynamicLibrary::SEARCH_PATH ||= ["c:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin"]

module Rename
  extend FFI::Library

  def self.library_names
    ["rename"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  EllipsoidalCs2DType = enum(
    :CS_2D_LONGITUDE_LATITUDE, 0,
    :CS_2D_LATITUDE_LONGITUDE, 1
  )

  class My3DPoint < FFI::Struct
    layout :x, :double,
           :y, :double,
           :z, :double
  end

  attach_function :create_cs, :create_ellipsoidal_2D_cs, [EllipsoidalCs2DType], My3DPoint.by_ref
end
