# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

module Sqlite3
  extend FFI::Library

  def self.library_names
    ["sqlite3"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  SQLITE_VERSION = "3.45.1"
  SQLITE_VERSION_NUMBER = 3045001
  SQLITE_SOURCE_ID = "2024-01-30 16:01:20 e876e51a0ed5c5b3126f52e532044363a014bc594cfefa87ffb5b82257ccalt1"
  SQLITE_OK = 0
  SQLITE_ERROR = 1
  SQLITE_INTERNAL = 2
  SQLITE_PERM = 3
  SQLITE_ABORT = 4
  SQLITE_BUSY = 5
  SQLITE_LOCKED = 6
  SQLITE_NOMEM = 7
  SQLITE_READONLY = 8
  SQLITE_INTERRUPT = 9
  SQLITE_IOERR = 10
  SQLITE_CORRUPT = 11
  SQLITE_NOTFOUND = 12
  SQLITE_FULL = 13
  SQLITE_CANTOPEN = 14
  SQLITE_PROTOCOL = 15
  SQLITE_EMPTY = 16
  SQLITE_SCHEMA = 17
  SQLITE_TOOBIG = 18
  SQLITE_CONSTRAINT = 19
  SQLITE_MISMATCH = 20
  SQLITE_MISUSE = 21
  SQLITE_NOLFS = 22
  SQLITE_AUTH = 23
  SQLITE_FORMAT = 24
  SQLITE_RANGE = 25
  SQLITE_NOTADB = 26
  SQLITE_NOTICE = 27
  SQLITE_WARNING = 28
  SQLITE_ROW = 100
  SQLITE_DONE = 101
  SQLITE_OPEN_READONLY = 0x00000001
  SQLITE_OPEN_READWRITE = 0x00000002
  SQLITE_OPEN_CREATE = 0x00000004
  SQLITE_OPEN_DELETEONCLOSE = 0x00000008
  SQLITE_OPEN_EXCLUSIVE = 0x00000010
  SQLITE_OPEN_AUTOPROXY = 0x00000020
  SQLITE_OPEN_URI = 0x00000040
  SQLITE_OPEN_MEMORY = 0x00000080
  SQLITE_OPEN_MAIN_DB = 0x00000100
  SQLITE_OPEN_TEMP_DB = 0x00000200
  SQLITE_OPEN_TRANSIENT_DB = 0x00000400
  SQLITE_OPEN_MAIN_JOURNAL = 0x00000800
  SQLITE_OPEN_TEMP_JOURNAL = 0x00001000
  SQLITE_OPEN_SUBJOURNAL = 0x00002000
  SQLITE_OPEN_SUPER_JOURNAL = 0x00004000
  SQLITE_OPEN_NOMUTEX = 0x00008000
  SQLITE_OPEN_FULLMUTEX = 0x00010000
  SQLITE_OPEN_SHAREDCACHE = 0x00020000
  SQLITE_OPEN_PRIVATECACHE = 0x00040000
  SQLITE_OPEN_WAL = 0x00080000
  SQLITE_OPEN_NOFOLLOW = 0x01000000
  SQLITE_OPEN_EXRESCODE = 0x02000000
  SQLITE_OPEN_MASTER_JOURNAL = 0x00004000
  SQLITE_IOCAP_ATOMIC = 0x00000001
  SQLITE_IOCAP_ATOMIC512 = 0x00000002
  SQLITE_IOCAP_ATOMIC1K = 0x00000004
  SQLITE_IOCAP_ATOMIC2K = 0x00000008
  SQLITE_IOCAP_ATOMIC4K = 0x00000010
  SQLITE_IOCAP_ATOMIC8K = 0x00000020
  SQLITE_IOCAP_ATOMIC16K = 0x00000040
  SQLITE_IOCAP_ATOMIC32K = 0x00000080
  SQLITE_IOCAP_ATOMIC64K = 0x00000100
  SQLITE_IOCAP_SAFE_APPEND = 0x00000200
  SQLITE_IOCAP_SEQUENTIAL = 0x00000400
  SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN = 0x00000800
  SQLITE_IOCAP_POWERSAFE_OVERWRITE = 0x00001000
  SQLITE_IOCAP_IMMUTABLE = 0x00002000
  SQLITE_IOCAP_BATCH_ATOMIC = 0x00004000
  SQLITE_LOCK_NONE = 0
  SQLITE_LOCK_SHARED = 1
  SQLITE_LOCK_RESERVED = 2
  SQLITE_LOCK_PENDING = 3
  SQLITE_LOCK_EXCLUSIVE = 4
  SQLITE_SYNC_NORMAL = 0x00002
  SQLITE_SYNC_FULL = 0x00003
  SQLITE_SYNC_DATAONLY = 0x00010
  SQLITE_FCNTL_LOCKSTATE = 1
  SQLITE_FCNTL_GET_LOCKPROXYFILE = 2
  SQLITE_FCNTL_SET_LOCKPROXYFILE = 3
  SQLITE_FCNTL_LAST_ERRNO = 4
  SQLITE_FCNTL_SIZE_HINT = 5
  SQLITE_FCNTL_CHUNK_SIZE = 6
  SQLITE_FCNTL_FILE_POINTER = 7
  SQLITE_FCNTL_SYNC_OMITTED = 8
  SQLITE_FCNTL_WIN32_AV_RETRY = 9
  SQLITE_FCNTL_PERSIST_WAL = 10
  SQLITE_FCNTL_OVERWRITE = 11
  SQLITE_FCNTL_VFSNAME = 12
  SQLITE_FCNTL_POWERSAFE_OVERWRITE = 13
  SQLITE_FCNTL_PRAGMA = 14
  SQLITE_FCNTL_BUSYHANDLER = 15
  SQLITE_FCNTL_TEMPFILENAME = 16
  SQLITE_FCNTL_MMAP_SIZE = 18
  SQLITE_FCNTL_TRACE = 19
  SQLITE_FCNTL_HAS_MOVED = 20
  SQLITE_FCNTL_SYNC = 21
  SQLITE_FCNTL_COMMIT_PHASETWO = 22
  SQLITE_FCNTL_WIN32_SET_HANDLE = 23
  SQLITE_FCNTL_WAL_BLOCK = 24
  SQLITE_FCNTL_ZIPVFS = 25
  SQLITE_FCNTL_RBU = 26
  SQLITE_FCNTL_VFS_POINTER = 27
  SQLITE_FCNTL_JOURNAL_POINTER = 28
  SQLITE_FCNTL_WIN32_GET_HANDLE = 29
  SQLITE_FCNTL_PDB = 30
  SQLITE_FCNTL_BEGIN_ATOMIC_WRITE = 31
  SQLITE_FCNTL_COMMIT_ATOMIC_WRITE = 32
  SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE = 33
  SQLITE_FCNTL_LOCK_TIMEOUT = 34
  SQLITE_FCNTL_DATA_VERSION = 35
  SQLITE_FCNTL_SIZE_LIMIT = 36
  SQLITE_FCNTL_CKPT_DONE = 37
  SQLITE_FCNTL_RESERVE_BYTES = 38
  SQLITE_FCNTL_CKPT_START = 39
  SQLITE_FCNTL_EXTERNAL_READER = 40
  SQLITE_FCNTL_CKSM_FILE = 41
  SQLITE_FCNTL_RESET_CACHE = 42
  SQLITE_ACCESS_EXISTS = 0
  SQLITE_ACCESS_READWRITE = 1
  SQLITE_ACCESS_READ = 2
  SQLITE_SHM_UNLOCK = 1
  SQLITE_SHM_LOCK = 2
  SQLITE_SHM_SHARED = 4
  SQLITE_SHM_EXCLUSIVE = 8
  SQLITE_SHM_NLOCK = 8
  SQLITE_CONFIG_SINGLETHREAD = 1
  SQLITE_CONFIG_MULTITHREAD = 2
  SQLITE_CONFIG_SERIALIZED = 3
  SQLITE_CONFIG_MALLOC = 4
  SQLITE_CONFIG_GETMALLOC = 5
  SQLITE_CONFIG_SCRATCH = 6
  SQLITE_CONFIG_PAGECACHE = 7
  SQLITE_CONFIG_HEAP = 8
  SQLITE_CONFIG_MEMSTATUS = 9
  SQLITE_CONFIG_MUTEX = 10
  SQLITE_CONFIG_GETMUTEX = 11
  SQLITE_CONFIG_LOOKASIDE = 13
  SQLITE_CONFIG_PCACHE = 14
  SQLITE_CONFIG_GETPCACHE = 15
  SQLITE_CONFIG_LOG = 16
  SQLITE_CONFIG_URI = 17
  SQLITE_CONFIG_PCACHE2 = 18
  SQLITE_CONFIG_GETPCACHE2 = 19
  SQLITE_CONFIG_COVERING_INDEX_SCAN = 20
  SQLITE_CONFIG_SQLLOG = 21
  SQLITE_CONFIG_MMAP_SIZE = 22
  SQLITE_CONFIG_WIN32_HEAPSIZE = 23
  SQLITE_CONFIG_PCACHE_HDRSZ = 24
  SQLITE_CONFIG_PMASZ = 25
  SQLITE_CONFIG_STMTJRNL_SPILL = 26
  SQLITE_CONFIG_SMALL_MALLOC = 27
  SQLITE_CONFIG_SORTERREF_SIZE = 28
  SQLITE_CONFIG_MEMDB_MAXSIZE = 29
  SQLITE_DBCONFIG_MAINDBNAME = 1000
  SQLITE_DBCONFIG_LOOKASIDE = 1001
  SQLITE_DBCONFIG_ENABLE_FKEY = 1002
  SQLITE_DBCONFIG_ENABLE_TRIGGER = 1003
  SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004
  SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005
  SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE = 1006
  SQLITE_DBCONFIG_ENABLE_QPSG = 1007
  SQLITE_DBCONFIG_TRIGGER_EQP = 1008
  SQLITE_DBCONFIG_RESET_DATABASE = 1009
  SQLITE_DBCONFIG_DEFENSIVE = 1010
  SQLITE_DBCONFIG_WRITABLE_SCHEMA = 1011
  SQLITE_DBCONFIG_LEGACY_ALTER_TABLE = 1012
  SQLITE_DBCONFIG_DQS_DML = 1013
  SQLITE_DBCONFIG_DQS_DDL = 1014
  SQLITE_DBCONFIG_ENABLE_VIEW = 1015
  SQLITE_DBCONFIG_LEGACY_FILE_FORMAT = 1016
  SQLITE_DBCONFIG_TRUSTED_SCHEMA = 1017
  SQLITE_DBCONFIG_STMT_SCANSTATUS = 1018
  SQLITE_DBCONFIG_REVERSE_SCANORDER = 1019
  SQLITE_DBCONFIG_MAX = 1019
  SQLITE_DENY = 1
  SQLITE_IGNORE = 2
  SQLITE_CREATE_INDEX = 1
  SQLITE_CREATE_TABLE = 2
  SQLITE_CREATE_TEMP_INDEX = 3
  SQLITE_CREATE_TEMP_TABLE = 4
  SQLITE_CREATE_TEMP_TRIGGER = 5
  SQLITE_CREATE_TEMP_VIEW = 6
  SQLITE_CREATE_TRIGGER = 7
  SQLITE_CREATE_VIEW = 8
  SQLITE_DELETE = 9
  SQLITE_DROP_INDEX = 10
  SQLITE_DROP_TABLE = 11
  SQLITE_DROP_TEMP_INDEX = 12
  SQLITE_DROP_TEMP_TABLE = 13
  SQLITE_DROP_TEMP_TRIGGER = 14
  SQLITE_DROP_TEMP_VIEW = 15
  SQLITE_DROP_TRIGGER = 16
  SQLITE_DROP_VIEW = 17
  SQLITE_INSERT = 18
  SQLITE_PRAGMA = 19
  SQLITE_READ = 20
  SQLITE_SELECT = 21
  SQLITE_TRANSACTION = 22
  SQLITE_UPDATE = 23
  SQLITE_ATTACH = 24
  SQLITE_DETACH = 25
  SQLITE_ALTER_TABLE = 26
  SQLITE_REINDEX = 27
  SQLITE_ANALYZE = 28
  SQLITE_CREATE_VTABLE = 29
  SQLITE_DROP_VTABLE = 30
  SQLITE_FUNCTION = 31
  SQLITE_SAVEPOINT = 32
  SQLITE_COPY = 0
  SQLITE_RECURSIVE = 33
  SQLITE_TRACE_STMT = 0x01
  SQLITE_TRACE_PROFILE = 0x02
  SQLITE_TRACE_ROW = 0x04
  SQLITE_TRACE_CLOSE = 0x08
  SQLITE_LIMIT_LENGTH = 0
  SQLITE_LIMIT_SQL_LENGTH = 1
  SQLITE_LIMIT_COLUMN = 2
  SQLITE_LIMIT_EXPR_DEPTH = 3
  SQLITE_LIMIT_COMPOUND_SELECT = 4
  SQLITE_LIMIT_VDBE_OP = 5
  SQLITE_LIMIT_FUNCTION_ARG = 6
  SQLITE_LIMIT_ATTACHED = 7
  SQLITE_LIMIT_LIKE_PATTERN_LENGTH = 8
  SQLITE_LIMIT_VARIABLE_NUMBER = 9
  SQLITE_LIMIT_TRIGGER_DEPTH = 10
  SQLITE_LIMIT_WORKER_THREADS = 11
  SQLITE_PREPARE_PERSISTENT = 0x01
  SQLITE_PREPARE_NORMALIZE = 0x02
  SQLITE_PREPARE_NO_VTAB = 0x04
  SQLITE_INTEGER = 1
  SQLITE_FLOAT = 2
  SQLITE_BLOB = 4
  SQLITE_NULL = 5
  SQLITE_TEXT = 3
  SQLITE3_TEXT = 3
  SQLITE_UTF8 = 1
  SQLITE_UTF16LE = 2
  SQLITE_UTF16BE = 3
  SQLITE_UTF16 = 4
  SQLITE_ANY = 5
  SQLITE_UTF16_ALIGNED = 8
  SQLITE_DETERMINISTIC = 0x000000800
  SQLITE_DIRECTONLY = 0x000080000
  SQLITE_SUBTYPE = 0x000100000
  SQLITE_INNOCUOUS = 0x000200000
  SQLITE_RESULT_SUBTYPE = 0x001000000
  SQLITE_WIN32_DATA_DIRECTORY_TYPE = 1
  SQLITE_WIN32_TEMP_DIRECTORY_TYPE = 2
  SQLITE_TXN_NONE = 0
  SQLITE_TXN_READ = 1
  SQLITE_TXN_WRITE = 2
  SQLITE_INDEX_SCAN_UNIQUE = 1
  SQLITE_INDEX_CONSTRAINT_EQ = 2
  SQLITE_INDEX_CONSTRAINT_GT = 4
  SQLITE_INDEX_CONSTRAINT_LE = 8
  SQLITE_INDEX_CONSTRAINT_LT = 16
  SQLITE_INDEX_CONSTRAINT_GE = 32
  SQLITE_INDEX_CONSTRAINT_MATCH = 64
  SQLITE_INDEX_CONSTRAINT_LIKE = 65
  SQLITE_INDEX_CONSTRAINT_GLOB = 66
  SQLITE_INDEX_CONSTRAINT_REGEXP = 67
  SQLITE_INDEX_CONSTRAINT_NE = 68
  SQLITE_INDEX_CONSTRAINT_ISNOT = 69
  SQLITE_INDEX_CONSTRAINT_ISNOTNULL = 70
  SQLITE_INDEX_CONSTRAINT_ISNULL = 71
  SQLITE_INDEX_CONSTRAINT_IS = 72
  SQLITE_INDEX_CONSTRAINT_LIMIT = 73
  SQLITE_INDEX_CONSTRAINT_OFFSET = 74
  SQLITE_INDEX_CONSTRAINT_FUNCTION = 150
  SQLITE_MUTEX_FAST = 0
  SQLITE_MUTEX_RECURSIVE = 1
  SQLITE_MUTEX_STATIC_MAIN = 2
  SQLITE_MUTEX_STATIC_MEM = 3
  SQLITE_MUTEX_STATIC_MEM2 = 4
  SQLITE_MUTEX_STATIC_OPEN = 4
  SQLITE_MUTEX_STATIC_PRNG = 5
  SQLITE_MUTEX_STATIC_LRU = 6
  SQLITE_MUTEX_STATIC_LRU2 = 7
  SQLITE_MUTEX_STATIC_PMEM = 7
  SQLITE_MUTEX_STATIC_APP1 = 8
  SQLITE_MUTEX_STATIC_APP2 = 9
  SQLITE_MUTEX_STATIC_APP3 = 10
  SQLITE_MUTEX_STATIC_VFS1 = 11
  SQLITE_MUTEX_STATIC_VFS2 = 12
  SQLITE_MUTEX_STATIC_VFS3 = 13
  SQLITE_MUTEX_STATIC_MASTER = 2
  SQLITE_TESTCTRL_FIRST = 5
  SQLITE_TESTCTRL_PRNG_SAVE = 5
  SQLITE_TESTCTRL_PRNG_RESTORE = 6
  SQLITE_TESTCTRL_PRNG_RESET = 7
  SQLITE_TESTCTRL_FK_NO_ACTION = 7
  SQLITE_TESTCTRL_BITVEC_TEST = 8
  SQLITE_TESTCTRL_FAULT_INSTALL = 9
  SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS = 10
  SQLITE_TESTCTRL_PENDING_BYTE = 11
  SQLITE_TESTCTRL_ASSERT = 12
  SQLITE_TESTCTRL_ALWAYS = 13
  SQLITE_TESTCTRL_RESERVE = 14
  SQLITE_TESTCTRL_JSON_SELFCHECK = 14
  SQLITE_TESTCTRL_OPTIMIZATIONS = 15
  SQLITE_TESTCTRL_ISKEYWORD = 16
  SQLITE_TESTCTRL_SCRATCHMALLOC = 17
  SQLITE_TESTCTRL_INTERNAL_FUNCTIONS = 17
  SQLITE_TESTCTRL_LOCALTIME_FAULT = 18
  SQLITE_TESTCTRL_EXPLAIN_STMT = 19
  SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD = 19
  SQLITE_TESTCTRL_NEVER_CORRUPT = 20
  SQLITE_TESTCTRL_VDBE_COVERAGE = 21
  SQLITE_TESTCTRL_BYTEORDER = 22
  SQLITE_TESTCTRL_ISINIT = 23
  SQLITE_TESTCTRL_SORTER_MMAP = 24
  SQLITE_TESTCTRL_IMPOSTER = 25
  SQLITE_TESTCTRL_PARSER_COVERAGE = 26
  SQLITE_TESTCTRL_RESULT_INTREAL = 27
  SQLITE_TESTCTRL_PRNG_SEED = 28
  SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS = 29
  SQLITE_TESTCTRL_SEEK_COUNT = 30
  SQLITE_TESTCTRL_TRACEFLAGS = 31
  SQLITE_TESTCTRL_TUNE = 32
  SQLITE_TESTCTRL_LOGEST = 33
  SQLITE_TESTCTRL_USELONGDOUBLE = 34
  SQLITE_TESTCTRL_LAST = 34
  SQLITE_STATUS_MEMORY_USED = 0
  SQLITE_STATUS_PAGECACHE_USED = 1
  SQLITE_STATUS_PAGECACHE_OVERFLOW = 2
  SQLITE_STATUS_SCRATCH_USED = 3
  SQLITE_STATUS_SCRATCH_OVERFLOW = 4
  SQLITE_STATUS_MALLOC_SIZE = 5
  SQLITE_STATUS_PARSER_STACK = 6
  SQLITE_STATUS_PAGECACHE_SIZE = 7
  SQLITE_STATUS_SCRATCH_SIZE = 8
  SQLITE_STATUS_MALLOC_COUNT = 9
  SQLITE_DBSTATUS_LOOKASIDE_USED = 0
  SQLITE_DBSTATUS_CACHE_USED = 1
  SQLITE_DBSTATUS_SCHEMA_USED = 2
  SQLITE_DBSTATUS_STMT_USED = 3
  SQLITE_DBSTATUS_LOOKASIDE_HIT = 4
  SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE = 5
  SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL = 6
  SQLITE_DBSTATUS_CACHE_HIT = 7
  SQLITE_DBSTATUS_CACHE_MISS = 8
  SQLITE_DBSTATUS_CACHE_WRITE = 9
  SQLITE_DBSTATUS_DEFERRED_FKS = 10
  SQLITE_DBSTATUS_CACHE_USED_SHARED = 11
  SQLITE_DBSTATUS_CACHE_SPILL = 12
  SQLITE_DBSTATUS_MAX = 12
  SQLITE_STMTSTATUS_FULLSCAN_STEP = 1
  SQLITE_STMTSTATUS_SORT = 2
  SQLITE_STMTSTATUS_AUTOINDEX = 3
  SQLITE_STMTSTATUS_VM_STEP = 4
  SQLITE_STMTSTATUS_REPREPARE = 5
  SQLITE_STMTSTATUS_RUN = 6
  SQLITE_STMTSTATUS_FILTER_MISS = 7
  SQLITE_STMTSTATUS_FILTER_HIT = 8
  SQLITE_STMTSTATUS_MEMUSED = 99
  SQLITE_CHECKPOINT_PASSIVE = 0
  SQLITE_CHECKPOINT_FULL = 1
  SQLITE_CHECKPOINT_RESTART = 2
  SQLITE_CHECKPOINT_TRUNCATE = 3
  SQLITE_VTAB_CONSTRAINT_SUPPORT = 1
  SQLITE_VTAB_INNOCUOUS = 2
  SQLITE_VTAB_DIRECTONLY = 3
  SQLITE_VTAB_USES_ALL_SCHEMAS = 4
  SQLITE_ROLLBACK = 1
  SQLITE_FAIL = 3
  SQLITE_REPLACE = 5
  SQLITE_SCANSTAT_NLOOP = 0
  SQLITE_SCANSTAT_NVISIT = 1
  SQLITE_SCANSTAT_EST = 2
  SQLITE_SCANSTAT_NAME = 3
  SQLITE_SCANSTAT_EXPLAIN = 4
  SQLITE_SCANSTAT_SELECTID = 5
  SQLITE_SCANSTAT_PARENTID = 6
  SQLITE_SCANSTAT_NCYCLE = 7
  SQLITE_SCANSTAT_COMPLEX = 0x0001
  SQLITE_SERIALIZE_NOCOPY = 0x001
  SQLITE_DESERIALIZE_FREEONCLOSE = 1
  SQLITE_DESERIALIZE_RESIZEABLE = 2
  SQLITE_DESERIALIZE_READONLY = 4
  NOT_WITHIN = 0
  PARTLY_WITHIN = 1
  FULLY_WITHIN = 2
  FTS5_TOKENIZE_QUERY = 0x0001
  FTS5_TOKENIZE_PREFIX = 0x0002
  FTS5_TOKENIZE_DOCUMENT = 0x0004
  FTS5_TOKENIZE_AUX = 0x0008
  FTS5_TOKEN_COLOCATED = 0x0001
  attach_variable :Sqlite3Version, :sqlite3_version, :string
  attach_function :sqlite3_libversion, :sqlite3_libversion, [], :string
  attach_function :sqlite3_sourceid, :sqlite3_sourceid, [], :string
  attach_function :sqlite3_libversion_number, :sqlite3_libversion_number, [], :int
  attach_function :sqlite3_compileoption_used, :sqlite3_compileoption_used, [:string], :int
  attach_function :sqlite3_compileoption_get, :sqlite3_compileoption_get, [:int], :string
  attach_function :sqlite3_threadsafe, :sqlite3_threadsafe, [], :int
  typedef :pointer, :Sqlite3
  typedef :long_long, :sqlite_int64
  typedef :ulong_long, :sqlite_uint64
  typedef :long_long, :sqlite_int64
  typedef :ulong_long, :sqlite_uint64
  attach_function :sqlite3_close, :sqlite3_close, [:pointer], :int
  attach_function :sqlite3_close_v2, :sqlite3_close_v2, [:pointer], :int
  callback :sqlite3_callback, [], :int
  callback :sqlite3_exec_callback_callback, [:pointer, :int, :pointer, :pointer], :int
  attach_function :sqlite3_exec, :sqlite3_exec, [:pointer, :string, :sqlite3_exec_callback_callback, :pointer, :pointer], :int

  class Sqlite3File < FFI::Struct
    layout :p_methods, :pointer
  end

  callback :sqlite3_io_methods_xClose_callback, [:pointer], :int
  callback :sqlite3_io_methods_xRead_callback, [:pointer, :pointer, :int, :long_long], :int
  callback :sqlite3_io_methods_xWrite_callback, [:pointer, :pointer, :int, :long_long], :int
  callback :sqlite3_io_methods_xTruncate_callback, [:pointer, :long_long], :int
  callback :sqlite3_io_methods_xSync_callback, [:pointer, :int], :int
  callback :sqlite3_io_methods_xFileSize_callback, [:pointer, :pointer], :int
  callback :sqlite3_io_methods_xLock_callback, [:pointer, :int], :int
  callback :sqlite3_io_methods_xUnlock_callback, [:pointer, :int], :int
  callback :sqlite3_io_methods_xCheckReservedLock_callback, [:pointer, :pointer], :int
  callback :sqlite3_io_methods_xFileControl_callback, [:pointer, :int, :pointer], :int
  callback :sqlite3_io_methods_xSectorSize_callback, [:pointer], :int
  callback :sqlite3_io_methods_xDeviceCharacteristics_callback, [:pointer], :int
  callback :sqlite3_io_methods_xShmMap_callback, [:pointer, :int, :int, :int, :pointer], :int
  callback :sqlite3_io_methods_xShmLock_callback, [:pointer, :int, :int, :int], :int
  callback :sqlite3_io_methods_xShmBarrier_callback, [:pointer], :void
  callback :sqlite3_io_methods_xShmUnmap_callback, [:pointer, :int], :int
  callback :sqlite3_io_methods_xFetch_callback, [:pointer, :long_long, :int, :pointer], :int
  callback :sqlite3_io_methods_xUnfetch_callback, [:pointer, :long_long, :pointer], :int

  class Sqlite3IoMethods < FFI::Struct
    layout :i_version, :int,
           :x_close, :sqlite3_io_methods_xClose_callback,
           :x_read, :sqlite3_io_methods_xRead_callback,
           :x_write, :sqlite3_io_methods_xWrite_callback,
           :x_truncate, :sqlite3_io_methods_xTruncate_callback,
           :x_sync, :sqlite3_io_methods_xSync_callback,
           :x_file_size, :sqlite3_io_methods_xFileSize_callback,
           :x_lock, :sqlite3_io_methods_xLock_callback,
           :x_unlock, :sqlite3_io_methods_xUnlock_callback,
           :x_check_reserved_lock, :sqlite3_io_methods_xCheckReservedLock_callback,
           :x_file_control, :sqlite3_io_methods_xFileControl_callback,
           :x_sector_size, :sqlite3_io_methods_xSectorSize_callback,
           :x_device_characteristics, :sqlite3_io_methods_xDeviceCharacteristics_callback,
           :x_shm_map, :sqlite3_io_methods_xShmMap_callback,
           :x_shm_lock, :sqlite3_io_methods_xShmLock_callback,
           :x_shm_barrier, :sqlite3_io_methods_xShmBarrier_callback,
           :x_shm_unmap, :sqlite3_io_methods_xShmUnmap_callback,
           :x_fetch, :sqlite3_io_methods_xFetch_callback,
           :x_unfetch, :sqlite3_io_methods_xUnfetch_callback
  end

  typedef :pointer, :Sqlite3Mutex
  typedef :pointer, :Sqlite3ApiRoutines
  typedef :string, :sqlite3_filename
  callback :sqlite3_syscall_ptr, [], :void
  callback :sqlite3_vfs_xOpen_callback, [:pointer, :string, :pointer, :int, :pointer], :int
  callback :sqlite3_vfs_xDelete_callback, [:pointer, :string, :int], :int
  callback :sqlite3_vfs_xAccess_callback, [:pointer, :string, :int, :pointer], :int
  callback :sqlite3_vfs_xFullPathname_callback, [:pointer, :string, :int, :pointer], :int
  callback :sqlite3_vfs_xDlOpen_callback, [:pointer, :string], :pointer
  callback :sqlite3_vfs_xDlError_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_vfs_xDlSym_callback, [:pointer, :pointer, :string], :pointer
  callback :sqlite3_vfs_xDlClose_callback, [:pointer, :pointer], :void
  callback :sqlite3_vfs_xRandomness_callback, [:pointer, :int, :pointer], :int
  callback :sqlite3_vfs_xSleep_callback, [:pointer, :int], :int
  callback :sqlite3_vfs_xCurrentTime_callback, [:pointer, :pointer], :int
  callback :sqlite3_vfs_xGetLastError_callback, [:pointer, :int, :pointer], :int
  callback :sqlite3_vfs_xCurrentTimeInt64_callback, [:pointer, :pointer], :int
  callback :sqlite3_vfs_xSetSystemCall_callback, [:pointer, :string, :pointer], :int
  callback :sqlite3_vfs_xGetSystemCall_callback, [:pointer, :string], :pointer
  callback :sqlite3_vfs_xNextSystemCall_callback, [:pointer, :string], :pointer

  class Sqlite3Vfs < FFI::Struct
    layout :i_version, :int,
           :sz_os_file, :int,
           :mx_pathname, :int,
           :p_next, :pointer,
           :z_name, :string,
           :p_app_data, :pointer,
           :x_open, :sqlite3_vfs_xOpen_callback,
           :x_delete, :sqlite3_vfs_xDelete_callback,
           :x_access, :sqlite3_vfs_xAccess_callback,
           :x_full_pathname, :sqlite3_vfs_xFullPathname_callback,
           :x_dl_open, :sqlite3_vfs_xDlOpen_callback,
           :x_dl_error, :sqlite3_vfs_xDlError_callback,
           :x_dl_sym, :sqlite3_vfs_xDlSym_callback,
           :x_dl_close, :sqlite3_vfs_xDlClose_callback,
           :x_randomness, :sqlite3_vfs_xRandomness_callback,
           :x_sleep, :sqlite3_vfs_xSleep_callback,
           :x_current_time, :sqlite3_vfs_xCurrentTime_callback,
           :x_get_last_error, :sqlite3_vfs_xGetLastError_callback,
           :x_current_time_int64, :sqlite3_vfs_xCurrentTimeInt64_callback,
           :x_set_system_call, :sqlite3_vfs_xSetSystemCall_callback,
           :x_get_system_call, :sqlite3_vfs_xGetSystemCall_callback,
           :x_next_system_call, :sqlite3_vfs_xNextSystemCall_callback
  end

  attach_function :sqlite3_initialize, :sqlite3_initialize, [], :int
  attach_function :sqlite3_shutdown, :sqlite3_shutdown, [], :int
  attach_function :sqlite3_os_init, :sqlite3_os_init, [], :int
  attach_function :sqlite3_os_end, :sqlite3_os_end, [], :int
  attach_function :sqlite3_config, :sqlite3_config, [:int], :int
  attach_function :sqlite3_db_config, :sqlite3_db_config, [:pointer, :int], :int
  callback :sqlite3_mem_methods_xMalloc_callback, [:int], :pointer
  callback :sqlite3_mem_methods_xFree_callback, [:pointer], :void
  callback :sqlite3_mem_methods_xRealloc_callback, [:pointer, :int], :pointer
  callback :sqlite3_mem_methods_xSize_callback, [:pointer], :int
  callback :sqlite3_mem_methods_xRoundup_callback, [:int], :int
  callback :sqlite3_mem_methods_xInit_callback, [:pointer], :int
  callback :sqlite3_mem_methods_xShutdown_callback, [:pointer], :void

  class Sqlite3MemMethods < FFI::Struct
    layout :x_malloc, :sqlite3_mem_methods_xMalloc_callback,
           :x_free, :sqlite3_mem_methods_xFree_callback,
           :x_realloc, :sqlite3_mem_methods_xRealloc_callback,
           :x_size, :sqlite3_mem_methods_xSize_callback,
           :x_roundup, :sqlite3_mem_methods_xRoundup_callback,
           :x_init, :sqlite3_mem_methods_xInit_callback,
           :x_shutdown, :sqlite3_mem_methods_xShutdown_callback,
           :p_app_data, :pointer
  end

  attach_function :sqlite3_extended_result_codes, :sqlite3_extended_result_codes, [:pointer, :int], :int
  attach_function :sqlite3_last_insert_rowid, :sqlite3_last_insert_rowid, [:pointer], :long_long
  attach_function :sqlite3_set_last_insert_rowid, :sqlite3_set_last_insert_rowid, [:pointer, :long_long], :void
  attach_function :sqlite3_changes, :sqlite3_changes, [:pointer], :int
  attach_function :sqlite3_changes64, :sqlite3_changes64, [:pointer], :long_long
  attach_function :sqlite3_total_changes, :sqlite3_total_changes, [:pointer], :int
  attach_function :sqlite3_total_changes64, :sqlite3_total_changes64, [:pointer], :long_long
  attach_function :sqlite3_interrupt, :sqlite3_interrupt, [:pointer], :void
  attach_function :sqlite3_is_interrupted, :sqlite3_is_interrupted, [:pointer], :int
  attach_function :sqlite3_complete, :sqlite3_complete, [:string], :int
  attach_function :sqlite3_complete16, :sqlite3_complete16, [:pointer], :int
  callback :sqlite3_busy_handler__callback, [:pointer, :int], :int
  attach_function :sqlite3_busy_handler, :sqlite3_busy_handler, [:pointer, :sqlite3_busy_handler__callback, :pointer], :int
  attach_function :sqlite3_busy_timeout, :sqlite3_busy_timeout, [:pointer, :int], :int
  attach_function :sqlite3_get_table, :sqlite3_get_table, [:pointer, :string, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :sqlite3_free_table, :sqlite3_free_table, [:pointer], :void
  attach_function :sqlite3_mprintf, :sqlite3_mprintf, [:string], :pointer
  attach_function :sqlite3_vmprintf, :sqlite3_vmprintf, [:string, :varargs], :pointer
  attach_function :sqlite3_snprintf, :sqlite3_snprintf, [:int, :pointer, :string], :pointer
  attach_function :sqlite3_vsnprintf, :sqlite3_vsnprintf, [:int, :pointer, :string, :varargs], :pointer
  attach_function :sqlite3_malloc, :sqlite3_malloc, [:int], :pointer
  attach_function :sqlite3_malloc64, :sqlite3_malloc64, [:ulong_long], :pointer
  attach_function :sqlite3_realloc, :sqlite3_realloc, [:pointer, :int], :pointer
  attach_function :sqlite3_realloc64, :sqlite3_realloc64, [:pointer, :ulong_long], :pointer
  attach_function :sqlite3_free, :sqlite3_free, [:pointer], :void
  attach_function :sqlite3_msize, :sqlite3_msize, [:pointer], :ulong_long
  attach_function :sqlite3_memory_used, :sqlite3_memory_used, [], :long_long
  attach_function :sqlite3_memory_highwater, :sqlite3_memory_highwater, [:int], :long_long
  attach_function :sqlite3_randomness, :sqlite3_randomness, [:int, :pointer], :void
  callback :sqlite3_set_authorizer_xAuth_callback, [:pointer, :int, :string, :string, :string, :string], :int
  attach_function :sqlite3_set_authorizer, :sqlite3_set_authorizer, [:pointer, :sqlite3_set_authorizer_xAuth_callback, :pointer], :int
  callback :sqlite3_trace_xTrace_callback, [:pointer, :string], :void
  attach_function :sqlite3_trace, :sqlite3_trace, [:pointer, :sqlite3_trace_xTrace_callback, :pointer], :pointer
  callback :sqlite3_profile_xProfile_callback, [:pointer, :string, :ulong_long], :void
  attach_function :sqlite3_profile, :sqlite3_profile, [:pointer, :sqlite3_profile_xProfile_callback, :pointer], :pointer
  callback :sqlite3_trace_v2_xCallback_callback, [:uint, :pointer, :pointer, :pointer], :int
  attach_function :sqlite3_trace_v2, :sqlite3_trace_v2, [:pointer, :uint, :sqlite3_trace_v2_xCallback_callback, :pointer], :int
  callback :sqlite3_progress_handler__callback, [:pointer], :int
  attach_function :sqlite3_progress_handler, :sqlite3_progress_handler, [:pointer, :int, :sqlite3_progress_handler__callback, :pointer], :void
  attach_function :sqlite3_open, :sqlite3_open, [:string, :pointer], :int
  attach_function :sqlite3_open16, :sqlite3_open16, [:pointer, :pointer], :int
  attach_function :sqlite3_open_v2, :sqlite3_open_v2, [:string, :pointer, :int, :string], :int
  attach_function :sqlite3_uri_parameter, :sqlite3_uri_parameter, [:string, :string], :string
  attach_function :sqlite3_uri_boolean, :sqlite3_uri_boolean, [:string, :string, :int], :int
  attach_function :sqlite3_uri_int64, :sqlite3_uri_int64, [:string, :string, :long_long], :long_long
  attach_function :sqlite3_uri_key, :sqlite3_uri_key, [:string, :int], :string
  attach_function :sqlite3_filename_database, :sqlite3_filename_database, [:string], :string
  attach_function :sqlite3_filename_journal, :sqlite3_filename_journal, [:string], :string
  attach_function :sqlite3_filename_wal, :sqlite3_filename_wal, [:string], :string
  attach_function :sqlite3_database_file_object, :sqlite3_database_file_object, [:string], Sqlite3File.by_ref
  attach_function :sqlite3_create_filename, :sqlite3_create_filename, [:string, :string, :string, :int, :pointer], :string
  attach_function :sqlite3_free_filename, :sqlite3_free_filename, [:string], :void
  attach_function :sqlite3_errcode, :sqlite3_errcode, [:pointer], :int
  attach_function :sqlite3_extended_errcode, :sqlite3_extended_errcode, [:pointer], :int
  attach_function :sqlite3_errmsg, :sqlite3_errmsg, [:pointer], :string
  attach_function :sqlite3_errmsg16, :sqlite3_errmsg16, [:pointer], :pointer
  attach_function :sqlite3_errstr, :sqlite3_errstr, [:int], :string
  attach_function :sqlite3_error_offset, :sqlite3_error_offset, [:pointer], :int
  typedef :pointer, :Sqlite3Stmt
  attach_function :sqlite3_limit, :sqlite3_limit, [:pointer, :int, :int], :int
  attach_function :sqlite3_prepare, :sqlite3_prepare, [:pointer, :string, :int, :pointer, :pointer], :int
  attach_function :sqlite3_prepare_v2, :sqlite3_prepare_v2, [:pointer, :string, :int, :pointer, :pointer], :int
  attach_function :sqlite3_prepare_v3, :sqlite3_prepare_v3, [:pointer, :string, :int, :uint, :pointer, :pointer], :int
  attach_function :sqlite3_prepare16, :sqlite3_prepare16, [:pointer, :pointer, :int, :pointer, :pointer], :int
  attach_function :sqlite3_prepare16_v2, :sqlite3_prepare16_v2, [:pointer, :pointer, :int, :pointer, :pointer], :int
  attach_function :sqlite3_prepare16_v3, :sqlite3_prepare16_v3, [:pointer, :pointer, :int, :uint, :pointer, :pointer], :int
  attach_function :sqlite3_sql, :sqlite3_sql, [:pointer], :string
  attach_function :sqlite3_expanded_sql, :sqlite3_expanded_sql, [:pointer], :pointer
  attach_function :sqlite3_stmt_readonly, :sqlite3_stmt_readonly, [:pointer], :int
  attach_function :sqlite3_stmt_isexplain, :sqlite3_stmt_isexplain, [:pointer], :int
  attach_function :sqlite3_stmt_explain, :sqlite3_stmt_explain, [:pointer, :int], :int
  attach_function :sqlite3_stmt_busy, :sqlite3_stmt_busy, [:pointer], :int
  typedef :pointer, :Sqlite3Value
  typedef :pointer, :Sqlite3Context
  callback :sqlite3_bind_blob__callback, [:pointer], :void
  attach_function :sqlite3_bind_blob, :sqlite3_bind_blob, [:pointer, :int, :pointer, :int, :sqlite3_bind_blob__callback], :int
  callback :sqlite3_bind_blob64__callback, [:pointer], :void
  attach_function :sqlite3_bind_blob64, :sqlite3_bind_blob64, [:pointer, :int, :pointer, :ulong_long, :sqlite3_bind_blob64__callback], :int
  attach_function :sqlite3_bind_double, :sqlite3_bind_double, [:pointer, :int, :double], :int
  attach_function :sqlite3_bind_int, :sqlite3_bind_int, [:pointer, :int, :int], :int
  attach_function :sqlite3_bind_int64, :sqlite3_bind_int64, [:pointer, :int, :long_long], :int
  attach_function :sqlite3_bind_null, :sqlite3_bind_null, [:pointer, :int], :int
  callback :sqlite3_bind_text__callback, [:pointer], :void
  attach_function :sqlite3_bind_text, :sqlite3_bind_text, [:pointer, :int, :string, :int, :sqlite3_bind_text__callback], :int
  callback :sqlite3_bind_text16__callback, [:pointer], :void
  attach_function :sqlite3_bind_text16, :sqlite3_bind_text16, [:pointer, :int, :pointer, :int, :sqlite3_bind_text16__callback], :int
  callback :sqlite3_bind_text64__callback, [:pointer], :void
  attach_function :sqlite3_bind_text64, :sqlite3_bind_text64, [:pointer, :int, :string, :ulong_long, :sqlite3_bind_text64__callback, :uchar], :int
  attach_function :sqlite3_bind_value, :sqlite3_bind_value, [:pointer, :int, :pointer], :int
  callback :sqlite3_bind_pointer__callback, [:pointer], :void
  attach_function :sqlite3_bind_pointer, :sqlite3_bind_pointer, [:pointer, :int, :pointer, :string, :sqlite3_bind_pointer__callback], :int
  attach_function :sqlite3_bind_zeroblob, :sqlite3_bind_zeroblob, [:pointer, :int, :int], :int
  attach_function :sqlite3_bind_zeroblob64, :sqlite3_bind_zeroblob64, [:pointer, :int, :ulong_long], :int
  attach_function :sqlite3_bind_parameter_count, :sqlite3_bind_parameter_count, [:pointer], :int
  attach_function :sqlite3_bind_parameter_name, :sqlite3_bind_parameter_name, [:pointer, :int], :string
  attach_function :sqlite3_bind_parameter_index, :sqlite3_bind_parameter_index, [:pointer, :string], :int
  attach_function :sqlite3_clear_bindings, :sqlite3_clear_bindings, [:pointer], :int
  attach_function :sqlite3_column_count, :sqlite3_column_count, [:pointer], :int
  attach_function :sqlite3_column_name, :sqlite3_column_name, [:pointer, :int], :string
  attach_function :sqlite3_column_name16, :sqlite3_column_name16, [:pointer, :int], :pointer
  attach_function :sqlite3_column_database_name, :sqlite3_column_database_name, [:pointer, :int], :string
  attach_function :sqlite3_column_database_name16, :sqlite3_column_database_name16, [:pointer, :int], :pointer
  attach_function :sqlite3_column_table_name, :sqlite3_column_table_name, [:pointer, :int], :string
  attach_function :sqlite3_column_table_name16, :sqlite3_column_table_name16, [:pointer, :int], :pointer
  attach_function :sqlite3_column_origin_name, :sqlite3_column_origin_name, [:pointer, :int], :string
  attach_function :sqlite3_column_origin_name16, :sqlite3_column_origin_name16, [:pointer, :int], :pointer
  attach_function :sqlite3_column_decltype, :sqlite3_column_decltype, [:pointer, :int], :string
  attach_function :sqlite3_column_decltype16, :sqlite3_column_decltype16, [:pointer, :int], :pointer
  attach_function :sqlite3_step, :sqlite3_step, [:pointer], :int
  attach_function :sqlite3_data_count, :sqlite3_data_count, [:pointer], :int
  attach_function :sqlite3_column_blob, :sqlite3_column_blob, [:pointer, :int], :pointer
  attach_function :sqlite3_column_double, :sqlite3_column_double, [:pointer, :int], :double
  attach_function :sqlite3_column_int, :sqlite3_column_int, [:pointer, :int], :int
  attach_function :sqlite3_column_int64, :sqlite3_column_int64, [:pointer, :int], :long_long
  attach_function :sqlite3_column_text, :sqlite3_column_text, [:pointer, :int], :pointer
  attach_function :sqlite3_column_text16, :sqlite3_column_text16, [:pointer, :int], :pointer
  attach_function :sqlite3_column_value, :sqlite3_column_value, [:pointer, :int], :pointer
  attach_function :sqlite3_column_bytes, :sqlite3_column_bytes, [:pointer, :int], :int
  attach_function :sqlite3_column_bytes16, :sqlite3_column_bytes16, [:pointer, :int], :int
  attach_function :sqlite3_column_type, :sqlite3_column_type, [:pointer, :int], :int
  attach_function :sqlite3_finalize, :sqlite3_finalize, [:pointer], :int
  attach_function :sqlite3_reset, :sqlite3_reset, [:pointer], :int
  callback :sqlite3_create_function_xFunc_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function_xStep_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function_xFinal_callback, [:pointer], :void
  attach_function :sqlite3_create_function, :sqlite3_create_function, [:pointer, :string, :int, :int, :pointer, :sqlite3_create_function_xFunc_callback, :sqlite3_create_function_xStep_callback, :sqlite3_create_function_xFinal_callback], :int
  callback :sqlite3_create_function16_xFunc_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function16_xStep_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function16_xFinal_callback, [:pointer], :void
  attach_function :sqlite3_create_function16, :sqlite3_create_function16, [:pointer, :pointer, :int, :int, :pointer, :sqlite3_create_function16_xFunc_callback, :sqlite3_create_function16_xStep_callback, :sqlite3_create_function16_xFinal_callback], :int
  callback :sqlite3_create_function_v2_xFunc_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function_v2_xStep_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function_v2_xFinal_callback, [:pointer], :void
  callback :sqlite3_create_function_v2_xDestroy_callback, [:pointer], :void
  attach_function :sqlite3_create_function_v2, :sqlite3_create_function_v2, [:pointer, :string, :int, :int, :pointer, :sqlite3_create_function_v2_xFunc_callback, :sqlite3_create_function_v2_xStep_callback, :sqlite3_create_function_v2_xFinal_callback, :sqlite3_create_function_v2_xDestroy_callback], :int
  callback :sqlite3_create_window_function_xStep_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_window_function_xFinal_callback, [:pointer], :void
  callback :sqlite3_create_window_function_xValue_callback, [:pointer], :void
  callback :sqlite3_create_window_function_xInverse_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_window_function_xDestroy_callback, [:pointer], :void
  attach_function :sqlite3_create_window_function, :sqlite3_create_window_function, [:pointer, :string, :int, :int, :pointer, :sqlite3_create_window_function_xStep_callback, :sqlite3_create_window_function_xFinal_callback, :sqlite3_create_window_function_xValue_callback, :sqlite3_create_window_function_xInverse_callback, :sqlite3_create_window_function_xDestroy_callback], :int
  attach_function :sqlite3_aggregate_count, :sqlite3_aggregate_count, [:pointer], :int
  attach_function :sqlite3_expired, :sqlite3_expired, [:pointer], :int
  attach_function :sqlite3_transfer_bindings, :sqlite3_transfer_bindings, [:pointer, :pointer], :int
  attach_function :sqlite3_global_recover, :sqlite3_global_recover, [], :int
  attach_function :sqlite3_thread_cleanup, :sqlite3_thread_cleanup, [], :void
  callback :sqlite3_memory_alarm__callback, [:pointer, :long_long, :int], :void
  attach_function :sqlite3_memory_alarm, :sqlite3_memory_alarm, [:sqlite3_memory_alarm__callback, :pointer, :long_long], :int
  attach_function :sqlite3_value_blob, :sqlite3_value_blob, [:pointer], :pointer
  attach_function :sqlite3_value_double, :sqlite3_value_double, [:pointer], :double
  attach_function :sqlite3_value_int, :sqlite3_value_int, [:pointer], :int
  attach_function :sqlite3_value_int64, :sqlite3_value_int64, [:pointer], :long_long
  attach_function :sqlite3_value_pointer, :sqlite3_value_pointer, [:pointer, :string], :pointer
  attach_function :sqlite3_value_text, :sqlite3_value_text, [:pointer], :pointer
  attach_function :sqlite3_value_text16, :sqlite3_value_text16, [:pointer], :pointer
  attach_function :sqlite3_value_text16le, :sqlite3_value_text16le, [:pointer], :pointer
  attach_function :sqlite3_value_text16be, :sqlite3_value_text16be, [:pointer], :pointer
  attach_function :sqlite3_value_bytes, :sqlite3_value_bytes, [:pointer], :int
  attach_function :sqlite3_value_bytes16, :sqlite3_value_bytes16, [:pointer], :int
  attach_function :sqlite3_value_type, :sqlite3_value_type, [:pointer], :int
  attach_function :sqlite3_value_numeric_type, :sqlite3_value_numeric_type, [:pointer], :int
  attach_function :sqlite3_value_nochange, :sqlite3_value_nochange, [:pointer], :int
  attach_function :sqlite3_value_frombind, :sqlite3_value_frombind, [:pointer], :int
  attach_function :sqlite3_value_encoding, :sqlite3_value_encoding, [:pointer], :int
  attach_function :sqlite3_value_subtype, :sqlite3_value_subtype, [:pointer], :uint
  attach_function :sqlite3_value_dup, :sqlite3_value_dup, [:pointer], :pointer
  attach_function :sqlite3_value_free, :sqlite3_value_free, [:pointer], :void
  attach_function :sqlite3_aggregate_context, :sqlite3_aggregate_context, [:pointer, :int], :pointer
  attach_function :sqlite3_user_data, :sqlite3_user_data, [:pointer], :pointer
  attach_function :sqlite3_context_db_handle, :sqlite3_context_db_handle, [:pointer], :pointer
  attach_function :sqlite3_get_auxdata, :sqlite3_get_auxdata, [:pointer, :int], :pointer
  callback :sqlite3_set_auxdata__callback, [:pointer], :void
  attach_function :sqlite3_set_auxdata, :sqlite3_set_auxdata, [:pointer, :int, :pointer, :sqlite3_set_auxdata__callback], :void
  attach_function :sqlite3_get_clientdata, :sqlite3_get_clientdata, [:pointer, :string], :pointer
  callback :sqlite3_set_clientdata__callback, [:pointer], :void
  attach_function :sqlite3_set_clientdata, :sqlite3_set_clientdata, [:pointer, :string, :pointer, :sqlite3_set_clientdata__callback], :int
  callback :sqlite3_destructor_type, [], :void
  callback :sqlite3_result_blob__callback, [:pointer], :void
  attach_function :sqlite3_result_blob, :sqlite3_result_blob, [:pointer, :pointer, :int, :sqlite3_result_blob__callback], :void
  callback :sqlite3_result_blob64__callback, [:pointer], :void
  attach_function :sqlite3_result_blob64, :sqlite3_result_blob64, [:pointer, :pointer, :ulong_long, :sqlite3_result_blob64__callback], :void
  attach_function :sqlite3_result_double, :sqlite3_result_double, [:pointer, :double], :void
  attach_function :sqlite3_result_error, :sqlite3_result_error, [:pointer, :string, :int], :void
  attach_function :sqlite3_result_error16, :sqlite3_result_error16, [:pointer, :pointer, :int], :void
  attach_function :sqlite3_result_error_toobig, :sqlite3_result_error_toobig, [:pointer], :void
  attach_function :sqlite3_result_error_nomem, :sqlite3_result_error_nomem, [:pointer], :void
  attach_function :sqlite3_result_error_code, :sqlite3_result_error_code, [:pointer, :int], :void
  attach_function :sqlite3_result_int, :sqlite3_result_int, [:pointer, :int], :void
  attach_function :sqlite3_result_int64, :sqlite3_result_int64, [:pointer, :long_long], :void
  attach_function :sqlite3_result_null, :sqlite3_result_null, [:pointer], :void
  callback :sqlite3_result_text__callback, [:pointer], :void
  attach_function :sqlite3_result_text, :sqlite3_result_text, [:pointer, :string, :int, :sqlite3_result_text__callback], :void
  callback :sqlite3_result_text64__callback, [:pointer], :void
  attach_function :sqlite3_result_text64, :sqlite3_result_text64, [:pointer, :string, :ulong_long, :sqlite3_result_text64__callback, :uchar], :void
  callback :sqlite3_result_text16__callback, [:pointer], :void
  attach_function :sqlite3_result_text16, :sqlite3_result_text16, [:pointer, :pointer, :int, :sqlite3_result_text16__callback], :void
  callback :sqlite3_result_text16le__callback, [:pointer], :void
  attach_function :sqlite3_result_text16le, :sqlite3_result_text16le, [:pointer, :pointer, :int, :sqlite3_result_text16le__callback], :void
  callback :sqlite3_result_text16be__callback, [:pointer], :void
  attach_function :sqlite3_result_text16be, :sqlite3_result_text16be, [:pointer, :pointer, :int, :sqlite3_result_text16be__callback], :void
  attach_function :sqlite3_result_value, :sqlite3_result_value, [:pointer, :pointer], :void
  callback :sqlite3_result_pointer__callback, [:pointer], :void
  attach_function :sqlite3_result_pointer, :sqlite3_result_pointer, [:pointer, :pointer, :string, :sqlite3_result_pointer__callback], :void
  attach_function :sqlite3_result_zeroblob, :sqlite3_result_zeroblob, [:pointer, :int], :void
  attach_function :sqlite3_result_zeroblob64, :sqlite3_result_zeroblob64, [:pointer, :ulong_long], :int
  attach_function :sqlite3_result_subtype, :sqlite3_result_subtype, [:pointer, :uint], :void
  callback :sqlite3_create_collation_xCompare_callback, [:pointer, :int, :pointer, :int, :pointer], :int
  attach_function :sqlite3_create_collation, :sqlite3_create_collation, [:pointer, :string, :int, :pointer, :sqlite3_create_collation_xCompare_callback], :int
  callback :sqlite3_create_collation_v2_xCompare_callback, [:pointer, :int, :pointer, :int, :pointer], :int
  callback :sqlite3_create_collation_v2_xDestroy_callback, [:pointer], :void
  attach_function :sqlite3_create_collation_v2, :sqlite3_create_collation_v2, [:pointer, :string, :int, :pointer, :sqlite3_create_collation_v2_xCompare_callback, :sqlite3_create_collation_v2_xDestroy_callback], :int
  callback :sqlite3_create_collation16_xCompare_callback, [:pointer, :int, :pointer, :int, :pointer], :int
  attach_function :sqlite3_create_collation16, :sqlite3_create_collation16, [:pointer, :pointer, :int, :pointer, :sqlite3_create_collation16_xCompare_callback], :int
  callback :sqlite3_collation_needed__callback, [:pointer, :pointer, :int, :string], :void
  attach_function :sqlite3_collation_needed, :sqlite3_collation_needed, [:pointer, :pointer, :sqlite3_collation_needed__callback], :int
  callback :sqlite3_collation_needed16__callback, [:pointer, :pointer, :int, :pointer], :void
  attach_function :sqlite3_collation_needed16, :sqlite3_collation_needed16, [:pointer, :pointer, :sqlite3_collation_needed16__callback], :int
  attach_function :sqlite3_sleep, :sqlite3_sleep, [:int], :int
  attach_variable :Sqlite3TempDirectory, :sqlite3_temp_directory, :pointer
  attach_variable :Sqlite3DataDirectory, :sqlite3_data_directory, :pointer
  attach_function :sqlite3_win32_set_directory, :sqlite3_win32_set_directory, [:ulong, :pointer], :int
  attach_function :sqlite3_win32_set_directory8, :sqlite3_win32_set_directory8, [:ulong, :string], :int
  attach_function :sqlite3_win32_set_directory16, :sqlite3_win32_set_directory16, [:ulong, :pointer], :int
  attach_function :sqlite3_get_autocommit, :sqlite3_get_autocommit, [:pointer], :int
  attach_function :sqlite3_db_handle, :sqlite3_db_handle, [:pointer], :pointer
  attach_function :sqlite3_db_name, :sqlite3_db_name, [:pointer, :int], :string
  attach_function :sqlite3_db_filename, :sqlite3_db_filename, [:pointer, :string], :string
  attach_function :sqlite3_db_readonly, :sqlite3_db_readonly, [:pointer, :string], :int
  attach_function :sqlite3_txn_state, :sqlite3_txn_state, [:pointer, :string], :int
  attach_function :sqlite3_next_stmt, :sqlite3_next_stmt, [:pointer, :pointer], :pointer
  callback :sqlite3_commit_hook__callback, [:pointer], :int
  attach_function :sqlite3_commit_hook, :sqlite3_commit_hook, [:pointer, :sqlite3_commit_hook__callback, :pointer], :pointer
  callback :sqlite3_rollback_hook__callback, [:pointer], :void
  attach_function :sqlite3_rollback_hook, :sqlite3_rollback_hook, [:pointer, :sqlite3_rollback_hook__callback, :pointer], :pointer
  callback :sqlite3_autovacuum_pages__callback, [:pointer, :string, :uint, :uint, :uint], :uint
  callback :sqlite3_autovacuum_pages__callback, [:pointer], :void
  attach_function :sqlite3_autovacuum_pages, :sqlite3_autovacuum_pages, [:pointer, :sqlite3_autovacuum_pages__callback, :pointer, :sqlite3_autovacuum_pages__callback], :int
  callback :sqlite3_update_hook__callback, [:pointer, :int, :string, :string, :long_long], :void
  attach_function :sqlite3_update_hook, :sqlite3_update_hook, [:pointer, :sqlite3_update_hook__callback, :pointer], :pointer
  attach_function :sqlite3_enable_shared_cache, :sqlite3_enable_shared_cache, [:int], :int
  attach_function :sqlite3_release_memory, :sqlite3_release_memory, [:int], :int
  attach_function :sqlite3_db_release_memory, :sqlite3_db_release_memory, [:pointer], :int
  attach_function :sqlite3_soft_heap_limit64, :sqlite3_soft_heap_limit64, [:long_long], :long_long
  attach_function :sqlite3_hard_heap_limit64, :sqlite3_hard_heap_limit64, [:long_long], :long_long
  attach_function :sqlite3_soft_heap_limit, :sqlite3_soft_heap_limit, [:int], :void
  attach_function :sqlite3_table_column_metadata, :sqlite3_table_column_metadata, [:pointer, :string, :string, :string, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :sqlite3_load_extension, :sqlite3_load_extension, [:pointer, :string, :string, :pointer], :int
  attach_function :sqlite3_enable_load_extension, :sqlite3_enable_load_extension, [:pointer, :int], :int
  callback :sqlite3_auto_extension_xEntryPoint_callback, [], :void
  attach_function :sqlite3_auto_extension, :sqlite3_auto_extension, [:sqlite3_auto_extension_xEntryPoint_callback], :int
  callback :sqlite3_cancel_auto_extension_xEntryPoint_callback, [], :void
  attach_function :sqlite3_cancel_auto_extension, :sqlite3_cancel_auto_extension, [:sqlite3_cancel_auto_extension_xEntryPoint_callback], :int
  attach_function :sqlite3_reset_auto_extension, :sqlite3_reset_auto_extension, [], :void
  callback :sqlite3_module_xCreate_callback, [:pointer, :pointer, :int, :pointer, :pointer, :pointer], :int
  callback :sqlite3_module_xConnect_callback, [:pointer, :pointer, :int, :pointer, :pointer, :pointer], :int
  callback :sqlite3_module_xBestIndex_callback, [:pointer, :pointer], :int
  callback :sqlite3_module_xDisconnect_callback, [:pointer], :int
  callback :sqlite3_module_xDestroy_callback, [:pointer], :int
  callback :sqlite3_module_xOpen_callback, [:pointer, :pointer], :int
  callback :sqlite3_module_xClose_callback, [:pointer], :int
  callback :sqlite3_module_xFilter_callback, [:pointer, :int, :string, :int, :pointer], :int
  callback :sqlite3_module_xNext_callback, [:pointer], :int
  callback :sqlite3_module_xEof_callback, [:pointer], :int
  callback :sqlite3_module_xColumn_callback, [:pointer, :pointer, :int], :int
  callback :sqlite3_module_xRowid_callback, [:pointer, :pointer], :int
  callback :sqlite3_module_xUpdate_callback, [:pointer, :int, :pointer, :pointer], :int
  callback :sqlite3_module_xBegin_callback, [:pointer], :int
  callback :sqlite3_module_xSync_callback, [:pointer], :int
  callback :sqlite3_module_xCommit_callback, [:pointer], :int
  callback :sqlite3_module_xRollback_callback, [:pointer], :int
  callback :sqlite3_module_xFindFunction_callback, [:pointer, :int, :string, :pointer, :pointer], :int
  callback :sqlite3_module_xRename_callback, [:pointer, :string], :int
  callback :sqlite3_module_xSavepoint_callback, [:pointer, :int], :int
  callback :sqlite3_module_xRelease_callback, [:pointer, :int], :int
  callback :sqlite3_module_xRollbackTo_callback, [:pointer, :int], :int
  callback :sqlite3_module_xShadowName_callback, [:string], :int
  callback :sqlite3_module_xIntegrity_callback, [:pointer, :string, :string, :int, :pointer], :int

  class Sqlite3Module < FFI::Struct
    layout :i_version, :int,
           :x_create, :sqlite3_module_xCreate_callback,
           :x_connect, :sqlite3_module_xConnect_callback,
           :x_best_index, :sqlite3_module_xBestIndex_callback,
           :x_disconnect, :sqlite3_module_xDisconnect_callback,
           :x_destroy, :sqlite3_module_xDestroy_callback,
           :x_open, :sqlite3_module_xOpen_callback,
           :x_close, :sqlite3_module_xClose_callback,
           :x_filter, :sqlite3_module_xFilter_callback,
           :x_next, :sqlite3_module_xNext_callback,
           :x_eof, :sqlite3_module_xEof_callback,
           :x_column, :sqlite3_module_xColumn_callback,
           :x_rowid, :sqlite3_module_xRowid_callback,
           :x_update, :sqlite3_module_xUpdate_callback,
           :x_begin, :sqlite3_module_xBegin_callback,
           :x_sync, :sqlite3_module_xSync_callback,
           :x_commit, :sqlite3_module_xCommit_callback,
           :x_rollback, :sqlite3_module_xRollback_callback,
           :x_find_function, :sqlite3_module_xFindFunction_callback,
           :x_rename, :sqlite3_module_xRename_callback,
           :x_savepoint, :sqlite3_module_xSavepoint_callback,
           :x_release, :sqlite3_module_xRelease_callback,
           :x_rollback_to, :sqlite3_module_xRollbackTo_callback,
           :x_shadow_name, :sqlite3_module_xShadowName_callback,
           :x_integrity, :sqlite3_module_xIntegrity_callback
  end

  class Sqlite3IndexConstraint < FFI::Struct
    layout :i_column, :int,
           :op, :uchar,
           :usable, :uchar,
           :i_term_offset, :int
  end

  class Sqlite3IndexOrderby < FFI::Struct
    layout :i_column, :int,
           :desc, :uchar
  end

  class Sqlite3IndexConstraintUsage < FFI::Struct
    layout :argv_index, :int,
           :omit, :uchar
  end

  class Sqlite3IndexInfo < FFI::Struct
    layout :n_constraint, :int,
           :a_constraint, Sqlite3IndexConstraint.ptr,
           :n_order_by, :int,
           :a_order_by, Sqlite3IndexOrderby.ptr,
           :a_constraint_usage, Sqlite3IndexConstraintUsage.ptr,
           :idx_num, :int,
           :idx_str, :string,
           :need_to_free_idx_str, :int,
           :order_by_consumed, :int,
           :estimated_cost, :double,
           :estimated_rows, :long_long,
           :idx_flags, :int,
           :col_used, :ulong_long
  end

  attach_function :sqlite3_create_module, :sqlite3_create_module, [:pointer, :string, Sqlite3Module.by_ref, :pointer], :int
  callback :sqlite3_create_module_v2_xDestroy_callback, [:pointer], :void
  attach_function :sqlite3_create_module_v2, :sqlite3_create_module_v2, [:pointer, :string, Sqlite3Module.by_ref, :pointer, :sqlite3_create_module_v2_xDestroy_callback], :int
  attach_function :sqlite3_drop_modules, :sqlite3_drop_modules, [:pointer, :pointer], :int

  class Sqlite3Vtab < FFI::Struct
    layout :p_module, :pointer,
           :n_ref, :int,
           :z_err_msg, :string
  end

  class Sqlite3VtabCursor < FFI::Struct
    layout :p_vtab, :pointer
  end

  attach_function :sqlite3_declare_vtab, :sqlite3_declare_vtab, [:pointer, :string], :int
  attach_function :sqlite3_overload_function, :sqlite3_overload_function, [:pointer, :string, :int], :int
  typedef :pointer, :Sqlite3Blob
  attach_function :sqlite3_blob_open, :sqlite3_blob_open, [:pointer, :string, :string, :string, :long_long, :int, :pointer], :int
  attach_function :sqlite3_blob_reopen, :sqlite3_blob_reopen, [:pointer, :long_long], :int
  attach_function :sqlite3_blob_close, :sqlite3_blob_close, [:pointer], :int
  attach_function :sqlite3_blob_bytes, :sqlite3_blob_bytes, [:pointer], :int
  attach_function :sqlite3_blob_read, :sqlite3_blob_read, [:pointer, :pointer, :int, :int], :int
  attach_function :sqlite3_blob_write, :sqlite3_blob_write, [:pointer, :pointer, :int, :int], :int
  attach_function :sqlite3_vfs_find, :sqlite3_vfs_find, [:string], Sqlite3Vfs.by_ref
  attach_function :sqlite3_vfs_register, :sqlite3_vfs_register, [Sqlite3Vfs.by_ref, :int], :int
  attach_function :sqlite3_vfs_unregister, :sqlite3_vfs_unregister, [Sqlite3Vfs.by_ref], :int
  attach_function :sqlite3_mutex_alloc, :sqlite3_mutex_alloc, [:int], :pointer
  attach_function :sqlite3_mutex_free, :sqlite3_mutex_free, [:pointer], :void
  attach_function :sqlite3_mutex_enter, :sqlite3_mutex_enter, [:pointer], :void
  attach_function :sqlite3_mutex_try, :sqlite3_mutex_try, [:pointer], :int
  attach_function :sqlite3_mutex_leave, :sqlite3_mutex_leave, [:pointer], :void
  callback :sqlite3_mutex_methods_xMutexInit_callback, [], :int
  callback :sqlite3_mutex_methods_xMutexEnd_callback, [], :int
  callback :sqlite3_mutex_methods_xMutexAlloc_callback, [:int], :pointer
  callback :sqlite3_mutex_methods_xMutexFree_callback, [:pointer], :void
  callback :sqlite3_mutex_methods_xMutexEnter_callback, [:pointer], :void
  callback :sqlite3_mutex_methods_xMutexTry_callback, [:pointer], :int
  callback :sqlite3_mutex_methods_xMutexLeave_callback, [:pointer], :void
  callback :sqlite3_mutex_methods_xMutexHeld_callback, [:pointer], :int
  callback :sqlite3_mutex_methods_xMutexNotheld_callback, [:pointer], :int

  class Sqlite3MutexMethods < FFI::Struct
    layout :x_mutex_init, :sqlite3_mutex_methods_xMutexInit_callback,
           :x_mutex_end, :sqlite3_mutex_methods_xMutexEnd_callback,
           :x_mutex_alloc, :sqlite3_mutex_methods_xMutexAlloc_callback,
           :x_mutex_free, :sqlite3_mutex_methods_xMutexFree_callback,
           :x_mutex_enter, :sqlite3_mutex_methods_xMutexEnter_callback,
           :x_mutex_try, :sqlite3_mutex_methods_xMutexTry_callback,
           :x_mutex_leave, :sqlite3_mutex_methods_xMutexLeave_callback,
           :x_mutex_held, :sqlite3_mutex_methods_xMutexHeld_callback,
           :x_mutex_notheld, :sqlite3_mutex_methods_xMutexNotheld_callback
  end

  attach_function :sqlite3_mutex_held, :sqlite3_mutex_held, [:pointer], :int
  attach_function :sqlite3_mutex_notheld, :sqlite3_mutex_notheld, [:pointer], :int
  attach_function :sqlite3_db_mutex, :sqlite3_db_mutex, [:pointer], :pointer
  attach_function :sqlite3_file_control, :sqlite3_file_control, [:pointer, :string, :int, :pointer], :int
  attach_function :sqlite3_test_control, :sqlite3_test_control, [:int], :int
  attach_function :sqlite3_keyword_count, :sqlite3_keyword_count, [], :int
  attach_function :sqlite3_keyword_name, :sqlite3_keyword_name, [:int, :pointer, :pointer], :int
  attach_function :sqlite3_keyword_check, :sqlite3_keyword_check, [:string, :int], :int
  typedef :pointer, :Sqlite3Str
  attach_function :sqlite3_str_new, :sqlite3_str_new, [:pointer], :pointer
  attach_function :sqlite3_str_finish, :sqlite3_str_finish, [:pointer], :pointer
  attach_function :sqlite3_str_appendf, :sqlite3_str_appendf, [:pointer, :string], :void
  attach_function :sqlite3_str_vappendf, :sqlite3_str_vappendf, [:pointer, :string, :varargs], :void
  attach_function :sqlite3_str_append, :sqlite3_str_append, [:pointer, :string, :int], :void
  attach_function :sqlite3_str_appendall, :sqlite3_str_appendall, [:pointer, :string], :void
  attach_function :sqlite3_str_appendchar, :sqlite3_str_appendchar, [:pointer, :int, :char], :void
  attach_function :sqlite3_str_reset, :sqlite3_str_reset, [:pointer], :void
  attach_function :sqlite3_str_errcode, :sqlite3_str_errcode, [:pointer], :int
  attach_function :sqlite3_str_length, :sqlite3_str_length, [:pointer], :int
  attach_function :sqlite3_str_value, :sqlite3_str_value, [:pointer], :pointer
  attach_function :sqlite3_status, :sqlite3_status, [:int, :pointer, :pointer, :int], :int
  attach_function :sqlite3_status64, :sqlite3_status64, [:int, :pointer, :pointer, :int], :int
  attach_function :sqlite3_db_status, :sqlite3_db_status, [:pointer, :int, :pointer, :pointer, :int], :int
  attach_function :sqlite3_stmt_status, :sqlite3_stmt_status, [:pointer, :int, :int], :int
  typedef :pointer, :Sqlite3Pcache

  class Sqlite3PcachePage < FFI::Struct
    layout :p_buf, :pointer,
           :p_extra, :pointer
  end

  callback :sqlite3_pcache_methods2_xInit_callback, [:pointer], :int
  callback :sqlite3_pcache_methods2_xShutdown_callback, [:pointer], :void
  callback :sqlite3_pcache_methods2_xCreate_callback, [:int, :int, :int], :pointer
  callback :sqlite3_pcache_methods2_xCachesize_callback, [:pointer, :int], :void
  callback :sqlite3_pcache_methods2_xPagecount_callback, [:pointer], :int
  callback :sqlite3_pcache_methods2_xFetch_callback, [:pointer, :uint, :int], Sqlite3PcachePage.by_ref
  callback :sqlite3_pcache_methods2_xUnpin_callback, [:pointer, :pointer, :int], :void
  callback :sqlite3_pcache_methods2_xRekey_callback, [:pointer, :pointer, :uint, :uint], :void
  callback :sqlite3_pcache_methods2_xTruncate_callback, [:pointer, :uint], :void
  callback :sqlite3_pcache_methods2_xDestroy_callback, [:pointer], :void
  callback :sqlite3_pcache_methods2_xShrink_callback, [:pointer], :void

  class Sqlite3PcacheMethods2 < FFI::Struct
    layout :i_version, :int,
           :p_arg, :pointer,
           :x_init, :sqlite3_pcache_methods2_xInit_callback,
           :x_shutdown, :sqlite3_pcache_methods2_xShutdown_callback,
           :x_create, :sqlite3_pcache_methods2_xCreate_callback,
           :x_cachesize, :sqlite3_pcache_methods2_xCachesize_callback,
           :x_pagecount, :sqlite3_pcache_methods2_xPagecount_callback,
           :x_fetch, :sqlite3_pcache_methods2_xFetch_callback,
           :x_unpin, :sqlite3_pcache_methods2_xUnpin_callback,
           :x_rekey, :sqlite3_pcache_methods2_xRekey_callback,
           :x_truncate, :sqlite3_pcache_methods2_xTruncate_callback,
           :x_destroy, :sqlite3_pcache_methods2_xDestroy_callback,
           :x_shrink, :sqlite3_pcache_methods2_xShrink_callback
  end

  callback :sqlite3_pcache_methods_xInit_callback, [:pointer], :int
  callback :sqlite3_pcache_methods_xShutdown_callback, [:pointer], :void
  callback :sqlite3_pcache_methods_xCreate_callback, [:int, :int], :pointer
  callback :sqlite3_pcache_methods_xCachesize_callback, [:pointer, :int], :void
  callback :sqlite3_pcache_methods_xPagecount_callback, [:pointer], :int
  callback :sqlite3_pcache_methods_xFetch_callback, [:pointer, :uint, :int], :pointer
  callback :sqlite3_pcache_methods_xUnpin_callback, [:pointer, :pointer, :int], :void
  callback :sqlite3_pcache_methods_xRekey_callback, [:pointer, :pointer, :uint, :uint], :void
  callback :sqlite3_pcache_methods_xTruncate_callback, [:pointer, :uint], :void
  callback :sqlite3_pcache_methods_xDestroy_callback, [:pointer], :void

  class Sqlite3PcacheMethods < FFI::Struct
    layout :p_arg, :pointer,
           :x_init, :sqlite3_pcache_methods_xInit_callback,
           :x_shutdown, :sqlite3_pcache_methods_xShutdown_callback,
           :x_create, :sqlite3_pcache_methods_xCreate_callback,
           :x_cachesize, :sqlite3_pcache_methods_xCachesize_callback,
           :x_pagecount, :sqlite3_pcache_methods_xPagecount_callback,
           :x_fetch, :sqlite3_pcache_methods_xFetch_callback,
           :x_unpin, :sqlite3_pcache_methods_xUnpin_callback,
           :x_rekey, :sqlite3_pcache_methods_xRekey_callback,
           :x_truncate, :sqlite3_pcache_methods_xTruncate_callback,
           :x_destroy, :sqlite3_pcache_methods_xDestroy_callback
  end

  typedef :pointer, :Sqlite3Backup
  attach_function :sqlite3_backup_init, :sqlite3_backup_init, [:pointer, :string, :pointer, :string], :pointer
  attach_function :sqlite3_backup_step, :sqlite3_backup_step, [:pointer, :int], :int
  attach_function :sqlite3_backup_finish, :sqlite3_backup_finish, [:pointer], :int
  attach_function :sqlite3_backup_remaining, :sqlite3_backup_remaining, [:pointer], :int
  attach_function :sqlite3_backup_pagecount, :sqlite3_backup_pagecount, [:pointer], :int
  callback :sqlite3_unlock_notify_xNotify_callback, [:pointer, :int], :void
  attach_function :sqlite3_unlock_notify, :sqlite3_unlock_notify, [:pointer, :sqlite3_unlock_notify_xNotify_callback, :pointer], :int
  attach_function :sqlite3_stricmp, :sqlite3_stricmp, [:string, :string], :int
  attach_function :sqlite3_strnicmp, :sqlite3_strnicmp, [:string, :string, :int], :int
  attach_function :sqlite3_strglob, :sqlite3_strglob, [:string, :string], :int
  attach_function :sqlite3_strlike, :sqlite3_strlike, [:string, :string, :uint], :int
  attach_function :sqlite3_log, :sqlite3_log, [:int, :string], :void
  callback :sqlite3_wal_hook__callback, [:pointer, :pointer, :string, :int], :int
  attach_function :sqlite3_wal_hook, :sqlite3_wal_hook, [:pointer, :sqlite3_wal_hook__callback, :pointer], :pointer
  attach_function :sqlite3_wal_autocheckpoint, :sqlite3_wal_autocheckpoint, [:pointer, :int], :int
  attach_function :sqlite3_wal_checkpoint, :sqlite3_wal_checkpoint, [:pointer, :string], :int
  attach_function :sqlite3_wal_checkpoint_v2, :sqlite3_wal_checkpoint_v2, [:pointer, :string, :int, :pointer, :pointer], :int
  attach_function :sqlite3_vtab_config, :sqlite3_vtab_config, [:pointer, :int], :int
  attach_function :sqlite3_vtab_on_conflict, :sqlite3_vtab_on_conflict, [:pointer], :int
  attach_function :sqlite3_vtab_nochange, :sqlite3_vtab_nochange, [:pointer], :int
  attach_function :sqlite3_vtab_collation, :sqlite3_vtab_collation, [Sqlite3IndexInfo.by_ref, :int], :string
  attach_function :sqlite3_vtab_distinct, :sqlite3_vtab_distinct, [Sqlite3IndexInfo.by_ref], :int
  attach_function :sqlite3_vtab_in, :sqlite3_vtab_in, [Sqlite3IndexInfo.by_ref, :int, :int], :int
  attach_function :sqlite3_vtab_in_first, :sqlite3_vtab_in_first, [:pointer, :pointer], :int
  attach_function :sqlite3_vtab_in_next, :sqlite3_vtab_in_next, [:pointer, :pointer], :int
  attach_function :sqlite3_vtab_rhs_value, :sqlite3_vtab_rhs_value, [Sqlite3IndexInfo.by_ref, :int, :pointer], :int
  attach_function :sqlite3_stmt_scanstatus, :sqlite3_stmt_scanstatus, [:pointer, :int, :int, :pointer], :int
  attach_function :sqlite3_stmt_scanstatus_v2, :sqlite3_stmt_scanstatus_v2, [:pointer, :int, :int, :int, :pointer], :int
  attach_function :sqlite3_stmt_scanstatus_reset, :sqlite3_stmt_scanstatus_reset, [:pointer], :void
  attach_function :sqlite3_db_cacheflush, :sqlite3_db_cacheflush, [:pointer], :int
  attach_function :sqlite3_system_errno, :sqlite3_system_errno, [:pointer], :int

  class Sqlite3Snapshot < FFI::Struct
    layout :hidden, [:uchar, 48]
  end

  attach_function :sqlite3_snapshot_get, :sqlite3_snapshot_get, [:pointer, :string, :pointer], :int
  attach_function :sqlite3_snapshot_open, :sqlite3_snapshot_open, [:pointer, :string, Sqlite3Snapshot.by_ref], :int
  attach_function :sqlite3_snapshot_free, :sqlite3_snapshot_free, [Sqlite3Snapshot.by_ref], :void
  attach_function :sqlite3_snapshot_cmp, :sqlite3_snapshot_cmp, [Sqlite3Snapshot.by_ref, Sqlite3Snapshot.by_ref], :int
  attach_function :sqlite3_snapshot_recover, :sqlite3_snapshot_recover, [:pointer, :string], :int
  attach_function :sqlite3_serialize, :sqlite3_serialize, [:pointer, :string, :pointer, :uint], :pointer
  attach_function :sqlite3_deserialize, :sqlite3_deserialize, [:pointer, :string, :pointer, :long_long, :long_long, :uint], :int
  typedef :double, :sqlite3_rtree_dbl
  callback :sqlite3_rtree_geometry_callback_xGeom_callback, [:pointer, :int, :pointer, :pointer], :int
  attach_function :sqlite3_rtree_geometry_callback, :sqlite3_rtree_geometry_callback, [:pointer, :string, :sqlite3_rtree_geometry_callback_xGeom_callback, :pointer], :int
  callback :sqlite3_rtree_geometry_xDelUser_callback, [:pointer], :void

  class Sqlite3RtreeGeometry < FFI::Struct
    layout :p_context, :pointer,
           :n_param, :int,
           :a_param, :pointer,
           :p_user, :pointer,
           :x_del_user, :sqlite3_rtree_geometry_xDelUser_callback
  end

  callback :sqlite3_rtree_query_callback_xQueryFunc_callback, [:pointer], :int
  callback :sqlite3_rtree_query_callback_xDestructor_callback, [:pointer], :void
  attach_function :sqlite3_rtree_query_callback, :sqlite3_rtree_query_callback, [:pointer, :string, :sqlite3_rtree_query_callback_xQueryFunc_callback, :pointer, :sqlite3_rtree_query_callback_xDestructor_callback], :int
  callback :sqlite3_rtree_query_info_xDelUser_callback, [:pointer], :void

  class Sqlite3RtreeQueryInfo < FFI::Struct
    layout :p_context, :pointer,
           :n_param, :int,
           :a_param, :pointer,
           :p_user, :pointer,
           :x_del_user, :sqlite3_rtree_query_info_xDelUser_callback,
           :a_coord, :pointer,
           :an_queue, :pointer,
           :n_coord, :int,
           :i_level, :int,
           :mx_level, :int,
           :i_rowid, :long_long,
           :r_parent_score, :double,
           :e_parent_within, :int,
           :e_within, :int,
           :r_score, :double,
           :ap_sql_param, :pointer
  end

  typedef :pointer, :Fts5Context
  callback :fts5_extension_function, [], :void

  class Fts5PhraseIter < FFI::Struct
    layout :a, :pointer,
           :b, :pointer
  end

  callback :Fts5ExtensionApi_xUserData_callback, [:pointer], :pointer
  callback :Fts5ExtensionApi_xColumnCount_callback, [:pointer], :int
  callback :Fts5ExtensionApi_xRowCount_callback, [:pointer, :pointer], :int
  callback :Fts5ExtensionApi_xColumnTotalSize_callback, [:pointer, :int, :pointer], :int
  callback :Fts5ExtensionApi_xTokenize_callback, [:pointer, :string, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xPhraseCount_callback, [:pointer], :int
  callback :Fts5ExtensionApi_xPhraseSize_callback, [:pointer, :int], :int
  callback :Fts5ExtensionApi_xInstCount_callback, [:pointer, :pointer], :int
  callback :Fts5ExtensionApi_xInst_callback, [:pointer, :int, :pointer, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xRowid_callback, [:pointer], :long_long
  callback :Fts5ExtensionApi_xColumnText_callback, [:pointer, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xColumnSize_callback, [:pointer, :int, :pointer], :int
  callback :Fts5ExtensionApi_xQueryPhrase_callback, [:pointer, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xSetAuxdata_callback, [:pointer, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xGetAuxdata_callback, [:pointer, :int], :pointer
  callback :Fts5ExtensionApi_xPhraseFirst_callback, [:pointer, :int, :pointer, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xPhraseNext_callback, [:pointer, :pointer, :pointer, :pointer], :void
  callback :Fts5ExtensionApi_xPhraseFirstColumn_callback, [:pointer, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xPhraseNextColumn_callback, [:pointer, :pointer, :pointer], :void
  callback :Fts5ExtensionApi_xQueryToken_callback, [:pointer, :int, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xInstToken_callback, [:pointer, :int, :int, :pointer, :pointer], :int

  class Fts5ExtensionApi < FFI::Struct
    layout :i_version, :int,
           :x_user_data, :Fts5ExtensionApi_xUserData_callback,
           :x_column_count, :Fts5ExtensionApi_xColumnCount_callback,
           :x_row_count, :Fts5ExtensionApi_xRowCount_callback,
           :x_column_total_size, :Fts5ExtensionApi_xColumnTotalSize_callback,
           :x_tokenize, :Fts5ExtensionApi_xTokenize_callback,
           :x_phrase_count, :Fts5ExtensionApi_xPhraseCount_callback,
           :x_phrase_size, :Fts5ExtensionApi_xPhraseSize_callback,
           :x_inst_count, :Fts5ExtensionApi_xInstCount_callback,
           :x_inst, :Fts5ExtensionApi_xInst_callback,
           :x_rowid, :Fts5ExtensionApi_xRowid_callback,
           :x_column_text, :Fts5ExtensionApi_xColumnText_callback,
           :x_column_size, :Fts5ExtensionApi_xColumnSize_callback,
           :x_query_phrase, :Fts5ExtensionApi_xQueryPhrase_callback,
           :x_set_auxdata, :Fts5ExtensionApi_xSetAuxdata_callback,
           :x_get_auxdata, :Fts5ExtensionApi_xGetAuxdata_callback,
           :x_phrase_first, :Fts5ExtensionApi_xPhraseFirst_callback,
           :x_phrase_next, :Fts5ExtensionApi_xPhraseNext_callback,
           :x_phrase_first_column, :Fts5ExtensionApi_xPhraseFirstColumn_callback,
           :x_phrase_next_column, :Fts5ExtensionApi_xPhraseNextColumn_callback,
           :x_query_token, :Fts5ExtensionApi_xQueryToken_callback,
           :x_inst_token, :Fts5ExtensionApi_xInstToken_callback
  end

  typedef :pointer, :Fts5Tokenizer
  callback :fts5_tokenizer_xCreate_callback, [:pointer, :pointer, :int, :pointer], :int
  callback :fts5_tokenizer_xDelete_callback, [:pointer], :void
  callback :fts5_tokenizer_xTokenize_callback, [:pointer, :pointer, :int, :string, :int, :pointer], :int

  class Fts5Tokenizer < FFI::Struct
    layout :x_create, :fts5_tokenizer_xCreate_callback,
           :x_delete, :fts5_tokenizer_xDelete_callback,
           :x_tokenize, :fts5_tokenizer_xTokenize_callback
  end

  callback :fts5_api_xCreateTokenizer_callback, [:pointer, :string, :pointer, :pointer, :pointer], :int
  callback :fts5_api_xFindTokenizer_callback, [:pointer, :string, :pointer, :pointer], :int
  callback :fts5_api_xCreateFunction_callback, [:pointer, :string, :pointer, :pointer, :pointer], :int

  class Fts5Api < FFI::Struct
    layout :i_version, :int,
           :x_create_tokenizer, :fts5_api_xCreateTokenizer_callback,
           :x_find_tokenizer, :fts5_api_xFindTokenizer_callback,
           :x_create_function, :fts5_api_xCreateFunction_callback
  end
end
