# Generated by ruby-bindgen (1.0.0)

require 'ffi'

module Sqlite3
  extend FFI::Library

  def self.library_names
    ["sqlite3"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          when /mingw/
            result << "lib#{name}-#{version}"
          when /mswin/
            result << "#{name}_#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names
end

require_relative './sqlite3'
