# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

FFI::DynamicLibrary::SEARCH_PATH = ["c:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin"]

module Sqlite3
  extend FFI::Library

  def self.library_names
    ["sqlite3"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  attach_variable :Sqlite3Version, :sqlite3_version, :string
  attach_function :sqlite3_libversion, :sqlite3_libversion, [], :string
  attach_function :sqlite3_sourceid, :sqlite3_sourceid, [], :string
  attach_function :sqlite3_libversion_number, :sqlite3_libversion_number, [], :int
  attach_function :sqlite3_compileoption_used, :sqlite3_compileoption_used, [:string], :int
  attach_function :sqlite3_compileoption_get, :sqlite3_compileoption_get, [:int], :string
  attach_function :sqlite3_threadsafe, :sqlite3_threadsafe, [], :int

  class Sqlite3 < FFI::Struct
  end

  typedef :long_long, :sqlite_int64
  typedef :ulong_long, :sqlite_uint64
  typedef :long_long, :sqlite_int64
  typedef :ulong_long, :sqlite_uint64
  attach_function :sqlite3_close, :sqlite3_close, [Sqlite3.by_ref], :int
  attach_function :sqlite3_close_v2, :sqlite3_close_v2, [Sqlite3.by_ref], :int
  callback :sqlite3_callback, [], :int
  callback :sqlite3_exec_callback_callback, [:pointer, :int, :pointer, :pointer], :int
  attach_function :sqlite3_exec, :sqlite3_exec, [Sqlite3.by_ref, :string, :sqlite3_exec_callback_callback, :pointer, :pointer], :int

  class Sqlite3File < FFI::Struct
    layout :p_methods, :pointer
  end

  callback :sqlite3_io_methods_xClose_callback, [:pointer], :int
  callback :sqlite3_io_methods_xRead_callback, [:pointer, :pointer, :int, :long_long], :int
  callback :sqlite3_io_methods_xWrite_callback, [:pointer, :pointer, :int, :long_long], :int
  callback :sqlite3_io_methods_xTruncate_callback, [:pointer, :long_long], :int
  callback :sqlite3_io_methods_xSync_callback, [:pointer, :int], :int
  callback :sqlite3_io_methods_xFileSize_callback, [:pointer, :pointer], :int
  callback :sqlite3_io_methods_xLock_callback, [:pointer, :int], :int
  callback :sqlite3_io_methods_xUnlock_callback, [:pointer, :int], :int
  callback :sqlite3_io_methods_xCheckReservedLock_callback, [:pointer, :pointer], :int
  callback :sqlite3_io_methods_xFileControl_callback, [:pointer, :int, :pointer], :int
  callback :sqlite3_io_methods_xSectorSize_callback, [:pointer], :int
  callback :sqlite3_io_methods_xDeviceCharacteristics_callback, [:pointer], :int
  callback :sqlite3_io_methods_xShmMap_callback, [:pointer, :int, :int, :int, :pointer], :int
  callback :sqlite3_io_methods_xShmLock_callback, [:pointer, :int, :int, :int], :int
  callback :sqlite3_io_methods_xShmBarrier_callback, [:pointer], :void
  callback :sqlite3_io_methods_xShmUnmap_callback, [:pointer, :int], :int
  callback :sqlite3_io_methods_xFetch_callback, [:pointer, :long_long, :int, :pointer], :int
  callback :sqlite3_io_methods_xUnfetch_callback, [:pointer, :long_long, :pointer], :int

  class Sqlite3IoMethods < FFI::Struct
    layout :i_version, :int,
           :x_close, :sqlite3_io_methods_xClose_callback,
           :x_read, :sqlite3_io_methods_xRead_callback,
           :x_write, :sqlite3_io_methods_xWrite_callback,
           :x_truncate, :sqlite3_io_methods_xTruncate_callback,
           :x_sync, :sqlite3_io_methods_xSync_callback,
           :x_file_size, :sqlite3_io_methods_xFileSize_callback,
           :x_lock, :sqlite3_io_methods_xLock_callback,
           :x_unlock, :sqlite3_io_methods_xUnlock_callback,
           :x_check_reserved_lock, :sqlite3_io_methods_xCheckReservedLock_callback,
           :x_file_control, :sqlite3_io_methods_xFileControl_callback,
           :x_sector_size, :sqlite3_io_methods_xSectorSize_callback,
           :x_device_characteristics, :sqlite3_io_methods_xDeviceCharacteristics_callback,
           :x_shm_map, :sqlite3_io_methods_xShmMap_callback,
           :x_shm_lock, :sqlite3_io_methods_xShmLock_callback,
           :x_shm_barrier, :sqlite3_io_methods_xShmBarrier_callback,
           :x_shm_unmap, :sqlite3_io_methods_xShmUnmap_callback,
           :x_fetch, :sqlite3_io_methods_xFetch_callback,
           :x_unfetch, :sqlite3_io_methods_xUnfetch_callback
  end

  class Sqlite3Mutex < FFI::Struct
  end

  class Sqlite3ApiRoutines < FFI::Struct
  end

  typedef :string, :sqlite3_filename
  callback :sqlite3_syscall_ptr, [], :void
  callback :sqlite3_vfs_xOpen_callback, [:pointer, :string, :pointer, :int, :pointer], :int
  callback :sqlite3_vfs_xDelete_callback, [:pointer, :string, :int], :int
  callback :sqlite3_vfs_xAccess_callback, [:pointer, :string, :int, :pointer], :int
  callback :sqlite3_vfs_xFullPathname_callback, [:pointer, :string, :int, :string], :int
  callback :sqlite3_vfs_xDlOpen_callback, [:pointer, :string], :pointer
  callback :sqlite3_vfs_xDlError_callback, [:pointer, :int, :string], :void
  callback :sqlite3_vfs_xDlSym_callback, [:pointer, :pointer, :string], :pointer
  callback :sqlite3_vfs_xDlClose_callback, [:pointer, :pointer], :void
  callback :sqlite3_vfs_xRandomness_callback, [:pointer, :int, :string], :int
  callback :sqlite3_vfs_xSleep_callback, [:pointer, :int], :int
  callback :sqlite3_vfs_xCurrentTime_callback, [:pointer, :pointer], :int
  callback :sqlite3_vfs_xGetLastError_callback, [:pointer, :int, :string], :int
  callback :sqlite3_vfs_xCurrentTimeInt64_callback, [:pointer, :pointer], :int
  callback :sqlite3_vfs_xSetSystemCall_callback, [:pointer, :string, :pointer], :int
  callback :sqlite3_vfs_xGetSystemCall_callback, [:pointer, :string], :pointer
  callback :sqlite3_vfs_xNextSystemCall_callback, [:pointer, :string], :pointer

  class Sqlite3Vfs < FFI::Struct
    layout :i_version, :int,
           :sz_os_file, :int,
           :mx_pathname, :int,
           :p_next, :pointer,
           :z_name, :string,
           :p_app_data, :pointer,
           :x_open, :sqlite3_vfs_xOpen_callback,
           :x_delete, :sqlite3_vfs_xDelete_callback,
           :x_access, :sqlite3_vfs_xAccess_callback,
           :x_full_pathname, :sqlite3_vfs_xFullPathname_callback,
           :x_dl_open, :sqlite3_vfs_xDlOpen_callback,
           :x_dl_error, :sqlite3_vfs_xDlError_callback,
           :x_dl_sym, :sqlite3_vfs_xDlSym_callback,
           :x_dl_close, :sqlite3_vfs_xDlClose_callback,
           :x_randomness, :sqlite3_vfs_xRandomness_callback,
           :x_sleep, :sqlite3_vfs_xSleep_callback,
           :x_current_time, :sqlite3_vfs_xCurrentTime_callback,
           :x_get_last_error, :sqlite3_vfs_xGetLastError_callback,
           :x_current_time_int64, :sqlite3_vfs_xCurrentTimeInt64_callback,
           :x_set_system_call, :sqlite3_vfs_xSetSystemCall_callback,
           :x_get_system_call, :sqlite3_vfs_xGetSystemCall_callback,
           :x_next_system_call, :sqlite3_vfs_xNextSystemCall_callback
  end

  attach_function :sqlite3_initialize, :sqlite3_initialize, [], :int
  attach_function :sqlite3_shutdown, :sqlite3_shutdown, [], :int
  attach_function :sqlite3_os_init, :sqlite3_os_init, [], :int
  attach_function :sqlite3_os_end, :sqlite3_os_end, [], :int
  attach_function :sqlite3_config, :sqlite3_config, [:int], :int
  attach_function :sqlite3_db_config, :sqlite3_db_config, [Sqlite3.by_ref, :int], :int
  callback :sqlite3_mem_methods_xMalloc_callback, [:int], :pointer
  callback :sqlite3_mem_methods_xFree_callback, [:pointer], :void
  callback :sqlite3_mem_methods_xRealloc_callback, [:pointer, :int], :pointer
  callback :sqlite3_mem_methods_xSize_callback, [:pointer], :int
  callback :sqlite3_mem_methods_xRoundup_callback, [:int], :int
  callback :sqlite3_mem_methods_xInit_callback, [:pointer], :int
  callback :sqlite3_mem_methods_xShutdown_callback, [:pointer], :void

  class Sqlite3MemMethods < FFI::Struct
    layout :x_malloc, :sqlite3_mem_methods_xMalloc_callback,
           :x_free, :sqlite3_mem_methods_xFree_callback,
           :x_realloc, :sqlite3_mem_methods_xRealloc_callback,
           :x_size, :sqlite3_mem_methods_xSize_callback,
           :x_roundup, :sqlite3_mem_methods_xRoundup_callback,
           :x_init, :sqlite3_mem_methods_xInit_callback,
           :x_shutdown, :sqlite3_mem_methods_xShutdown_callback,
           :p_app_data, :pointer
  end

  attach_function :sqlite3_extended_result_codes, :sqlite3_extended_result_codes, [Sqlite3.by_ref, :int], :int
  attach_function :sqlite3_last_insert_rowid, :sqlite3_last_insert_rowid, [Sqlite3.by_ref], :long_long
  attach_function :sqlite3_set_last_insert_rowid, :sqlite3_set_last_insert_rowid, [Sqlite3.by_ref, :long_long], :void
  attach_function :sqlite3_changes, :sqlite3_changes, [Sqlite3.by_ref], :int
  attach_function :sqlite3_changes64, :sqlite3_changes64, [Sqlite3.by_ref], :long_long
  attach_function :sqlite3_total_changes, :sqlite3_total_changes, [Sqlite3.by_ref], :int
  attach_function :sqlite3_total_changes64, :sqlite3_total_changes64, [Sqlite3.by_ref], :long_long
  attach_function :sqlite3_interrupt, :sqlite3_interrupt, [Sqlite3.by_ref], :void
  attach_function :sqlite3_is_interrupted, :sqlite3_is_interrupted, [Sqlite3.by_ref], :int
  attach_function :sqlite3_complete, :sqlite3_complete, [:string], :int
  attach_function :sqlite3_complete16, :sqlite3_complete16, [:pointer], :int
  callback :sqlite3_busy_handler__callback, [:pointer, :int], :int
  attach_function :sqlite3_busy_handler, :sqlite3_busy_handler, [Sqlite3.by_ref, :sqlite3_busy_handler__callback, :pointer], :int
  attach_function :sqlite3_busy_timeout, :sqlite3_busy_timeout, [Sqlite3.by_ref, :int], :int
  attach_function :sqlite3_get_table, :sqlite3_get_table, [Sqlite3.by_ref, :string, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :sqlite3_free_table, :sqlite3_free_table, [:pointer], :void
  attach_function :sqlite3_mprintf, :sqlite3_mprintf, [:string], :string
  attach_function :sqlite3_vmprintf, :sqlite3_vmprintf, [:string, :int], :string
  attach_function :sqlite3_snprintf, :sqlite3_snprintf, [:int, :string, :string], :string
  attach_function :sqlite3_vsnprintf, :sqlite3_vsnprintf, [:int, :string, :string, :int], :string
  attach_function :sqlite3_malloc, :sqlite3_malloc, [:int], :pointer
  attach_function :sqlite3_malloc64, :sqlite3_malloc64, [:ulong_long], :pointer
  attach_function :sqlite3_realloc, :sqlite3_realloc, [:pointer, :int], :pointer
  attach_function :sqlite3_realloc64, :sqlite3_realloc64, [:pointer, :ulong_long], :pointer
  attach_function :sqlite3_free, :sqlite3_free, [:pointer], :void
  attach_function :sqlite3_msize, :sqlite3_msize, [:pointer], :ulong_long
  attach_function :sqlite3_memory_used, :sqlite3_memory_used, [], :long_long
  attach_function :sqlite3_memory_highwater, :sqlite3_memory_highwater, [:int], :long_long
  attach_function :sqlite3_randomness, :sqlite3_randomness, [:int, :pointer], :void
  callback :sqlite3_set_authorizer_xAuth_callback, [:pointer, :int, :string, :string, :string, :string], :int
  attach_function :sqlite3_set_authorizer, :sqlite3_set_authorizer, [Sqlite3.by_ref, :sqlite3_set_authorizer_xAuth_callback, :pointer], :int
  callback :sqlite3_trace_xTrace_callback, [:pointer, :string], :void
  attach_function :sqlite3_trace, :sqlite3_trace, [Sqlite3.by_ref, :sqlite3_trace_xTrace_callback, :pointer], :pointer
  callback :sqlite3_profile_xProfile_callback, [:pointer, :string, :ulong_long], :void
  attach_function :sqlite3_profile, :sqlite3_profile, [Sqlite3.by_ref, :sqlite3_profile_xProfile_callback, :pointer], :pointer
  callback :sqlite3_trace_v2_xCallback_callback, [:uint, :pointer, :pointer, :pointer], :int
  attach_function :sqlite3_trace_v2, :sqlite3_trace_v2, [Sqlite3.by_ref, :uint, :sqlite3_trace_v2_xCallback_callback, :pointer], :int
  callback :sqlite3_progress_handler__callback, [:pointer], :int
  attach_function :sqlite3_progress_handler, :sqlite3_progress_handler, [Sqlite3.by_ref, :int, :sqlite3_progress_handler__callback, :pointer], :void
  attach_function :sqlite3_open, :sqlite3_open, [:string, :pointer], :int
  attach_function :sqlite3_open16, :sqlite3_open16, [:pointer, :pointer], :int
  attach_function :sqlite3_open_v2, :sqlite3_open_v2, [:string, :pointer, :int, :string], :int
  attach_function :sqlite3_uri_parameter, :sqlite3_uri_parameter, [:string, :string], :string
  attach_function :sqlite3_uri_boolean, :sqlite3_uri_boolean, [:string, :string, :int], :int
  attach_function :sqlite3_uri_int64, :sqlite3_uri_int64, [:string, :string, :long_long], :long_long
  attach_function :sqlite3_uri_key, :sqlite3_uri_key, [:string, :int], :string
  attach_function :sqlite3_filename_database, :sqlite3_filename_database, [:string], :string
  attach_function :sqlite3_filename_journal, :sqlite3_filename_journal, [:string], :string
  attach_function :sqlite3_filename_wal, :sqlite3_filename_wal, [:string], :string
  attach_function :sqlite3_database_file_object, :sqlite3_database_file_object, [:string], Sqlite3File.by_ref
  attach_function :sqlite3_create_filename, :sqlite3_create_filename, [:string, :string, :string, :int, :pointer], :string
  attach_function :sqlite3_free_filename, :sqlite3_free_filename, [:string], :void
  attach_function :sqlite3_errcode, :sqlite3_errcode, [Sqlite3.by_ref], :int
  attach_function :sqlite3_extended_errcode, :sqlite3_extended_errcode, [Sqlite3.by_ref], :int
  attach_function :sqlite3_errmsg, :sqlite3_errmsg, [Sqlite3.by_ref], :string
  attach_function :sqlite3_errmsg16, :sqlite3_errmsg16, [Sqlite3.by_ref], :pointer
  attach_function :sqlite3_errstr, :sqlite3_errstr, [:int], :string
  attach_function :sqlite3_error_offset, :sqlite3_error_offset, [Sqlite3.by_ref], :int

  class Sqlite3Stmt < FFI::Struct
  end

  attach_function :sqlite3_limit, :sqlite3_limit, [Sqlite3.by_ref, :int, :int], :int
  attach_function :sqlite3_prepare, :sqlite3_prepare, [Sqlite3.by_ref, :string, :int, :pointer, :pointer], :int
  attach_function :sqlite3_prepare_v2, :sqlite3_prepare_v2, [Sqlite3.by_ref, :string, :int, :pointer, :pointer], :int
  attach_function :sqlite3_prepare_v3, :sqlite3_prepare_v3, [Sqlite3.by_ref, :string, :int, :uint, :pointer, :pointer], :int
  attach_function :sqlite3_prepare16, :sqlite3_prepare16, [Sqlite3.by_ref, :pointer, :int, :pointer, :pointer], :int
  attach_function :sqlite3_prepare16_v2, :sqlite3_prepare16_v2, [Sqlite3.by_ref, :pointer, :int, :pointer, :pointer], :int
  attach_function :sqlite3_prepare16_v3, :sqlite3_prepare16_v3, [Sqlite3.by_ref, :pointer, :int, :uint, :pointer, :pointer], :int
  attach_function :sqlite3_sql, :sqlite3_sql, [Sqlite3Stmt.by_ref], :string
  attach_function :sqlite3_expanded_sql, :sqlite3_expanded_sql, [Sqlite3Stmt.by_ref], :string
  attach_function :sqlite3_stmt_readonly, :sqlite3_stmt_readonly, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_stmt_isexplain, :sqlite3_stmt_isexplain, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_stmt_explain, :sqlite3_stmt_explain, [Sqlite3Stmt.by_ref, :int], :int
  attach_function :sqlite3_stmt_busy, :sqlite3_stmt_busy, [Sqlite3Stmt.by_ref], :int

  class Sqlite3Value < FFI::Struct
  end

  class Sqlite3Context < FFI::Struct
  end

  callback :sqlite3_bind_blob__callback, [:pointer], :void
  attach_function :sqlite3_bind_blob, :sqlite3_bind_blob, [Sqlite3Stmt.by_ref, :int, :pointer, :int, :sqlite3_bind_blob__callback], :int
  callback :sqlite3_bind_blob64__callback, [:pointer], :void
  attach_function :sqlite3_bind_blob64, :sqlite3_bind_blob64, [Sqlite3Stmt.by_ref, :int, :pointer, :ulong_long, :sqlite3_bind_blob64__callback], :int
  attach_function :sqlite3_bind_double, :sqlite3_bind_double, [Sqlite3Stmt.by_ref, :int, :double], :int
  attach_function :sqlite3_bind_int, :sqlite3_bind_int, [Sqlite3Stmt.by_ref, :int, :int], :int
  attach_function :sqlite3_bind_int64, :sqlite3_bind_int64, [Sqlite3Stmt.by_ref, :int, :long_long], :int
  attach_function :sqlite3_bind_null, :sqlite3_bind_null, [Sqlite3Stmt.by_ref, :int], :int
  callback :sqlite3_bind_text__callback, [:pointer], :void
  attach_function :sqlite3_bind_text, :sqlite3_bind_text, [Sqlite3Stmt.by_ref, :int, :string, :int, :sqlite3_bind_text__callback], :int
  callback :sqlite3_bind_text16__callback, [:pointer], :void
  attach_function :sqlite3_bind_text16, :sqlite3_bind_text16, [Sqlite3Stmt.by_ref, :int, :pointer, :int, :sqlite3_bind_text16__callback], :int
  callback :sqlite3_bind_text64__callback, [:pointer], :void
  attach_function :sqlite3_bind_text64, :sqlite3_bind_text64, [Sqlite3Stmt.by_ref, :int, :string, :ulong_long, :sqlite3_bind_text64__callback, :uchar], :int
  attach_function :sqlite3_bind_value, :sqlite3_bind_value, [Sqlite3Stmt.by_ref, :int, Sqlite3Value.by_ref], :int
  callback :sqlite3_bind_pointer__callback, [:pointer], :void
  attach_function :sqlite3_bind_pointer, :sqlite3_bind_pointer, [Sqlite3Stmt.by_ref, :int, :pointer, :string, :sqlite3_bind_pointer__callback], :int
  attach_function :sqlite3_bind_zeroblob, :sqlite3_bind_zeroblob, [Sqlite3Stmt.by_ref, :int, :int], :int
  attach_function :sqlite3_bind_zeroblob64, :sqlite3_bind_zeroblob64, [Sqlite3Stmt.by_ref, :int, :ulong_long], :int
  attach_function :sqlite3_bind_parameter_count, :sqlite3_bind_parameter_count, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_bind_parameter_name, :sqlite3_bind_parameter_name, [Sqlite3Stmt.by_ref, :int], :string
  attach_function :sqlite3_bind_parameter_index, :sqlite3_bind_parameter_index, [Sqlite3Stmt.by_ref, :string], :int
  attach_function :sqlite3_clear_bindings, :sqlite3_clear_bindings, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_column_count, :sqlite3_column_count, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_column_name, :sqlite3_column_name, [Sqlite3Stmt.by_ref, :int], :string
  attach_function :sqlite3_column_name16, :sqlite3_column_name16, [Sqlite3Stmt.by_ref, :int], :pointer
  attach_function :sqlite3_column_database_name, :sqlite3_column_database_name, [Sqlite3Stmt.by_ref, :int], :string
  attach_function :sqlite3_column_database_name16, :sqlite3_column_database_name16, [Sqlite3Stmt.by_ref, :int], :pointer
  attach_function :sqlite3_column_table_name, :sqlite3_column_table_name, [Sqlite3Stmt.by_ref, :int], :string
  attach_function :sqlite3_column_table_name16, :sqlite3_column_table_name16, [Sqlite3Stmt.by_ref, :int], :pointer
  attach_function :sqlite3_column_origin_name, :sqlite3_column_origin_name, [Sqlite3Stmt.by_ref, :int], :string
  attach_function :sqlite3_column_origin_name16, :sqlite3_column_origin_name16, [Sqlite3Stmt.by_ref, :int], :pointer
  attach_function :sqlite3_column_decltype, :sqlite3_column_decltype, [Sqlite3Stmt.by_ref, :int], :string
  attach_function :sqlite3_column_decltype16, :sqlite3_column_decltype16, [Sqlite3Stmt.by_ref, :int], :pointer
  attach_function :sqlite3_step, :sqlite3_step, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_data_count, :sqlite3_data_count, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_column_blob, :sqlite3_column_blob, [Sqlite3Stmt.by_ref, :int], :pointer
  attach_function :sqlite3_column_double, :sqlite3_column_double, [Sqlite3Stmt.by_ref, :int], :double
  attach_function :sqlite3_column_int, :sqlite3_column_int, [Sqlite3Stmt.by_ref, :int], :int
  attach_function :sqlite3_column_int64, :sqlite3_column_int64, [Sqlite3Stmt.by_ref, :int], :long_long
  attach_function :sqlite3_column_text, :sqlite3_column_text, [Sqlite3Stmt.by_ref, :int], :pointer
  attach_function :sqlite3_column_text16, :sqlite3_column_text16, [Sqlite3Stmt.by_ref, :int], :pointer
  attach_function :sqlite3_column_value, :sqlite3_column_value, [Sqlite3Stmt.by_ref, :int], Sqlite3Value.by_ref
  attach_function :sqlite3_column_bytes, :sqlite3_column_bytes, [Sqlite3Stmt.by_ref, :int], :int
  attach_function :sqlite3_column_bytes16, :sqlite3_column_bytes16, [Sqlite3Stmt.by_ref, :int], :int
  attach_function :sqlite3_column_type, :sqlite3_column_type, [Sqlite3Stmt.by_ref, :int], :int
  attach_function :sqlite3_finalize, :sqlite3_finalize, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_reset, :sqlite3_reset, [Sqlite3Stmt.by_ref], :int
  callback :sqlite3_create_function_xFunc_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function_xStep_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function_xFinal_callback, [:pointer], :void
  attach_function :sqlite3_create_function, :sqlite3_create_function, [Sqlite3.by_ref, :string, :int, :int, :pointer, :sqlite3_create_function_xFunc_callback, :sqlite3_create_function_xStep_callback, :sqlite3_create_function_xFinal_callback], :int
  callback :sqlite3_create_function16_xFunc_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function16_xStep_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function16_xFinal_callback, [:pointer], :void
  attach_function :sqlite3_create_function16, :sqlite3_create_function16, [Sqlite3.by_ref, :pointer, :int, :int, :pointer, :sqlite3_create_function16_xFunc_callback, :sqlite3_create_function16_xStep_callback, :sqlite3_create_function16_xFinal_callback], :int
  callback :sqlite3_create_function_v2_xFunc_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function_v2_xStep_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_function_v2_xFinal_callback, [:pointer], :void
  callback :sqlite3_create_function_v2_xDestroy_callback, [:pointer], :void
  attach_function :sqlite3_create_function_v2, :sqlite3_create_function_v2, [Sqlite3.by_ref, :string, :int, :int, :pointer, :sqlite3_create_function_v2_xFunc_callback, :sqlite3_create_function_v2_xStep_callback, :sqlite3_create_function_v2_xFinal_callback, :sqlite3_create_function_v2_xDestroy_callback], :int
  callback :sqlite3_create_window_function_xStep_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_window_function_xFinal_callback, [:pointer], :void
  callback :sqlite3_create_window_function_xValue_callback, [:pointer], :void
  callback :sqlite3_create_window_function_xInverse_callback, [:pointer, :int, :pointer], :void
  callback :sqlite3_create_window_function_xDestroy_callback, [:pointer], :void
  attach_function :sqlite3_create_window_function, :sqlite3_create_window_function, [Sqlite3.by_ref, :string, :int, :int, :pointer, :sqlite3_create_window_function_xStep_callback, :sqlite3_create_window_function_xFinal_callback, :sqlite3_create_window_function_xValue_callback, :sqlite3_create_window_function_xInverse_callback, :sqlite3_create_window_function_xDestroy_callback], :int
  attach_function :sqlite3_aggregate_count, :sqlite3_aggregate_count, [Sqlite3Context.by_ref], :int
  attach_function :sqlite3_expired, :sqlite3_expired, [Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_transfer_bindings, :sqlite3_transfer_bindings, [Sqlite3Stmt.by_ref, Sqlite3Stmt.by_ref], :int
  attach_function :sqlite3_global_recover, :sqlite3_global_recover, [], :int
  attach_function :sqlite3_thread_cleanup, :sqlite3_thread_cleanup, [], :void
  callback :sqlite3_memory_alarm__callback, [:pointer, :long_long, :int], :void
  attach_function :sqlite3_memory_alarm, :sqlite3_memory_alarm, [:sqlite3_memory_alarm__callback, :pointer, :long_long], :int
  attach_function :sqlite3_value_blob, :sqlite3_value_blob, [Sqlite3Value.by_ref], :pointer
  attach_function :sqlite3_value_double, :sqlite3_value_double, [Sqlite3Value.by_ref], :double
  attach_function :sqlite3_value_int, :sqlite3_value_int, [Sqlite3Value.by_ref], :int
  attach_function :sqlite3_value_int64, :sqlite3_value_int64, [Sqlite3Value.by_ref], :long_long
  attach_function :sqlite3_value_pointer, :sqlite3_value_pointer, [Sqlite3Value.by_ref, :string], :pointer
  attach_function :sqlite3_value_text, :sqlite3_value_text, [Sqlite3Value.by_ref], :pointer
  attach_function :sqlite3_value_text16, :sqlite3_value_text16, [Sqlite3Value.by_ref], :pointer
  attach_function :sqlite3_value_text16le, :sqlite3_value_text16le, [Sqlite3Value.by_ref], :pointer
  attach_function :sqlite3_value_text16be, :sqlite3_value_text16be, [Sqlite3Value.by_ref], :pointer
  attach_function :sqlite3_value_bytes, :sqlite3_value_bytes, [Sqlite3Value.by_ref], :int
  attach_function :sqlite3_value_bytes16, :sqlite3_value_bytes16, [Sqlite3Value.by_ref], :int
  attach_function :sqlite3_value_type, :sqlite3_value_type, [Sqlite3Value.by_ref], :int
  attach_function :sqlite3_value_numeric_type, :sqlite3_value_numeric_type, [Sqlite3Value.by_ref], :int
  attach_function :sqlite3_value_nochange, :sqlite3_value_nochange, [Sqlite3Value.by_ref], :int
  attach_function :sqlite3_value_frombind, :sqlite3_value_frombind, [Sqlite3Value.by_ref], :int
  attach_function :sqlite3_value_encoding, :sqlite3_value_encoding, [Sqlite3Value.by_ref], :int
  attach_function :sqlite3_value_subtype, :sqlite3_value_subtype, [Sqlite3Value.by_ref], :uint
  attach_function :sqlite3_value_dup, :sqlite3_value_dup, [Sqlite3Value.by_ref], Sqlite3Value.by_ref
  attach_function :sqlite3_value_free, :sqlite3_value_free, [Sqlite3Value.by_ref], :void
  attach_function :sqlite3_aggregate_context, :sqlite3_aggregate_context, [Sqlite3Context.by_ref, :int], :pointer
  attach_function :sqlite3_user_data, :sqlite3_user_data, [Sqlite3Context.by_ref], :pointer
  attach_function :sqlite3_context_db_handle, :sqlite3_context_db_handle, [Sqlite3Context.by_ref], Sqlite3.by_ref
  attach_function :sqlite3_get_auxdata, :sqlite3_get_auxdata, [Sqlite3Context.by_ref, :int], :pointer
  callback :sqlite3_set_auxdata__callback, [:pointer], :void
  attach_function :sqlite3_set_auxdata, :sqlite3_set_auxdata, [Sqlite3Context.by_ref, :int, :pointer, :sqlite3_set_auxdata__callback], :void
  attach_function :sqlite3_get_clientdata, :sqlite3_get_clientdata, [Sqlite3.by_ref, :string], :pointer
  callback :sqlite3_set_clientdata__callback, [:pointer], :void
  attach_function :sqlite3_set_clientdata, :sqlite3_set_clientdata, [Sqlite3.by_ref, :string, :pointer, :sqlite3_set_clientdata__callback], :int
  callback :sqlite3_destructor_type, [], :void
  callback :sqlite3_result_blob__callback, [:pointer], :void
  attach_function :sqlite3_result_blob, :sqlite3_result_blob, [Sqlite3Context.by_ref, :pointer, :int, :sqlite3_result_blob__callback], :void
  callback :sqlite3_result_blob64__callback, [:pointer], :void
  attach_function :sqlite3_result_blob64, :sqlite3_result_blob64, [Sqlite3Context.by_ref, :pointer, :ulong_long, :sqlite3_result_blob64__callback], :void
  attach_function :sqlite3_result_double, :sqlite3_result_double, [Sqlite3Context.by_ref, :double], :void
  attach_function :sqlite3_result_error, :sqlite3_result_error, [Sqlite3Context.by_ref, :string, :int], :void
  attach_function :sqlite3_result_error16, :sqlite3_result_error16, [Sqlite3Context.by_ref, :pointer, :int], :void
  attach_function :sqlite3_result_error_toobig, :sqlite3_result_error_toobig, [Sqlite3Context.by_ref], :void
  attach_function :sqlite3_result_error_nomem, :sqlite3_result_error_nomem, [Sqlite3Context.by_ref], :void
  attach_function :sqlite3_result_error_code, :sqlite3_result_error_code, [Sqlite3Context.by_ref, :int], :void
  attach_function :sqlite3_result_int, :sqlite3_result_int, [Sqlite3Context.by_ref, :int], :void
  attach_function :sqlite3_result_int64, :sqlite3_result_int64, [Sqlite3Context.by_ref, :long_long], :void
  attach_function :sqlite3_result_null, :sqlite3_result_null, [Sqlite3Context.by_ref], :void
  callback :sqlite3_result_text__callback, [:pointer], :void
  attach_function :sqlite3_result_text, :sqlite3_result_text, [Sqlite3Context.by_ref, :string, :int, :sqlite3_result_text__callback], :void
  callback :sqlite3_result_text64__callback, [:pointer], :void
  attach_function :sqlite3_result_text64, :sqlite3_result_text64, [Sqlite3Context.by_ref, :string, :ulong_long, :sqlite3_result_text64__callback, :uchar], :void
  callback :sqlite3_result_text16__callback, [:pointer], :void
  attach_function :sqlite3_result_text16, :sqlite3_result_text16, [Sqlite3Context.by_ref, :pointer, :int, :sqlite3_result_text16__callback], :void
  callback :sqlite3_result_text16le__callback, [:pointer], :void
  attach_function :sqlite3_result_text16le, :sqlite3_result_text16le, [Sqlite3Context.by_ref, :pointer, :int, :sqlite3_result_text16le__callback], :void
  callback :sqlite3_result_text16be__callback, [:pointer], :void
  attach_function :sqlite3_result_text16be, :sqlite3_result_text16be, [Sqlite3Context.by_ref, :pointer, :int, :sqlite3_result_text16be__callback], :void
  attach_function :sqlite3_result_value, :sqlite3_result_value, [Sqlite3Context.by_ref, Sqlite3Value.by_ref], :void
  callback :sqlite3_result_pointer__callback, [:pointer], :void
  attach_function :sqlite3_result_pointer, :sqlite3_result_pointer, [Sqlite3Context.by_ref, :pointer, :string, :sqlite3_result_pointer__callback], :void
  attach_function :sqlite3_result_zeroblob, :sqlite3_result_zeroblob, [Sqlite3Context.by_ref, :int], :void
  attach_function :sqlite3_result_zeroblob64, :sqlite3_result_zeroblob64, [Sqlite3Context.by_ref, :ulong_long], :int
  attach_function :sqlite3_result_subtype, :sqlite3_result_subtype, [Sqlite3Context.by_ref, :uint], :void
  callback :sqlite3_create_collation_xCompare_callback, [:pointer, :int, :pointer, :int, :pointer], :int
  attach_function :sqlite3_create_collation, :sqlite3_create_collation, [Sqlite3.by_ref, :string, :int, :pointer, :sqlite3_create_collation_xCompare_callback], :int
  callback :sqlite3_create_collation_v2_xCompare_callback, [:pointer, :int, :pointer, :int, :pointer], :int
  callback :sqlite3_create_collation_v2_xDestroy_callback, [:pointer], :void
  attach_function :sqlite3_create_collation_v2, :sqlite3_create_collation_v2, [Sqlite3.by_ref, :string, :int, :pointer, :sqlite3_create_collation_v2_xCompare_callback, :sqlite3_create_collation_v2_xDestroy_callback], :int
  callback :sqlite3_create_collation16_xCompare_callback, [:pointer, :int, :pointer, :int, :pointer], :int
  attach_function :sqlite3_create_collation16, :sqlite3_create_collation16, [Sqlite3.by_ref, :pointer, :int, :pointer, :sqlite3_create_collation16_xCompare_callback], :int
  callback :sqlite3_collation_needed__callback, [:pointer, :pointer, :int, :string], :void
  attach_function :sqlite3_collation_needed, :sqlite3_collation_needed, [Sqlite3.by_ref, :pointer, :sqlite3_collation_needed__callback], :int
  callback :sqlite3_collation_needed16__callback, [:pointer, :pointer, :int, :pointer], :void
  attach_function :sqlite3_collation_needed16, :sqlite3_collation_needed16, [Sqlite3.by_ref, :pointer, :sqlite3_collation_needed16__callback], :int
  attach_function :sqlite3_sleep, :sqlite3_sleep, [:int], :int
  attach_variable :Sqlite3TempDirectory, :sqlite3_temp_directory, :string
  attach_variable :Sqlite3DataDirectory, :sqlite3_data_directory, :string
  attach_function :sqlite3_win32_set_directory, :sqlite3_win32_set_directory, [:ulong, :pointer], :int
  attach_function :sqlite3_win32_set_directory8, :sqlite3_win32_set_directory8, [:ulong, :string], :int
  attach_function :sqlite3_win32_set_directory16, :sqlite3_win32_set_directory16, [:ulong, :pointer], :int
  attach_function :sqlite3_get_autocommit, :sqlite3_get_autocommit, [Sqlite3.by_ref], :int
  attach_function :sqlite3_db_handle, :sqlite3_db_handle, [Sqlite3Stmt.by_ref], Sqlite3.by_ref
  attach_function :sqlite3_db_name, :sqlite3_db_name, [Sqlite3.by_ref, :int], :string
  attach_function :sqlite3_db_filename, :sqlite3_db_filename, [Sqlite3.by_ref, :string], :string
  attach_function :sqlite3_db_readonly, :sqlite3_db_readonly, [Sqlite3.by_ref, :string], :int
  attach_function :sqlite3_txn_state, :sqlite3_txn_state, [Sqlite3.by_ref, :string], :int
  attach_function :sqlite3_next_stmt, :sqlite3_next_stmt, [Sqlite3.by_ref, Sqlite3Stmt.by_ref], Sqlite3Stmt.by_ref
  callback :sqlite3_commit_hook__callback, [:pointer], :int
  attach_function :sqlite3_commit_hook, :sqlite3_commit_hook, [Sqlite3.by_ref, :sqlite3_commit_hook__callback, :pointer], :pointer
  callback :sqlite3_rollback_hook__callback, [:pointer], :void
  attach_function :sqlite3_rollback_hook, :sqlite3_rollback_hook, [Sqlite3.by_ref, :sqlite3_rollback_hook__callback, :pointer], :pointer
  callback :sqlite3_autovacuum_pages__callback, [:pointer, :string, :uint, :uint, :uint], :uint
  callback :sqlite3_autovacuum_pages__callback, [:pointer], :void
  attach_function :sqlite3_autovacuum_pages, :sqlite3_autovacuum_pages, [Sqlite3.by_ref, :sqlite3_autovacuum_pages__callback, :pointer, :sqlite3_autovacuum_pages__callback], :int
  callback :sqlite3_update_hook__callback, [:pointer, :int, :string, :string, :long_long], :void
  attach_function :sqlite3_update_hook, :sqlite3_update_hook, [Sqlite3.by_ref, :sqlite3_update_hook__callback, :pointer], :pointer
  attach_function :sqlite3_enable_shared_cache, :sqlite3_enable_shared_cache, [:int], :int
  attach_function :sqlite3_release_memory, :sqlite3_release_memory, [:int], :int
  attach_function :sqlite3_db_release_memory, :sqlite3_db_release_memory, [Sqlite3.by_ref], :int
  attach_function :sqlite3_soft_heap_limit64, :sqlite3_soft_heap_limit64, [:long_long], :long_long
  attach_function :sqlite3_hard_heap_limit64, :sqlite3_hard_heap_limit64, [:long_long], :long_long
  attach_function :sqlite3_soft_heap_limit, :sqlite3_soft_heap_limit, [:int], :void
  attach_function :sqlite3_table_column_metadata, :sqlite3_table_column_metadata, [Sqlite3.by_ref, :string, :string, :string, :pointer, :pointer, :pointer, :pointer, :pointer], :int
  attach_function :sqlite3_load_extension, :sqlite3_load_extension, [Sqlite3.by_ref, :string, :string, :pointer], :int
  attach_function :sqlite3_enable_load_extension, :sqlite3_enable_load_extension, [Sqlite3.by_ref, :int], :int
  callback :sqlite3_auto_extension_xEntryPoint_callback, [], :void
  attach_function :sqlite3_auto_extension, :sqlite3_auto_extension, [:sqlite3_auto_extension_xEntryPoint_callback], :int
  callback :sqlite3_cancel_auto_extension_xEntryPoint_callback, [], :void
  attach_function :sqlite3_cancel_auto_extension, :sqlite3_cancel_auto_extension, [:sqlite3_cancel_auto_extension_xEntryPoint_callback], :int
  attach_function :sqlite3_reset_auto_extension, :sqlite3_reset_auto_extension, [], :void
  callback :sqlite3_module_xCreate_callback, [:pointer, :pointer, :int, :pointer, :pointer, :pointer], :int
  callback :sqlite3_module_xConnect_callback, [:pointer, :pointer, :int, :pointer, :pointer, :pointer], :int
  callback :sqlite3_module_xBestIndex_callback, [:pointer, :pointer], :int
  callback :sqlite3_module_xDisconnect_callback, [:pointer], :int
  callback :sqlite3_module_xDestroy_callback, [:pointer], :int
  callback :sqlite3_module_xOpen_callback, [:pointer, :pointer], :int
  callback :sqlite3_module_xClose_callback, [:pointer], :int
  callback :sqlite3_module_xFilter_callback, [:pointer, :int, :string, :int, :pointer], :int
  callback :sqlite3_module_xNext_callback, [:pointer], :int
  callback :sqlite3_module_xEof_callback, [:pointer], :int
  callback :sqlite3_module_xColumn_callback, [:pointer, :pointer, :int], :int
  callback :sqlite3_module_xRowid_callback, [:pointer, :pointer], :int
  callback :sqlite3_module_xUpdate_callback, [:pointer, :int, :pointer, :pointer], :int
  callback :sqlite3_module_xBegin_callback, [:pointer], :int
  callback :sqlite3_module_xSync_callback, [:pointer], :int
  callback :sqlite3_module_xCommit_callback, [:pointer], :int
  callback :sqlite3_module_xRollback_callback, [:pointer], :int
  callback :sqlite3_module_xFindFunction_callback, [:pointer, :int, :string, :pointer, :pointer], :int
  callback :sqlite3_module_xRename_callback, [:pointer, :string], :int
  callback :sqlite3_module_xSavepoint_callback, [:pointer, :int], :int
  callback :sqlite3_module_xRelease_callback, [:pointer, :int], :int
  callback :sqlite3_module_xRollbackTo_callback, [:pointer, :int], :int
  callback :sqlite3_module_xShadowName_callback, [:string], :int
  callback :sqlite3_module_xIntegrity_callback, [:pointer, :string, :string, :int, :pointer], :int

  class Sqlite3Module < FFI::Struct
    layout :i_version, :int,
           :x_create, :sqlite3_module_xCreate_callback,
           :x_connect, :sqlite3_module_xConnect_callback,
           :x_best_index, :sqlite3_module_xBestIndex_callback,
           :x_disconnect, :sqlite3_module_xDisconnect_callback,
           :x_destroy, :sqlite3_module_xDestroy_callback,
           :x_open, :sqlite3_module_xOpen_callback,
           :x_close, :sqlite3_module_xClose_callback,
           :x_filter, :sqlite3_module_xFilter_callback,
           :x_next, :sqlite3_module_xNext_callback,
           :x_eof, :sqlite3_module_xEof_callback,
           :x_column, :sqlite3_module_xColumn_callback,
           :x_rowid, :sqlite3_module_xRowid_callback,
           :x_update, :sqlite3_module_xUpdate_callback,
           :x_begin, :sqlite3_module_xBegin_callback,
           :x_sync, :sqlite3_module_xSync_callback,
           :x_commit, :sqlite3_module_xCommit_callback,
           :x_rollback, :sqlite3_module_xRollback_callback,
           :x_find_function, :sqlite3_module_xFindFunction_callback,
           :x_rename, :sqlite3_module_xRename_callback,
           :x_savepoint, :sqlite3_module_xSavepoint_callback,
           :x_release, :sqlite3_module_xRelease_callback,
           :x_rollback_to, :sqlite3_module_xRollbackTo_callback,
           :x_shadow_name, :sqlite3_module_xShadowName_callback,
           :x_integrity, :sqlite3_module_xIntegrity_callback
  end

  class Sqlite3IndexConstraint < FFI::Struct
    layout :i_column, :int,
           :op, :uchar,
           :usable, :uchar,
           :i_term_offset, :int
  end

  class Sqlite3IndexOrderby < FFI::Struct
    layout :i_column, :int,
           :desc, :uchar
  end

  class Sqlite3IndexConstraintUsage < FFI::Struct
    layout :argv_index, :int,
           :omit, :uchar
  end

  class Sqlite3IndexInfo < FFI::Struct
    layout :n_constraint, :int,
           :a_constraint, Sqlite3IndexConstraint.ptr,
           :n_order_by, :int,
           :a_order_by, Sqlite3IndexOrderby.ptr,
           :a_constraint_usage, Sqlite3IndexConstraintUsage.ptr,
           :idx_num, :int,
           :idx_str, :string,
           :need_to_free_idx_str, :int,
           :order_by_consumed, :int,
           :estimated_cost, :double,
           :estimated_rows, :long_long,
           :idx_flags, :int,
           :col_used, :ulong_long
  end

  attach_function :sqlite3_create_module, :sqlite3_create_module, [Sqlite3.by_ref, :string, Sqlite3Module.by_ref, :pointer], :int
  callback :sqlite3_create_module_v2_xDestroy_callback, [:pointer], :void
  attach_function :sqlite3_create_module_v2, :sqlite3_create_module_v2, [Sqlite3.by_ref, :string, Sqlite3Module.by_ref, :pointer, :sqlite3_create_module_v2_xDestroy_callback], :int
  attach_function :sqlite3_drop_modules, :sqlite3_drop_modules, [Sqlite3.by_ref, :pointer], :int

  class Sqlite3Vtab < FFI::Struct
    layout :p_module, :pointer,
           :n_ref, :int,
           :z_err_msg, :string
  end

  class Sqlite3VtabCursor < FFI::Struct
    layout :p_vtab, :pointer
  end

  attach_function :sqlite3_declare_vtab, :sqlite3_declare_vtab, [Sqlite3.by_ref, :string], :int
  attach_function :sqlite3_overload_function, :sqlite3_overload_function, [Sqlite3.by_ref, :string, :int], :int

  class Sqlite3Blob < FFI::Struct
  end

  attach_function :sqlite3_blob_open, :sqlite3_blob_open, [Sqlite3.by_ref, :string, :string, :string, :long_long, :int, :pointer], :int
  attach_function :sqlite3_blob_reopen, :sqlite3_blob_reopen, [Sqlite3Blob.by_ref, :long_long], :int
  attach_function :sqlite3_blob_close, :sqlite3_blob_close, [Sqlite3Blob.by_ref], :int
  attach_function :sqlite3_blob_bytes, :sqlite3_blob_bytes, [Sqlite3Blob.by_ref], :int
  attach_function :sqlite3_blob_read, :sqlite3_blob_read, [Sqlite3Blob.by_ref, :pointer, :int, :int], :int
  attach_function :sqlite3_blob_write, :sqlite3_blob_write, [Sqlite3Blob.by_ref, :pointer, :int, :int], :int
  attach_function :sqlite3_vfs_find, :sqlite3_vfs_find, [:string], Sqlite3Vfs.by_ref
  attach_function :sqlite3_vfs_register, :sqlite3_vfs_register, [Sqlite3Vfs.by_ref, :int], :int
  attach_function :sqlite3_vfs_unregister, :sqlite3_vfs_unregister, [Sqlite3Vfs.by_ref], :int
  attach_function :sqlite3_mutex_alloc, :sqlite3_mutex_alloc, [:int], Sqlite3Mutex.by_ref
  attach_function :sqlite3_mutex_free, :sqlite3_mutex_free, [Sqlite3Mutex.by_ref], :void
  attach_function :sqlite3_mutex_enter, :sqlite3_mutex_enter, [Sqlite3Mutex.by_ref], :void
  attach_function :sqlite3_mutex_try, :sqlite3_mutex_try, [Sqlite3Mutex.by_ref], :int
  attach_function :sqlite3_mutex_leave, :sqlite3_mutex_leave, [Sqlite3Mutex.by_ref], :void
  callback :sqlite3_mutex_methods_xMutexInit_callback, [], :int
  callback :sqlite3_mutex_methods_xMutexEnd_callback, [], :int
  callback :sqlite3_mutex_methods_xMutexAlloc_callback, [:int], Sqlite3Mutex.by_ref
  callback :sqlite3_mutex_methods_xMutexFree_callback, [:pointer], :void
  callback :sqlite3_mutex_methods_xMutexEnter_callback, [:pointer], :void
  callback :sqlite3_mutex_methods_xMutexTry_callback, [:pointer], :int
  callback :sqlite3_mutex_methods_xMutexLeave_callback, [:pointer], :void
  callback :sqlite3_mutex_methods_xMutexHeld_callback, [:pointer], :int
  callback :sqlite3_mutex_methods_xMutexNotheld_callback, [:pointer], :int

  class Sqlite3MutexMethods < FFI::Struct
    layout :x_mutex_init, :sqlite3_mutex_methods_xMutexInit_callback,
           :x_mutex_end, :sqlite3_mutex_methods_xMutexEnd_callback,
           :x_mutex_alloc, :sqlite3_mutex_methods_xMutexAlloc_callback,
           :x_mutex_free, :sqlite3_mutex_methods_xMutexFree_callback,
           :x_mutex_enter, :sqlite3_mutex_methods_xMutexEnter_callback,
           :x_mutex_try, :sqlite3_mutex_methods_xMutexTry_callback,
           :x_mutex_leave, :sqlite3_mutex_methods_xMutexLeave_callback,
           :x_mutex_held, :sqlite3_mutex_methods_xMutexHeld_callback,
           :x_mutex_notheld, :sqlite3_mutex_methods_xMutexNotheld_callback
  end

  attach_function :sqlite3_mutex_held, :sqlite3_mutex_held, [Sqlite3Mutex.by_ref], :int
  attach_function :sqlite3_mutex_notheld, :sqlite3_mutex_notheld, [Sqlite3Mutex.by_ref], :int
  attach_function :sqlite3_db_mutex, :sqlite3_db_mutex, [Sqlite3.by_ref], Sqlite3Mutex.by_ref
  attach_function :sqlite3_file_control, :sqlite3_file_control, [Sqlite3.by_ref, :string, :int, :pointer], :int
  attach_function :sqlite3_test_control, :sqlite3_test_control, [:int], :int
  attach_function :sqlite3_keyword_count, :sqlite3_keyword_count, [], :int
  attach_function :sqlite3_keyword_name, :sqlite3_keyword_name, [:int, :pointer, :pointer], :int
  attach_function :sqlite3_keyword_check, :sqlite3_keyword_check, [:string, :int], :int

  class Sqlite3Str < FFI::Struct
  end

  attach_function :sqlite3_str_new, :sqlite3_str_new, [Sqlite3.by_ref], Sqlite3Str.by_ref
  attach_function :sqlite3_str_finish, :sqlite3_str_finish, [Sqlite3Str.by_ref], :string
  attach_function :sqlite3_str_appendf, :sqlite3_str_appendf, [Sqlite3Str.by_ref, :string], :void
  attach_function :sqlite3_str_vappendf, :sqlite3_str_vappendf, [Sqlite3Str.by_ref, :string, :int], :void
  attach_function :sqlite3_str_append, :sqlite3_str_append, [Sqlite3Str.by_ref, :string, :int], :void
  attach_function :sqlite3_str_appendall, :sqlite3_str_appendall, [Sqlite3Str.by_ref, :string], :void
  attach_function :sqlite3_str_appendchar, :sqlite3_str_appendchar, [Sqlite3Str.by_ref, :int, :char], :void
  attach_function :sqlite3_str_reset, :sqlite3_str_reset, [Sqlite3Str.by_ref], :void
  attach_function :sqlite3_str_errcode, :sqlite3_str_errcode, [Sqlite3Str.by_ref], :int
  attach_function :sqlite3_str_length, :sqlite3_str_length, [Sqlite3Str.by_ref], :int
  attach_function :sqlite3_str_value, :sqlite3_str_value, [Sqlite3Str.by_ref], :string
  attach_function :sqlite3_status, :sqlite3_status, [:int, :pointer, :pointer, :int], :int
  attach_function :sqlite3_status64, :sqlite3_status64, [:int, :pointer, :pointer, :int], :int
  attach_function :sqlite3_db_status, :sqlite3_db_status, [Sqlite3.by_ref, :int, :pointer, :pointer, :int], :int
  attach_function :sqlite3_stmt_status, :sqlite3_stmt_status, [Sqlite3Stmt.by_ref, :int, :int], :int

  class Sqlite3Pcache < FFI::Struct
  end

  class Sqlite3PcachePage < FFI::Struct
    layout :p_buf, :pointer,
           :p_extra, :pointer
  end

  callback :sqlite3_pcache_methods2_xInit_callback, [:pointer], :int
  callback :sqlite3_pcache_methods2_xShutdown_callback, [:pointer], :void
  callback :sqlite3_pcache_methods2_xCreate_callback, [:int, :int, :int], Sqlite3Pcache.by_ref
  callback :sqlite3_pcache_methods2_xCachesize_callback, [:pointer, :int], :void
  callback :sqlite3_pcache_methods2_xPagecount_callback, [:pointer], :int
  callback :sqlite3_pcache_methods2_xFetch_callback, [:pointer, :uint, :int], Sqlite3PcachePage.by_ref
  callback :sqlite3_pcache_methods2_xUnpin_callback, [:pointer, :pointer, :int], :void
  callback :sqlite3_pcache_methods2_xRekey_callback, [:pointer, :pointer, :uint, :uint], :void
  callback :sqlite3_pcache_methods2_xTruncate_callback, [:pointer, :uint], :void
  callback :sqlite3_pcache_methods2_xDestroy_callback, [:pointer], :void
  callback :sqlite3_pcache_methods2_xShrink_callback, [:pointer], :void

  class Sqlite3PcacheMethods2 < FFI::Struct
    layout :i_version, :int,
           :p_arg, :pointer,
           :x_init, :sqlite3_pcache_methods2_xInit_callback,
           :x_shutdown, :sqlite3_pcache_methods2_xShutdown_callback,
           :x_create, :sqlite3_pcache_methods2_xCreate_callback,
           :x_cachesize, :sqlite3_pcache_methods2_xCachesize_callback,
           :x_pagecount, :sqlite3_pcache_methods2_xPagecount_callback,
           :x_fetch, :sqlite3_pcache_methods2_xFetch_callback,
           :x_unpin, :sqlite3_pcache_methods2_xUnpin_callback,
           :x_rekey, :sqlite3_pcache_methods2_xRekey_callback,
           :x_truncate, :sqlite3_pcache_methods2_xTruncate_callback,
           :x_destroy, :sqlite3_pcache_methods2_xDestroy_callback,
           :x_shrink, :sqlite3_pcache_methods2_xShrink_callback
  end

  callback :sqlite3_pcache_methods_xInit_callback, [:pointer], :int
  callback :sqlite3_pcache_methods_xShutdown_callback, [:pointer], :void
  callback :sqlite3_pcache_methods_xCreate_callback, [:int, :int], Sqlite3Pcache.by_ref
  callback :sqlite3_pcache_methods_xCachesize_callback, [:pointer, :int], :void
  callback :sqlite3_pcache_methods_xPagecount_callback, [:pointer], :int
  callback :sqlite3_pcache_methods_xFetch_callback, [:pointer, :uint, :int], :pointer
  callback :sqlite3_pcache_methods_xUnpin_callback, [:pointer, :pointer, :int], :void
  callback :sqlite3_pcache_methods_xRekey_callback, [:pointer, :pointer, :uint, :uint], :void
  callback :sqlite3_pcache_methods_xTruncate_callback, [:pointer, :uint], :void
  callback :sqlite3_pcache_methods_xDestroy_callback, [:pointer], :void

  class Sqlite3PcacheMethods < FFI::Struct
    layout :p_arg, :pointer,
           :x_init, :sqlite3_pcache_methods_xInit_callback,
           :x_shutdown, :sqlite3_pcache_methods_xShutdown_callback,
           :x_create, :sqlite3_pcache_methods_xCreate_callback,
           :x_cachesize, :sqlite3_pcache_methods_xCachesize_callback,
           :x_pagecount, :sqlite3_pcache_methods_xPagecount_callback,
           :x_fetch, :sqlite3_pcache_methods_xFetch_callback,
           :x_unpin, :sqlite3_pcache_methods_xUnpin_callback,
           :x_rekey, :sqlite3_pcache_methods_xRekey_callback,
           :x_truncate, :sqlite3_pcache_methods_xTruncate_callback,
           :x_destroy, :sqlite3_pcache_methods_xDestroy_callback
  end

  class Sqlite3Backup < FFI::Struct
  end

  attach_function :sqlite3_backup_init, :sqlite3_backup_init, [Sqlite3.by_ref, :string, Sqlite3.by_ref, :string], Sqlite3Backup.by_ref
  attach_function :sqlite3_backup_step, :sqlite3_backup_step, [Sqlite3Backup.by_ref, :int], :int
  attach_function :sqlite3_backup_finish, :sqlite3_backup_finish, [Sqlite3Backup.by_ref], :int
  attach_function :sqlite3_backup_remaining, :sqlite3_backup_remaining, [Sqlite3Backup.by_ref], :int
  attach_function :sqlite3_backup_pagecount, :sqlite3_backup_pagecount, [Sqlite3Backup.by_ref], :int
  callback :sqlite3_unlock_notify_xNotify_callback, [:pointer, :int], :void
  attach_function :sqlite3_unlock_notify, :sqlite3_unlock_notify, [Sqlite3.by_ref, :sqlite3_unlock_notify_xNotify_callback, :pointer], :int
  attach_function :sqlite3_stricmp, :sqlite3_stricmp, [:string, :string], :int
  attach_function :sqlite3_strnicmp, :sqlite3_strnicmp, [:string, :string, :int], :int
  attach_function :sqlite3_strglob, :sqlite3_strglob, [:string, :string], :int
  attach_function :sqlite3_strlike, :sqlite3_strlike, [:string, :string, :uint], :int
  attach_function :sqlite3_log, :sqlite3_log, [:int, :string], :void
  callback :sqlite3_wal_hook__callback, [:pointer, :pointer, :string, :int], :int
  attach_function :sqlite3_wal_hook, :sqlite3_wal_hook, [Sqlite3.by_ref, :sqlite3_wal_hook__callback, :pointer], :pointer
  attach_function :sqlite3_wal_autocheckpoint, :sqlite3_wal_autocheckpoint, [Sqlite3.by_ref, :int], :int
  attach_function :sqlite3_wal_checkpoint, :sqlite3_wal_checkpoint, [Sqlite3.by_ref, :string], :int
  attach_function :sqlite3_wal_checkpoint_v2, :sqlite3_wal_checkpoint_v2, [Sqlite3.by_ref, :string, :int, :pointer, :pointer], :int
  attach_function :sqlite3_vtab_config, :sqlite3_vtab_config, [Sqlite3.by_ref, :int], :int
  attach_function :sqlite3_vtab_on_conflict, :sqlite3_vtab_on_conflict, [Sqlite3.by_ref], :int
  attach_function :sqlite3_vtab_nochange, :sqlite3_vtab_nochange, [Sqlite3Context.by_ref], :int
  attach_function :sqlite3_vtab_collation, :sqlite3_vtab_collation, [Sqlite3IndexInfo.by_ref, :int], :string
  attach_function :sqlite3_vtab_distinct, :sqlite3_vtab_distinct, [Sqlite3IndexInfo.by_ref], :int
  attach_function :sqlite3_vtab_in, :sqlite3_vtab_in, [Sqlite3IndexInfo.by_ref, :int, :int], :int
  attach_function :sqlite3_vtab_in_first, :sqlite3_vtab_in_first, [Sqlite3Value.by_ref, :pointer], :int
  attach_function :sqlite3_vtab_in_next, :sqlite3_vtab_in_next, [Sqlite3Value.by_ref, :pointer], :int
  attach_function :sqlite3_vtab_rhs_value, :sqlite3_vtab_rhs_value, [Sqlite3IndexInfo.by_ref, :int, :pointer], :int
  attach_function :sqlite3_stmt_scanstatus, :sqlite3_stmt_scanstatus, [Sqlite3Stmt.by_ref, :int, :int, :pointer], :int
  attach_function :sqlite3_stmt_scanstatus_v2, :sqlite3_stmt_scanstatus_v2, [Sqlite3Stmt.by_ref, :int, :int, :int, :pointer], :int
  attach_function :sqlite3_stmt_scanstatus_reset, :sqlite3_stmt_scanstatus_reset, [Sqlite3Stmt.by_ref], :void
  attach_function :sqlite3_db_cacheflush, :sqlite3_db_cacheflush, [Sqlite3.by_ref], :int
  attach_function :sqlite3_system_errno, :sqlite3_system_errno, [Sqlite3.by_ref], :int

  class Sqlite3Snapshot < FFI::Struct
    layout :hidden, [:uchar, 48]
  end

  attach_function :sqlite3_snapshot_get, :sqlite3_snapshot_get, [Sqlite3.by_ref, :string, :pointer], :int
  attach_function :sqlite3_snapshot_open, :sqlite3_snapshot_open, [Sqlite3.by_ref, :string, Sqlite3Snapshot.by_ref], :int
  attach_function :sqlite3_snapshot_free, :sqlite3_snapshot_free, [Sqlite3Snapshot.by_ref], :void
  attach_function :sqlite3_snapshot_cmp, :sqlite3_snapshot_cmp, [Sqlite3Snapshot.by_ref, Sqlite3Snapshot.by_ref], :int
  attach_function :sqlite3_snapshot_recover, :sqlite3_snapshot_recover, [Sqlite3.by_ref, :string], :int
  attach_function :sqlite3_serialize, :sqlite3_serialize, [Sqlite3.by_ref, :string, :pointer, :uint], :pointer
  attach_function :sqlite3_deserialize, :sqlite3_deserialize, [Sqlite3.by_ref, :string, :pointer, :long_long, :long_long, :uint], :int
  typedef :double, :sqlite3_rtree_dbl
  callback :sqlite3_rtree_geometry_callback_xGeom_callback, [:pointer, :int, :pointer, :pointer], :int
  attach_function :sqlite3_rtree_geometry_callback, :sqlite3_rtree_geometry_callback, [Sqlite3.by_ref, :string, :sqlite3_rtree_geometry_callback_xGeom_callback, :pointer], :int
  callback :sqlite3_rtree_geometry_xDelUser_callback, [:pointer], :void

  class Sqlite3RtreeGeometry < FFI::Struct
    layout :p_context, :pointer,
           :n_param, :int,
           :a_param, :pointer,
           :p_user, :pointer,
           :x_del_user, :sqlite3_rtree_geometry_xDelUser_callback
  end

  callback :sqlite3_rtree_query_callback_xQueryFunc_callback, [:pointer], :int
  callback :sqlite3_rtree_query_callback_xDestructor_callback, [:pointer], :void
  attach_function :sqlite3_rtree_query_callback, :sqlite3_rtree_query_callback, [Sqlite3.by_ref, :string, :sqlite3_rtree_query_callback_xQueryFunc_callback, :pointer, :sqlite3_rtree_query_callback_xDestructor_callback], :int
  callback :sqlite3_rtree_query_info_xDelUser_callback, [:pointer], :void

  class Sqlite3RtreeQueryInfo < FFI::Struct
    layout :p_context, :pointer,
           :n_param, :int,
           :a_param, :pointer,
           :p_user, :pointer,
           :x_del_user, :sqlite3_rtree_query_info_xDelUser_callback,
           :a_coord, :pointer,
           :an_queue, :pointer,
           :n_coord, :int,
           :i_level, :int,
           :mx_level, :int,
           :i_rowid, :long_long,
           :r_parent_score, :double,
           :e_parent_within, :int,
           :e_within, :int,
           :r_score, :double,
           :ap_sql_param, :pointer
  end

  class Fts5Context < FFI::Struct
  end

  callback :fts5_extension_function, [], :void

  class Fts5PhraseIter < FFI::Struct
    layout :a, :pointer,
           :b, :pointer
  end

  callback :Fts5ExtensionApi_xUserData_callback, [:pointer], :pointer
  callback :Fts5ExtensionApi_xColumnCount_callback, [:pointer], :int
  callback :Fts5ExtensionApi_xRowCount_callback, [:pointer, :pointer], :int
  callback :Fts5ExtensionApi_xColumnTotalSize_callback, [:pointer, :int, :pointer], :int
  callback :Fts5ExtensionApi_xTokenize_callback, [:pointer, :string, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xPhraseCount_callback, [:pointer], :int
  callback :Fts5ExtensionApi_xPhraseSize_callback, [:pointer, :int], :int
  callback :Fts5ExtensionApi_xInstCount_callback, [:pointer, :pointer], :int
  callback :Fts5ExtensionApi_xInst_callback, [:pointer, :int, :pointer, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xRowid_callback, [:pointer], :long_long
  callback :Fts5ExtensionApi_xColumnText_callback, [:pointer, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xColumnSize_callback, [:pointer, :int, :pointer], :int
  callback :Fts5ExtensionApi_xQueryPhrase_callback, [:pointer, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xSetAuxdata_callback, [:pointer, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xGetAuxdata_callback, [:pointer, :int], :pointer
  callback :Fts5ExtensionApi_xPhraseFirst_callback, [:pointer, :int, :pointer, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xPhraseNext_callback, [:pointer, :pointer, :pointer, :pointer], :void
  callback :Fts5ExtensionApi_xPhraseFirstColumn_callback, [:pointer, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xPhraseNextColumn_callback, [:pointer, :pointer, :pointer], :void
  callback :Fts5ExtensionApi_xQueryToken_callback, [:pointer, :int, :int, :pointer, :pointer], :int
  callback :Fts5ExtensionApi_xInstToken_callback, [:pointer, :int, :int, :pointer, :pointer], :int

  class Fts5ExtensionApi < FFI::Struct
    layout :i_version, :int,
           :x_user_data, :Fts5ExtensionApi_xUserData_callback,
           :x_column_count, :Fts5ExtensionApi_xColumnCount_callback,
           :x_row_count, :Fts5ExtensionApi_xRowCount_callback,
           :x_column_total_size, :Fts5ExtensionApi_xColumnTotalSize_callback,
           :x_tokenize, :Fts5ExtensionApi_xTokenize_callback,
           :x_phrase_count, :Fts5ExtensionApi_xPhraseCount_callback,
           :x_phrase_size, :Fts5ExtensionApi_xPhraseSize_callback,
           :x_inst_count, :Fts5ExtensionApi_xInstCount_callback,
           :x_inst, :Fts5ExtensionApi_xInst_callback,
           :x_rowid, :Fts5ExtensionApi_xRowid_callback,
           :x_column_text, :Fts5ExtensionApi_xColumnText_callback,
           :x_column_size, :Fts5ExtensionApi_xColumnSize_callback,
           :x_query_phrase, :Fts5ExtensionApi_xQueryPhrase_callback,
           :x_set_auxdata, :Fts5ExtensionApi_xSetAuxdata_callback,
           :x_get_auxdata, :Fts5ExtensionApi_xGetAuxdata_callback,
           :x_phrase_first, :Fts5ExtensionApi_xPhraseFirst_callback,
           :x_phrase_next, :Fts5ExtensionApi_xPhraseNext_callback,
           :x_phrase_first_column, :Fts5ExtensionApi_xPhraseFirstColumn_callback,
           :x_phrase_next_column, :Fts5ExtensionApi_xPhraseNextColumn_callback,
           :x_query_token, :Fts5ExtensionApi_xQueryToken_callback,
           :x_inst_token, :Fts5ExtensionApi_xInstToken_callback
  end

  class Fts5Tokenizer < FFI::Struct
  end

  callback :fts5_tokenizer_xCreate_callback, [:pointer, :pointer, :int, :pointer], :int
  callback :fts5_tokenizer_xDelete_callback, [:pointer], :void
  callback :fts5_tokenizer_xTokenize_callback, [:pointer, :pointer, :int, :string, :int, :pointer], :int

  class Fts5Tokenizer < FFI::Struct
    layout :x_create, :fts5_tokenizer_xCreate_callback,
           :x_delete, :fts5_tokenizer_xDelete_callback,
           :x_tokenize, :fts5_tokenizer_xTokenize_callback
  end

  callback :fts5_api_xCreateTokenizer_callback, [:pointer, :string, :pointer, :pointer, :pointer], :int
  callback :fts5_api_xFindTokenizer_callback, [:pointer, :string, :pointer, :pointer], :int
  callback :fts5_api_xCreateFunction_callback, [:pointer, :string, :pointer, :pointer, :pointer], :int

  class Fts5Api < FFI::Struct
    layout :i_version, :int,
           :x_create_tokenizer, :fts5_api_xCreateTokenizer_callback,
           :x_find_tokenizer, :fts5_api_xFindTokenizer_callback,
           :x_create_function, :fts5_api_xCreateFunction_callback
  end
end
