# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

FFI::DynamicLibrary::SEARCH_PATH = ["c:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin"]

module Structs
  extend FFI::Library

  def self.library_names
    ["structs"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  class CXFileUniqueID < FFI::Struct
    layout :data, [:ulong_long, 3]
  end

  class MyArrayT < FFI::Struct
    layout :value, :int,
           :string, [:uchar, 4]
  end

  attach_variable :MyArrayT, :MyArray_t, MyArrayT

  class U < FFI::Union
    layout :sdata, :string,
           :idata, :int
  end

  class FTextItemT < FFI::Struct
    layout :offset, :int,
           :data_type, :int,
           :u, U
  end

  class FTextItemsT < FFI::Struct
    layout :len, :uchar,
           :val, FTextItemT.ptr
  end
end
