# Generated by ruby-bindgen (1.0.0)

module Structs

  class CXFileUniqueID < FFI::Struct
    layout :data, [:ulong_long, 3]
  end

  class MyArrayT < FFI::Struct
    layout :value, :int,
           :string, [:uchar, 4]
  end

  attach_variable :MyArrayT, :MyArray_t, MyArrayT

  class U < FFI::Union
    layout :sdata, :pointer,
           :idata, :int
  end

  class FTextItemT < FFI::Struct
    layout :offset, :int,
           :data_type, :int,
           :u, U
  end

  class FTextItemsT < FFI::Struct
    layout :len, :uchar,
           :val, FTextItemT.ptr
  end

  class TypeCoverageStruct < FFI::Struct
    layout :f, :float,
           :us, :ushort,
           :s, :short,
           :b, :bool,
           :u8, :uint8_t
  end
end
