# This file was generated by ruby-bindgen. Please do not edit by hand.
require 'ffi'

FFI::DynamicLibrary::SEARCH_PATH ||= ["c:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin"]

module VersionGuards
  extend FFI::Library

  def self.library_names
    ["version_guards"]
  end

  def self.library_versions
    []
  end

  def self.search_names
    result = Array.new
    self.library_names.each do |name|
      result << "lib#{name}"
      self.library_versions.each do |version|
        case RbConfig::CONFIG['host_os']
          when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
            result << "lib#{name}-#{version}"
            result << "lib#{name}_#{version}"
          when /darwin|mac os/
            result << "lib#{name}.#{version}"
          else
            result << "lib#{name}.so.#{version}"
        end
      end
    end
    result
  end

  ffi_lib self.search_names

  TEST_VERSION = 25000
  attach_function :stable_function, :stableFunction, [:int], :int

  class StableStruct < FFI::Struct
    layout :x, :int,
           :y, :int
  end

  StableEnum = enum(
    :STABLE_A, 0,
    :STABLE_B, 1
  )

  typedef :int, :stable_typedef
  if TEST_VERSION >= 20000
    attach_function :new_function, :newFunction, [:double], :void

    class NewStruct < FFI::Struct
      layout :a, :int,
             :b, :int
    end

    NewEnum = enum(
      :NEW_A, 10,
      :NEW_B, 20
    )

    typedef :double, :new_typedef
  end
  if TEST_VERSION >= 30000
    attach_function :future_function, :futureFunction, [:int, :int], :int
  end
end
