# Generated by ruby-bindgen (1.0.0)

module VersionGuards
  attach_function :stable_function, :stableFunction, [:int], :int

  class StableStruct < FFI::Struct
    layout :x, :int,
           :y, :int
  end

  StableEnum = enum(
    :STABLE_A, 0,
    :STABLE_B, 1
  )

  typedef :int, :stable_typedef
  if version_guards_version >= 30000
    class MixedStruct < FFI::Struct
      layout :stable_field, :int,
             :versioned_field, :int,
             :future_field, :double
    end
  elsif version_guards_version >= 20000
    class MixedStruct < FFI::Struct
      layout :stable_field, :int,
             :versioned_field, :int
    end
  else
    class MixedStruct < FFI::Struct
      layout :stable_field, :int
    end
  end
  if version_guards_version >= 30000
    MixedEnum = enum(
      :MIXED_A, 0,
      :MIXED_B, 1,
      :MIXED_C, 2
    )
  elsif version_guards_version >= 20000
    MixedEnum = enum(
      :MIXED_A, 0,
      :MIXED_B, 1
    )
  else
    MixedEnum = enum(
      :MIXED_A, 0
    )
  end
  if version_guards_version >= 20000
    attach_function :new_function, :newFunction, [:double], :void

    class NewStruct < FFI::Struct
      layout :a, :int,
             :b, :int
    end

    NewEnum = enum(
      :NEW_A, 10,
      :NEW_B, 20
    )

    typedef :double, :new_typedef
    attach_function :overridden_function, :overriddenFunction, [:int, :int, :int], :bool
  end
  if version_guards_version >= 30000
    attach_function :future_function, :futureFunction, [:int, :int], :int
  end
end
