// Generated by ruby-bindgen (1.0.0)

#pragma once

#include <rice/rice.hpp>

extern "C"
#if defined(_WIN32)
__declspec(dllexport)
#else
__attribute__((visibility("default")))
#endif
void Init_myproject();
